### ISSUE TITLE
Function on confirm not working

### ISSUE THREAD

**Issue by schris12** [t4t5/sweetalert#103]
Hello, I have used SweetAlert before with success but today I tried using it with Ionic and I have a problem. 
When I use it like this it executes the something function but it's not waiting for the confirm button to be pressed:
```javascript
$scope.something=function(){console.log('test')};
swal({title: 'True',text: '',type: 'success',confirmButtonText: 'Next' },$scope.something());
```

When I use it like this, it's not working at all:
```javascript
swal({title: 'True',text: '',type: 'success',confirmButtonText: 'Next' },function(){console.log('test')});
```

Any ideas?

**Comment by borodatych** [comment]
Many thanks.
There is little, or even a big "but" - if you call in the active modeling window, the buttons are not working.
Please tell me how to get rid of the scourge?
