### ISSUE TITLE
Getting 'Uncaught RangeError: Maximum call stack size exceeded.' error

### ISSUE THREAD

**Issue by ramysa** [t4t5/sweetalert#104]
SweetAlert is working perfectly, but I am having an error. I use bootstrap modal and while I have it opened, I use as well SweetAlert. After I click 'Cancel', 'OK'.... on the SweetAlert, I get this 'Uncaught RangeError: Maximum call stack size exceeded' error. The problem is here:

```
      if (btnIndex === -1) {
        // Something in the dom, but not a visible button. Focus back on the button.
        $targetElement.focus();
      }
```

When I comment this code, I don't have the error anymore.
PS: I don't get this error when I don't have the modal opened.

**Comment by jbh-** [comment]
I ran into the same issue and came up with a decent way of handling it. I basically hide the modal, show swal, and on confirm bring back the modal. If one is using magnific popup for example, the code would look similar to this:

```javascript
$('.mfp-wrap').hide();
swal({
    title: "Updated!",
    text: "#" + data.updateData['number'] + " was successfully updated",
    type: "success"
},
function(isConfirm) {
    $('.mfp-wrap').show();
});```

This is basically what @littleneotrix was talking about. I just didn't catch his explanation at first and figured I would give a more detailed example. I find it to be an elegant enough solution for my use case.

For those asking, I don't think there is much that the developers can do to fix this problem. Double modals and callbacks are hefty.

**Comment by reason211** [comment]
I have the solution:
Comment out：
`$targetElement.focus (); `
_Probably in the 413 row._

**Comment by Walllter** [comment]
Just add `$.fn.modal.Constructor.prototype.enforceFocus = function () {};` before call `swal(...);`

**Comment by t4t5** [comment]
Let's keep it in one issue: https://github.com/aspnetboilerplate/aspnetboilerplate-templates/issues/48

Feel free to try this again in SweetAlert 2.0.
