### ISSUE TITLE
CommonJS support

### ISSUE THREAD

**Issue by zalad** [t4t5/sweetalert#105]
What about adding a `package.json` to be installable via `Webpack` or `Browserify` as well?
I could submit a PR.

**Comment by t4t5** [comment]
Added in v0.4.2! Yay!

**Comment by idolizesc** [comment]
Is this still working? When I `require('sweetalert')` I get back an empty object...

**Comment by t4t5** [comment]
Yup, seems like it broke in the beta. Let's fix it!

**Comment by t4t5** [comment]
What setup are you guys using? When I test in Browserify and do `require('sweetalert');` I can run run all the examples without any errors being thrown.

**Comment by idolizesc** [comment]
I'm using Browserify as well, but I end up seeing the following:

```js
var salert = require('sweetalert');
console.log(salert); // outputs: {}
salert('Test'); // Error about not being a function
```

**Comment by jackalopy** [comment]
I have the exactly same issue here.
