### ISSUE TITLE
Loading State

### ISSUE THREAD

**Issue by pemrouz** [t4t5/sweetalert#111]
Would it be possible to add a "loading" state? For example, with the delete example you would likely want to ask for confirmation (type: warning), update the database (type: loading) and then show a confirmation message (type: success/error).

**Comment by IsaiahJTurner** [comment]
Requesting this as well.

**Comment by limonte** [comment]
It seems like this repo is inactive now, I added loading state and some additional features to [sweetalert2](https://github.com/limonte/sweetalert2). See last example with ajax request here https://limonte.github.io/sweetalert2/

**Comment by JFLTM** [comment]
limonte, your sweetalert2 works perfectly for this - but the alert only bounces in on the first use on each page? Is this a bug?

**Comment by JFLTM** [comment]
Limonte, I have fixed this but have no clue how to commit a change on here. Between versions 0.0.3 and 0.0.5 of sweetalert2 you changed the naming conventions of some classes from camel case to hyphen spaced but in both the js and css files did not change some instances of showSweetAlert and hideSweetAlert to the new format. Rectifying this fixes the bug. Hope this helps.

Thank you for your additions to sweet alert, and thank Tristan Edwards very much for the original library!

**Comment by babeuloula** [comment]
+1 for loading state, but it's possible to have something like this : https://raw.githubusercontent.com/pedant/sweet-alert-dialog/master/play_progress.gif

**Comment by chriscct7** [comment]
@babeuloula that's the Android fork. It's not possible on the JS version

**Comment by babeuloula** [comment]
Yes i know, but for an AJAX request, it's possible no ?

**Comment by chriscct7** [comment]
I'm not sure what you mean. That action and the assets are not available in the JS version. They are the android fork only. The ticket here is to add the functionality from the Android fork to the JS version

**Comment by babeuloula** [comment]
Yes I know, and I think, it's very intresting to implement this foncitonality from the Android fork on the JS version

**Comment by daybaryour** [comment]
Well i have this little snippet that works for me. it's a little hack but looks beautiful all the same.
$(document).on("click", "blah blah", function() {
    swal({title:"", text:"Loading", imageUrl: link/to/your/url", showConfirmButton:false,      allowOutsideClick:false});
    $.ajax({url:url, type:'POST', data:data,success:function() {
         swal.close(); //or whatever you want to implement here
    } 
}

i hope someone finds it useful. cheers

**Comment by HelloCui** [comment]
Loading is needed. Ajax request need time, at this time some user actions should be prevented. Like: click delete button twice. It will be awesome if I can custom the buttons like [ladda](http://lab.hakim.se/ladda/).

**Comment by debian-sh** [comment]
+1

**Comment by ChadTaljaardt** [comment]
+1

**Comment by atorscho** [comment]
+1

**Comment by UnifiedInc** [comment]
-1

**Comment by s9xie** [comment]
+1

**Comment by SparK-Cruz** [comment]
What about "showLoaderOnConfirm"? (that doesn't work with custom button text) It is minimalist but fits.

**Comment by seanlindo** [comment]
+1

It's too specific, but Ladda would work lovely.

**Comment by t4t5** [comment]
In the new SweetAlert 2.0, setting `closeModal: false` in the [button object](https://sweetalert.js.org/docs/#button) will automatically show a spinner on the button when it's clicked.

For other types of spinners, you can use the new [content option](https://sweetalert.js.org/docs/#content) and build it yourself! :)
