### ISSUE TITLE
Create Chrome Extention to replace native?

### ISSUE THREAD

**Issue by Martinspire** [t4t5/sweetalert#118]
Is it possible to create a Chrome Extention to really override the native popup to be this awesome instead?

I like this styling and i hope one day browsers will show alerts like this (i'm still not sure why alerts look like the ones from 2004), but perhaps we can force it?

**Comment by t4t5** [comment]
I'm closing this for now. If @kodypeterson or someone else releases something, I'll add it to "Related projects", but it's not on the current SweetAlert roadmap.
