### ISSUE TITLE
Publish to CDNs (jsdelivr/cdnjs/etc.)

### ISSUE THREAD

**Issue by pilwon** [t4t5/sweetalert#122]
It'd be great to publish this library to CDNs:
* http://www.jsdelivr.com/
* https://cdnjs.com/
* ...

**Comment by t4t5** [comment]
Boom! Not the latest version yet (v0.5.0), but it will probably be there soon!

http://www.jsdelivr.com/#!sweetalert
https://cdnjs.com/libraries/sweetalert
