### ISSUE TITLE
[ESC] Key Does Not Close Alert

### ISSUE THREAD

**Issue by Solidwhite** [t4t5/sweetalert#131]
When I open a standard alert I expect to be able to close it with a press of the [ESC] key. The demo located here: http://tristanedwards.me/sweetalert, does not include that functionality.

**Comment by limonte** [comment]
It seems like this repo is inactive now, I fixed this and added some additional features to [sweetalert2](https://github.com/limonte/sweetalert2).

**Comment by jack126guy** [comment]
This issue has been fixed, as noted in # 132.
