### ISSUE TITLE
Set initial focus to Cancel button if there is one

### ISSUE THREAD

**Issue by jack126guy** [t4t5/sweetalert#133]
I understand that focus is set on the OK/Confirm button because sometimes there is only that button. But for actual Confirm/Cancel messages, wouldn't it be "safer" to set the initial focus on the Cancel button? I assume that, if something needs confirmation, it shouldn't be subject to an accidental Enter keystroke.

**Comment by t4t5** [comment]
The default behaviour I've seen is that the focus in on the action-button, not the cancel button. I'm considering making this optional though.

**Comment by sweco-semmod** [comment]
What is status on setting focus on cancel instead of action?

**Comment by emilv** [comment]
@sweco-semmod Sweetalert2 at https://github.com/limonte/sweetalert2 have an option to focus cancel.
