### ISSUE TITLE
Internet Explorer Browser Test

### ISSUE THREAD

**Issue by ImBobby** [t4t5/sweetalert#144]
Sweet Alert is not working is these browsers
* **IE8** (Windows XP)
* **IE9** (Windows 7)
* **IE10** (Windows 7)

These browsers fail in [line 170](https://github.com/t4t5/sweetalert/blob/master/lib/sweet-alert.js#L170)

![ie9](https://cloud.githubusercontent.com/assets/2084193/4695556/6330f1aa-5832-11e4-8bbb-a9c8984da22a.png)
![screen shot 2014-10-20 at 8 27 20 am](https://cloud.githubusercontent.com/assets/2084193/4695569/f321638a-5832-11e4-8076-9652f5d36bef.png)

**Comment by t4t5** [comment]
This has been fixed.
