### ISSUE TITLE
Vertical center fails if alert buttons are not in same line

### ISSUE THREAD

**Issue by fidoboy** [t4t5/sweetalert#145]
On mobile devices for example, if the buttons width does not allow to show them on the same line, the function to calculate the top margin fails and the returned offset (topMargin) is wrong, resulting in a modal not being vertically centered.

**Comment by voodoo6** [comment]
I'm noticing the same issue testing on iPhone 5 screen size – if 'text' has content (eg. over 6-7 lines) the modal doesn't centre on the screen and the action buttons are un-clickable and can't be scrolled into view)

**Comment by esetnik** [comment]
same issue

**Comment by t4t5** [comment]
Centering is fixed in SweetAlert 2.0
