### ISSUE TITLE
TypeError: Cannot read property 'querySelector' of null

### ISSUE THREAD

**Issue by slneufeld** [t4t5/sweetalert#147]
I get the following error in Google Chrome 38 on Win7. Sweetalert works fine, and then I navigate to another page. I then click the back button, and try to call swal again. Here is the message:

TypeError: Cannot read property 'querySelector' of null {stack: (...), message: "Cannot read property 'querySelector' of null"}message: "Cannot read property 'querySelector' of null"stack: (...)get stack: function () { [native code] }set stack: function () { [native code] }__proto__: Error index.js:113

Repeatable 100% of the time. Sweetalert is loaded before jquery.

**Comment by t4t5** [comment]
This should now be fixed.
