### ISSUE TITLE
Confirm accepts when you hit enter instead of canceling

### ISSUE THREAD

**Issue by design1online** [t4t5/sweetalert#151]
Your examples of a confirm dialog box automatically hit the "ok" button if you hit enter instead of canceling the confirmation.

**Comment by t4t5** [comment]
Yes, I prefer the focus to be on the action button rather than the cancel button by default. If a lot more people disagree we can reopen this.

**Comment by ceejayoz** [comment]
@t4t5 I'd like to see this configurable. I use the tool to prompt with "are you sure?" on dangerous actions, so being able to explicitly require a click would be beneficial.

**Comment by design1online** [comment]
@ceejayoz I just modified it to cancel when you hit the enter button.

**Comment by wagneramaral** [comment]
@design1online how did modify it?

**Comment by design1online** [comment]
@wagneramaral sorry it was a long time ago and I ended up going with [Toastr](https://github.com/CodeSeven/toastr) instead since it had more flexibility and could do multiple messages at the same time. Basically the idea is that you don't fire the cancel handler when the keycode is the enter key.

`var onButtonEvent = function onButtonEvent(e) {
    if (e.keyCode != 13) {
      return _handleButton$handleConfirm$handleCancel.handleButton(e, params, modal);
    }
  };`
