### ISSUE TITLE
Auto close timer doesnt work on example website

### ISSUE THREAD

**Issue by mkoczka** [t4t5/sweetalert#152]
Hey,

[sweetalert website](http://tristanedwards.me/sweetalert) is missing initialization code for Auto close timer feature.
```
document.querySelector('ul.examples li.timer button').onclick = function(){
	swal({
		title: "Auto close alert!",
		text: "I will close in 2 seconds.",
		timer: 2000
	});
};
```

It's commited in master branch example [here](https://github.com/t4t5/sweetalert/blob/master/example/index.html), but not on live website.

**Comment by t4t5** [comment]
I'm late to the party, but I'm closing! :)
