### ISSUE TITLE
On Page Load

### ISSUE THREAD

**Issue by quma** [t4t5/sweetalert#156]
Hallo,

thanks for this great extension.
I have a question ... how I can start a Modal window on Page Load without clicking any button or link ?

thx

**Comment by t4t5** [comment]
The jQuery conflict should be fixed.

**Comment by waiylgeek** [comment]
I think this may help:

```  
<script>
      $(window).load(function(){
        swal("Good job!", "You clicked the button!", "success");
      });
  </script>
```

**Comment by bitcubico** [comment]
Gracias, el último me funcionó

**Comment by ahkjxy** [comment]
yea, a good idea.

**Comment by eslam-elameen** [comment]
how to use sweetalert with vanilla js in a separate js file!

**Comment by sailonthrough** [comment]
Your email is received and will be handled  as soon as possible,and this is an automatic reply,I will respond to your message  immediately when I see it.Thank you.
