### ISSUE TITLE
Button color should be optional

### ISSUE THREAD

**Issue by notreadbyhumans** [t4t5/sweetalert#166]
Passing a null into confirmButtonColor should override the functionality that adds the in-line styles i.e. explicitly passing in a null (or some other value) disables this functionality, rather than causes to revert to the defaults.

At the moment the inline styles will always override the style sheet, causing an issue when the button color is not known in advance e.g. user configurable theming.

**Comment by t4t5** [comment]
This is fixed in v0.5.0 by padding the argument ```confirmButtonColor: false``` (better late than never, eh?)
