### ISSUE TITLE
Go to link on click OK

### ISSUE THREAD

**Issue by voodoo6** [t4t5/sweetalert#168]
Forgive my inexperience. How can I achieve this:

I'd like sweetalert to show a message when a user clicks a link, but then to only go to the link _if_ the user selects 'OK' in the sweetalert dialog.

Thanks!

**Comment by alitnk** [comment]
hi and thank you for the example,
i wanna link the button to a laravel route
like this (i know it's wrong and this isn't blade...)
```
function(){
                window.location.href = "{{ route('panel.posts.remove') }}";
            });

```
and i passed $post data to the view...

**Comment by mojtabaRKS** [comment]
it's not working! 
------------------------------------------------------------------------------
Uncaught SweetAlert: Unexpected 2nd argument (function(){
 window.location.href = mainURL;
 });
------------------------------------------
what should i do?
