### ISSUE TITLE
MouseEvent can be an empty object

### ISSUE THREAD

**Issue by JesperKrejbergPetersen** [t4t5/sweetalert#169]
MouseEvent can be an empty object in the "fireClick" function. 
I experienced this when only using the keyboard to trigger the open and close. On the second open, it failed.

It can be fixed by replacing 
      if ( MouseEvent ) {
with
      if ( MouseEvent && !isObjectEmpty( MouseEvent ) ) {

and adding this function 

    /*
     * Check if an object has any properties
     */
    function isObjectEmpty( obj ) {
        for ( var prop in obj ) {
            if ( obj.hasOwnProperty( prop ) )
                return false;
        }
        return true;
    }

**Comment by limonte** [comment]
@JesperKrejbergPetersen it seems like this repo is inactive now, I fixed this and added some additional features to [sweetalert2](https://github.com/limonte/sweetalert2), https://github.com/limonte/sweetalert2/commit/d8b619675aed6c258de7b8e651bb2c72f93c5f43

**Comment by t4t5** [comment]
Fixed in 0.4.1.
