### ISSUE TITLE
Change the icon classes

### ISSUE THREAD

**Issue by zacksmash** [t4t5/sweetalert#174]
I need to append the icon classes with something like .saerror, .sasuccess, etc. The current ones are conflicting with some css that's already using .error and .success. How can I do this?

Edit: Everything I've tried thus far gets this error 
`Unhandled Exception: TypeError: null is not an object (evaluating 'elems.length')`

**Comment by sushantdhiman** [comment]
I have made a PR request [here](https://github.com/t4t5/sweetalert/pull/278) that should solve conflicting icons classes issue.

**Comment by t4t5** [comment]
Fixed in v0.4.2. Thanks @sushantdhiman!

**Comment by zacksmash** [comment]
Awesome! Thanks, all!

**Comment by sushantdhiman** [comment]
:satisfied:, great plugin always love to support it.
