### ISSUE TITLE
Add showConfirmButton option

### ISSUE THREAD

**Issue by sylouuu** [t4t5/sweetalert#177]
Hi,

As this is now possible to add a timer, it could be perfect to support `showConfirmButton: false`.

Bests

**Comment by limonte** [comment]
@sylouuu seems like this repo is inactive now, I added this option and some additional features to [sweetalert2](https://github.com/limonte/sweetalert2).

**Comment by t4t5** [comment]
Finally added in v0.4.2. Thanks for the suggestion!
