### ISSUE TITLE
[EXPIRED] Popup flickering when using keyboard

### ISSUE THREAD

**Issue by sergeevabc** [t4t5/sweetalert#178]
Dear Tristan, 
steps to reproduce:
0. Browsers: latest Chromium and Firefox.
1. Open http://jsbin.com/cajugiluqe/1/
2. Type 123
3. Press Enter
4. Close popup by pressing Enter again
5. Focus goes to input field, so press Enter one more time
6. Popup is expected, however either flickering happens or nothing at all.

Could you be so kind and fix it asap?

**Comment by sergeevabc** [comment]
@camelCaseD, have you updated the repository with that fix?

**Comment by camelCaseD** [comment]
@sergeevabc I cannot confirm based on the project I was using this for, because it is inactive and not maintained.

**Comment by sergeevabc** [comment]
By the way, @t4t5, the author of Sweetalert, has been active on Twitter all these years. And neglected us.
