### ISSUE TITLE
Attach callback to OK button before showing alert

### ISSUE THREAD

**Issue by paolodona** [t4t5/sweetalert#182]
First of all, thanks for the great library!
I'm using sweetAlert as a replacement for js confirm() function.
All works fine in production but my selenium tests fail because the callback function on clicking "OK" does not get called.

I've noticed this is due to selenium clicking "OK" before the sweetalert animation completes.
If I add a sleep() before clicking "OK" all works fine.

It would be handy to bind the callback to the "OK" / "CANCEL" buttons before showing the animation, so that no sleep is required if you need to automate tests of applications using sweetAlert

**Comment by t4t5** [comment]
Sorry for the late response, but in SweetAlert 2.0, there should no longer be a delay for for when the event listeners get attached to the buttons!
