### ISSUE TITLE
Remove default HTML injection in WP

### ISSUE THREAD

**Issue by colir** [t4t5/sweetalert#187]
Hi,
i use Sweet Alert, and it work pretty well.
However, i've a probleme.

I use it on a Wordpress projet, and when i'm on the login form to acces the administration of WP, i see the injected html no styled, because wp didnt load theme css on this view.

How i can remove it ?

thanks a lot

**Comment by t4t5** [comment]
Shouldn't the question rather be why the CSS-file wasn't loaded?

**Comment by colir** [comment]
by default wordpress login page dosn't load theme css (where i put sweet alert style).
However i had a login page check before loading sweetalert (is_login_page)
thanks
