### ISSUE TITLE
Cannot select text inside alert

### ISSUE THREAD

**Issue by antoniobrandao** [t4t5/sweetalert#192]
Using the latest version, I cannot create a text selection of the "p" element of the alert (just after the h2) using the mouse.

I tried adding this CSS to the element but it doesn't sem to work:

    -webkit-user-select all
    -moz-user-select all
    -ms-user-select all
    -o-user-select all
    user-select all

**Comment by limonte** [comment]
It seems like this repo is inactive now, I fixed this and added some additional features to [sweetalert2](https://github.com/limonte/sweetalert2).

**Comment by antoniobrandao** [comment]
@limonte good job mate, will check it out

**Comment by t4t5** [comment]
This is fixed!
