### ISSUE TITLE
scroller 

### ISSUE THREAD

**Issue by vic1403** [t4t5/sweetalert#195]
how to add a vertical scroller in the message.
Any ideas?

**Comment by Jordan4jc** [comment]
Any updates on this? I tried adding `overflow:scroll` to the `.sweet-alert` and it works but when the alert opens it's scrolled to the bottom of the alert, and I can't seem to get it to scroll to the top of the alert before is opens.

**Comment by esecules** [comment]
looks like my PR never made it in, but the way it should work is the scrollbox will be created if the inner text's height is greater than the threshold. 

if you look in my branch (PR #208) I also added a usage example to the readme. 

It might also be the case that the feature was added by someone else and this ticket was never closed.

**Comment by esecules** [comment]
#209. my bad

**Comment by t4t5** [comment]
In SweetAlert 2.0, you can scroll down the modal if it's too long. Closing.
