### ISSUE TITLE
when i click ok button of sweet alert.. send to another page

### ISSUE THREAD

**Issue by fabianchoxD** [t4t5/sweetalert#199]
i need go to another page after click  at ok or error button...my code:

i use a $(document) because i need show the error when the page is loaded

 <script>
        $(document).ready(function () {
    swal({ title: "Error", text: "wrong user or password", type: "error" });
});
    </script>

pls give me a hand ;)

**Comment by Jpsstack** [comment]
@fabianchoxD  Good Job !

**Comment by sunilsmith** [comment]
I need to bind a html page within sweet alert. so that when my sweet alert triggered it should show the html page in its body.

**Comment by manso92** [comment]
But if i like to use a cusomize url that is on a var?

Example:

`function(event) {

            swal({
                title: event.title,
                text: "<p>" + event.description + "</p><a href=\"" + event.link + "\" target='_blank'>enlace</a>",
                html: true,
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Ir al enlace",
                cancelButtonText: "Cerrar",
                closeOnConfirm: false,
                closeOnCancel: false
            },
            function(isConfirm) {
                if (isConfirm) {
                    window.open(event.link,'_blank');
                    swal.close();
                } else {
                    swal.close();
                }
            }
            );`


But that function cant read event var

**Comment by prajesh2u** [comment]
how can i do the alert when user is trying to close  browser/tab with SweetAlert? Please help me out..

**Comment by MAbdulHalim** [comment]
@fabianchoxD thanks, it works.

**Comment by yogesh-mistry** [comment]
anyone have any idea about the callback function/event triggered on click of OK button genereated using persistant() function?
`Alert::success('Success Message', 'Optional Title')->persistent("Ok");`

**Comment by cnchg** [comment]
@fabianchoxD  thank you for the solution but it did not work for me. I was able to resolve this issue like this:
`swal({
          title: "Success!", 
          text: response.scriptstatus, 
          type: "success"
}).then(function() {
      // Redirect the user
       window.location.href = "new_url.html";
       console.log('The Ok Button was clicked.');
 });`

**Comment by koolbseit** [comment]
@cnchg many thanks, it's work for me!!!

**Comment by Grafluxe** [comment]
If you also have a "Cancel" button in your modal, you'll want to confirm that the "OK" button was indeed pressed:

```
swal({...}).then(okay => {
  if (okay) {
    window.location.href = "...";
  }
});
```

**Comment by jmada** [comment]
```
swal({
   icon: "error",
  title: "¡Error!",
  showConfirmButton: true,
  confirmButtonText: "Cerrar",
  closeOnConfirm: false
}). then(function(result){
  window.location = "WEREYOUWANTTOGO";
             })
```

This is my solution for this issue!

**Comment by alitnk** [comment]
hi and thank you for the example,
i wanna link the button to a laravel route
like this (i know it's wrong and this isn't blade...)

function(){
                window.location.href = "{{ route('panel.posts.remove') }}";
            });

and i passed $post data to the view...

**Comment by zoom699** [comment]
function MesajUyari($mesaj,$text,$icon,$sure,$url){
 echo"<script >
	swal({
			title:\"$mesaj\", 
			text:'$text',
			icon:'$icon',
			button:'Kapat'
	});	
</script> ";
header("Refresh: $sure; url=$url");
//location.href = 'http://www.alokatalog.com/'
//$gidecekSiteAdres=  header('location:'.$_SERVER['HTTP_REFERER']);
}
			MesajUyari("Proje Oluşturma Başarılı","Yönlendiriliyorsunuz<br>Lütfen Bekleyin","success",3,"Sayfa.php");/

**Comment by dinukakulatunga** [comment]
> @fabianchoxD thank you for the solution but it did not work for me. I was able to resolve this issue like this:
> swal({
> title: "Success!",
> text: response.scriptstatus,
> type: "success"
> }).then(function() {
> // Redirect the user
> window.location.href = "new_url.html";
> console.log('The Ok Button was clicked.');
> });

Thanks!! It worked!!

**Comment by sbalasa** [comment]
Mine is redirecting to the page directly without even showing the Alert message. Am using Chrome.
`        swal({
                title: "App",
                text: "Error: Invalid Credentials, try again !",
                icon: "error",
                closeOnConfirm: false
        }).then(
                function () {
                        window.location.href = 'index.html';
                }
        );`

**Comment by yvaneee** [comment]
Hi, I'm trying to make swal disappear after 5 seconds so I put a `timer: 5000` but when the timer is done, even if the user didn't click the button, it goes to another page. I want to the user to stay on the page if he didn't click the button on swal. Here's my code:

`                            Swal.fire({
                                html: "Your tip has been published.",
                                icon: 'warning',
                                showCancelButton: false,
                                confirmButtonText: "See tip",
                                timer: 5000,
                                customClass: {
                                    container: 'custom-alert',
                                    popup: 'published-tip',
                                    actions: 'actions-btn'
                                },
                            }).then(function() {
                                window.location = "/" + data.username;
                            });`

**Comment by malikbakacak** [comment]
Swal.fire({
                text: "Here's a basic example of SweetAlert!",
                icon: "question",
                buttonsStyling: false,
                showCancelButton: true,
                allowEnterKey: false,
                confirmButtonText: "Ok, got it!",
                cancelButtonText: 'Nope, cancel it',
                customClass: {
                    confirmButton: "btn btn-primary",
                    cancelButton: 'btn btn-danger'
                }
            }).then(({ isConfirmed }) => { alert(isConfirmed); });
