### ISSUE TITLE
[Feature] Close Event

### ISSUE THREAD

**Issue by aliemre** [t4t5/sweetalert#200]
How to close sweet alert without clicking confirm button? Is there available close event or am I missing?
e.g.:
``` 
swal('hide');
swal('close');
```

**Comment by aly006** [comment]
would like to hop on this, and ask if there was any way to hide the button itself from the modal?

**Comment by limonte** [comment]
@aly006  I added ``showConfirmButton`` option and some other additional features in [sweetalert2](https://github.com/limonte/sweetalert2).

**Comment by chetankhargone** [comment]
I am using sweetalert,but I am in need to hide the Ok button(button to hide sweetalert). I want that there should be no button in sweetalert,after data is loaded it will hide automatically but no manual button to hide it.

**Comment by IARKI** [comment]
My solution is 

> swal.closeModal();

**Comment by rvanlaak** [comment]
Given the title of this issue is about a "close event", seems SweetAlert cannot trigger an event / do callback if the cancel button is clicked? I'd expect it to be the third parameter, but that doesn't do anything:

```js
swal({
    title: Scribbr.referenceListWarningTitle,
    text: Scribbr.referenceListWarningText,
    type: 'warning',
    showCancelButton: true,
    confirmButtonText: 'ok',
    cancelButtonText: 'cancel' 
, function() {
    $('html, body').animate({
        scrollTop: $("#page-"+page).offset().top - 70
    }, 600);
}, function(e) {
    console.log(e);
});
```
How to do something when the cancel button is clicked?

**Comment by MacgyverMartins** [comment]
Try it: `swal.close();`

**Comment by KalanaPerera** [comment]
@MacgyverMartins thanks : Try it: swal.close(); works

**Comment by ggwebdev** [comment]
By default, it provides the ** closeOnConfirm ** and ** closeOnCancel ** parameters that can be set to true or false. Set to true it will close immediately after the click. If you want to close just after processing the callback function you can use ** swal.close () **

**Comment by utpal-patel** [comment]
Try this:
 $('.sweet-alert').css('display','none');
 $('.sweet-overlay').css('display','none');

**Comment by mdashiff** [comment]
swal.close(); requires an argument to be passed as a string. Error in agularjs typescript
