### ISSUE TITLE
Can you add this to CDNjs?

### ISSUE THREAD

**Issue by simkessy** [t4t5/sweetalert#203]
Hi, 

Would it be possible to add this to cdnjs please?

**Comment by t4t5** [comment]
The library can be found here: https://cdnjs.com/libraries/sweetalert

It's not the latest version yet (v0.5.0), but it will probably be there soon. :)

**Comment by josdejong** [comment]
Thanks for this nice library!

It would be great if the latest verison of sweet-alert could be added to cdnjs (which is still at v0.5.0)
