### ISSUE TITLE
Success icon not round

### ISSUE THREAD

**Issue by elahmo** [t4t5/sweetalert#210]
I have encountered a small styling issue. I am using one of the bootstrap based template, and when I show the sweetalert this is how the success message looks like:
![image](https://cloud.githubusercontent.com/assets/852433/5237532/10d4110c-788b-11e4-9f9d-4a4bf055719c.png)

For some reason, in the template I am using, there is a `border-radius: 0 !important` line for all divs, and that overwrites the sweetalert css.

So, I added  `!important` lines to `sweet-alert.css` on lines  [88](https://github.com/t4t5/sweetalert/blob/master/lib/sweet-alert.css#L88) and  [186](https://github.com/t4t5/sweetalert/blob/master/lib/sweet-alert.css#L186) and this fixes the issue.

**Comment by malcolmocean** [comment]
Honestly I would say that's an issue with your template.

**Comment by t4t5** [comment]
As @malcolmocean said, the template is the problem, they should be more restrictive with their ```important!``` values. :) Glad you found a solution though. Closing.
