### ISSUE TITLE
Cancel callback doesn't work when wrapped in a proxy function

### ISSUE THREAD

**Issue by adambiggs** [t4t5/sweetalert#213]
For example, if you use a CoffeeScript class method as the `doneFunction` callback, and the method has been bound with a fat-arrow, Sweet Alert doesn't call the function as expected...

E.g.:

``` coffee
class MyClass

  confirmSomething: =>
    alertOptions =
      title: 'For Real?'
      showCancelButton: yes
    sweetAlert alertOptions, @doStuff

  doStuff: (confirmed)=>
    # Only called if the user confirms... Not when they click the cancel button.
```

The problem is caused in the logic on line `305`. CoffeeScript has wrapped the method in a proxy function, so when Sweet Alert converts it into a string, it looks like this:

``` js
"function(){returnfn.apply(me,arguments);}"
```

I suggest allowing a separate `cancelled()` callback instead of using the same callback for both confirmed/unconfirmed user flows.

The benefit would be less logic in your code, and IMO a simpler more familiar API for developers (success/fail callbacks are a pretty standard JS pattern).

**Comment by joenorton** [comment]
+1

**Comment by t4t5** [comment]
SweetAlert no longer uses strings to check callback functions (which was an ugly hack). As of 2.0 you can use awesome [promises](https://sweetalert.js.org/guides/#using-promises) instead!
