### ISSUE TITLE
Close with the esc key

### ISSUE THREAD

**Issue by ValentinPoddany** [t4t5/sweetalert#219]
Can you add a cool (and simple) feature for the UX : the window with the escape key ?

**Comment by limonte** [comment]
It seems like this repo is inactive now, I fixed this and added some additional features to [sweetalert2](https://github.com/limonte/sweetalert2).

**Comment by jack126guy** [comment]
This issue has been fixed, as noted in #132.

**Comment by t4t5** [comment]
This has now been added as a feature through ```allowEscapeKey``` (true by default). Thanks for your help guys!

**Comment by anselmobattisti** [comment]
Old but goooood :)
