### ISSUE TITLE
[Suggestion] Create a nuget package so that .NET developers can find it more easily

### ISSUE THREAD

**Issue by maboivin** [t4t5/sweetalert#22]
Hi,
It would be nice if you could create a nuget package and upload it here http://www.nuget.org/packages/upload. Nuget is very popular these days in the .NET world.

Thanks.

**Comment by djm61** [comment]
A bit late, but I've created a nuget package and uploaded it to nuget.org - just waiting for it to be listed.  The ID I had to choose was SweetAlert.Base --> ```Install-Package SweetAlert.Base```

**Comment by masteradhoc** [comment]
Thanks @djm61! @t4t5 This could be closed now. I added a Pullrequest for this to add the Link into Readme (#369)
