### ISSUE TITLE
Callback function

### ISSUE THREAD

**Issue by alexander-code** [t4t5/sweetalert#227]
Hi congrats for your great plugin.

So, here is the story. I got an error "Cannot read property 'querySelector' of null" which I realized that was some known issue and some guys tried to fix it. I found another version of your sweet-alert.js using the following code (I compare them and there are plenty of differences with your original except the following code) .

   *var args = arguments;
    if (getModal() !== null) {
        // If getModal returns values then continue
        modalDependant.apply(this, args);
    } else {
        // If getModal returns null i.e. no matches, then set up a interval event to check the return value until it is not null	
        var modalCheckInterval = setInterval(function() {
          if (getModal() !== null) {
            clearInterval(modalCheckInterval);
            modalDependant.apply(this, args);
          }
      }, 100);
    }*

which actually solve this problem but now the callback functions for example
_closeOnConfirm: false }, **function()**
            { ...}_
doesn't work anymore!

Is there any solution of a js that works fine for everything of the above?

Thanks in advance.

**Comment by t4t5** [comment]
I believe this is fixed now so I'm closing.

**Comment by alexander-code** [comment]
Hello,

How is this fixed now? Did you publish a new version?

**Comment by t4t5** [comment]
Yes, please upgrade to 0.4.0 and try again. If the problem persists, feel free to post here!
