### ISSUE TITLE
Ugly flickering

### ISSUE THREAD

**Issue by scrnjakovic** [t4t5/sweetalert#228]
I get this ugly flickering/painting when I call swal() for the first time since page load.

Firefox 34 for Ubuntu 14.04 x64 with latest Bootstrap included on the page.

**Comment by t4t5** [comment]
I've seen this too, but I'm not sure what causes it. If anyone has an idea and would like to chip in I'd greatly appreciate it!

**Comment by t4t5** [comment]
I'm not sure when or how this was fixed, but it seems like it's not an issue anymore when I test it. :) Closing.
