### ISSUE TITLE
[Feature Request] Create your own action buttons

### ISSUE THREAD

**Issue by marceloboeira** [t4t5/sweetalert#23]

**Comment by t4t5** [comment]
I think this adds unnecessary complexity to the library. I'm looking into letting people template their own modals though and using SweetAlert for calling them.

**Comment by cbfranca** [comment]
Could exist buttons 'Yes No Cancel'. It's very useful.

**Comment by tylerlweb** [comment]
I agree, I have a use case where I need to have "Accept Request" and "Deny Request" buttons, but I also need to let the user get rid of the popup without running the accept/deny function!

**Comment by wweldon** [comment]
I need this as well.  It does not seem to be an at all unreasonable capbility.

**Comment by Charlex** [comment]
Everyone is doing the same hack to do this by using the confirm boolean as a code switch.

It would make life a lot easier not to do this and to just have two additional attributes like "onConfirm" and "onCancel"
