### ISSUE TITLE
Request for HTML partials as params.text

### ISSUE THREAD

**Issue by xgenvn** [t4t5/sweetalert#230]
Currently, swal does not allow to use HTML partial as message string. I think we should have an option to escape the text or not. Maybe swal just focusing too much on the basic alert, not extending the other type of showing the details (e.g: the validation that already formated in html before coming to browser ...) ?
IMO the strict escape HTML on params.text is not really neccessary.

**Comment by limonte** [comment]
@xgenvn @user453584 @jhiver seems like this repo is inactive now, I added this option and some additional features to [sweetalert2](https://github.com/limonte/sweetalert2).

**Comment by t4t5** [comment]
In 0.4.0, you can now set ```html: true``` to pass HTML tags in the text fields.
