### ISSUE TITLE
SwAl doesn't disappear on back navigation

### ISSUE THREAD

**Issue by girishbr** [t4t5/sweetalert#231]
Using SwAl in a Jquery Mobile app running in a cordova shell. It works just great but for one small issue.
SwAl is up and the user presses the back button on his Android app. Everything in the background goes one step back but no SwAl - SwAl just stays there for some reason I am not able to figure out. 

How do I get SwAl to disappear when an user navigates back on his phone?

**Comment by t4t5** [comment]
As the pull request says, just use `swal.close()`

**Comment by MasadAshraf** [comment]
just use this script , its working for me: 
<?php
header("Cache-Control: no-store, no-cache, must-revalidate, max-age=0");
header("Expires: Sat, 26 Jul 1997 05:00:00 GMT");
?>
