### ISSUE TITLE
publish to npm?

### ISSUE THREAD

**Issue by jprichardson** [t4t5/sweetalert#238]
It's a common misconception that npm isn't for front-end code, but that's not the case; the npm website even mentions it now on the front-page :) See: React.js community has embraced npm as a front-end package manager.

Any willingness to do this?

**Comment by danreeves** [comment]
Sweetalert has already been published, here: https://www.npmjs.com/package/sweetalert

However, it's not published by @t4t5 and it's outdated.

**Comment by t4t5** [comment]
I contacted the uploader to get the namespace, so the new version should be there anytime now. :)

**Comment by danreeves** [comment]
Excellent!

**Comment by t4t5** [comment]
Just tried running ```npm install sweetalert``` and everything seems to work well. :) Closing...
