### ISSUE TITLE
swal in swal function() problem

### ISSUE THREAD

**Issue by zimbar** [t4t5/sweetalert#239]
when i call swall in function() of existant swall, it appears but disappears quickly

swal({   title: "Are you sure?",   text: "You will not be able to recover this imaginary file!",   type: "warning",   showCancelButton: true,   confirmButtonColor: "#DD6B55",   confirmButtonText: "Yes, delete it!",   cancelButtonText: "No, cancel plx!",   closeOnConfirm: false,   closeOnCancel: false }, function(isConfirm){   if (isConfirm) {     swal("Deleted!", "Your imaginary file has been deleted.", "success");   } else {     swal("Cancelled", "Your imaginary file is safe :)", "error");   } });

**Comment by t4t5** [comment]
Check out the new [promise API](https://sweetalert.js.org/guides/#using-promises) to make this easier to implement.
