### ISSUE TITLE
clash with jQuery? not sure how to fix

### ISSUE THREAD

**Issue by sicklyman** [t4t5/sweetalert#241]
I'm using jQuery to build a drag and drop activity. I wanted to use sweet alert to give users feedback on this, but it seems that the counter I use to increment correct drops is disabled when I load sweet-alert.js (minimsed or not).

It doesn't matter where in my file I load sweet alert it always disables the code that checks the drop action. 

I've read on here (#56): 

> the function is split to two swal and modalDependant

> call getModal to see if it returns null or not, if it does return null then
> start an interval with 100ms and check if it returns null until it does not return null and then call
> the modalDependant() function, previously swal

but I have no idea what this means and how to apply it. Can anyone help me solve this?

**Comment by t4t5** [comment]
I'm pretty sure this is fixed, so I'm closing!
