### ISSUE TITLE
Auto refrest of page after some time when confirmButtonText is not clicked.

### ISSUE THREAD

**Issue by usamamashkoor** [t4t5/sweetalert#242]
I want to refresh my page when some one click on confirmation button(OK) it is working but i also want to refresh my page when confirmation button is not click for 3 seconds but it is not working.Please help i need urgent help...

Here is my code

swal({
	   title: "Alert",
	   text: "Voucher is saved Successfully.",
	   timer: 3000,
	  confirmButtonText: "Ok!",	
	},
	function(isConfirm){
		  if (isConfirm) {
	  		window.location.reload();
		  } else  { 
			window.location.reload();
		 }
	});
It is not going to else condition.

**Comment by t4t5** [comment]
This is not something that's built into sweetAlert, but if I understand you correctly, it could be done like this:

```javascript
function saveVoucher() {
  swal({
    title: "Alert",
    text: "Voucher is saved Successfully.",
    timer: 3000,
    confirmButtonText: "Ok!", 
  }, function(){
    window.location.reload();
  });
  setTimeout(function() {
    window.location.reload();
  }, 3000);
}

// call the function
saveVoucher();
```

**Comment by usamamashkoor** [comment]
Thnx bro..
