### ISSUE TITLE
Provide context to callback

### ISSUE THREAD

**Issue by PommeVerte** [t4t5/sweetalert#246]
Is there any easy way to provide context to a callback? I need to make my callback aware of both the event and the current element being clicked on...
I must be missing something.

Thanks

**Comment by PommeVerte** [comment]
Answering my own question here. Using `$.proxy()` to assign `this` as the context for the anon function works.

```javascript
swal({/**options**/}, $.proxy(function(){}, this));
```

**Comment by Rvanlaak** [comment]
Think this should be re-opened, because providing context to the events is really necessary when you want to do something that is a bit more complex than showing a alert.
