### ISSUE TITLE
Add cancelButtonColor option

### ISSUE THREAD

**Issue by danilo-valente** [t4t5/sweetalert#249]
It would be nice to have a `cancelButtonColor` option, similar to `confirmButtonColor`.

**Comment by limonte** [comment]
@danilo-valente seems like this repo is inactive now, I added this option and some additional features to [sweetalert2](https://github.com/limonte/sweetalert2).

**Comment by danilo-valente** [comment]
@limonte Nice! Thanks for the quick reply. I'll check it out.

**Comment by TranquilMarmot** [comment]
Looks like there was a pull request for this already but it was closed https://github.com/t4t5/sweetalert/pull/113

**Comment by parterburn** [comment]
You can already accomplish this...see https://github.com/t4t5/sweetalert/pull/113#issuecomment-83681047

**Comment by danilo-valente** [comment]
@parterburn @TranquilMarmot Thanks, I'm going to close this one then.
