### ISSUE TITLE
MouseEvent IE11

### ISSUE THREAD

**Issue by adi-ads** [t4t5/sweetalert#251]
'Esc' doesn't work with cancel option in IE11 as its passing the if(MouseEvents) statement but failing thereafter.

**Comment by limonte** [comment]
@adi-ads seems like this repo is inactive now, I fixed this and added some additional features to [sweetalert2](https://github.com/limonte/sweetalert2).

**Comment by adi-ads** [comment]
@limonte both repository have the same code for MouseEvents (pasting the code below)

if (MouseEvent) {
        // Up-to-date approach
        var mevt = new MouseEvent('click', {
          view: window,
          bubbles: false,
          cancelable: true
        });
        node.dispatchEvent(mevt);
      } 

So your code would have the same error for this specific case as well.

**Comment by limonte** [comment]
@adi-ads thank you again! Fixed now in [sweetalert2](https://github.com/limonte/sweetalert2), https://github.com/limonte/sweetalert2/commit/d8b619675aed6c258de7b8e651bb2c72f93c5f43

**Comment by adi-ads** [comment]
brilliant!

It might be worth to have a chat with @t4t5 to get you added as a repository maintainer moving forward and merging the versions together as well.

**Comment by Turqueso** [comment]
I agree with @adi-ads !
