### ISSUE TITLE
Add an input text comment when confirming an action

### ISSUE THREAD

**Issue by kzelda** [t4t5/sweetalert#252]
Hi , I want to add an input text in the confirm message like this 
http://i.imgur.com/ScqBmGo.png

**Comment by Braunson** [comment]
:+1:

**Comment by sabas** [comment]
Would be cool, perhaps passing the content as an argument to the confirm function.

**Comment by t4t5** [comment]
This is now available in v0.5.0!

**Comment by kzelda** [comment]
Thx
