### ISSUE TITLE
[Feature Request] It would be great if we could add HTML inside the modal

### ISSUE THREAD

**Issue by alexsutu** [t4t5/sweetalert#255]
Sometimes we need to add maybe a link in the modal so it would be great to have a special option to enable html.

**Comment by pomartel** [comment]
https://github.com/t4t5/sweetalert/search?q=html&type=Issues&utf8=%E2%9C%93

**Comment by t4t5** [comment]
This is now possible in 0.4.0. Thanks for your suggestion!
