### ISSUE TITLE
Promise-based API?

### ISSUE THREAD

**Issue by peterjosling** [t4t5/sweetalert#261]
How do other people feel about switching (or just adding) an ES6 Promise-based API? I'm gradually switching all of my new/existing code to use Promises instead of – would be nice if this could do the same. The existing callback-based API wouldn't necessarily have to be removed – we could always just return a thennable object from the `swal` and call inline callbacks as usual.

**Comment by t4t5** [comment]
Yes, that would be pretty awesome. I'm all for having it added!

**Comment by alexbowers-tecmark** [comment]
I think adding it onto the existing API is more beneficial, for those that don't want to use promises

**Comment by EgoAleSum** [comment]
:+1 for promises support. I saw a closed PR #3 for that

**Comment by altmind** [comment]
+1 for returning promises

**Comment by hxlniada** [comment]
+1

**Comment by RobertHerhold** [comment]
+1

**Comment by dandart** [comment]
Completely. swal-forms does this with the swal.withFormAsync() which returns a promise.
If swal or perhaps swal.async were added this would make sense.
I suggest not including an async library and have it work with whatever window.Promise is allowing it to work with native es2015 or a library, and then if this does not exist simply throw an error.

This would work especially well with es2016 which I'm using:

async () => await swal.async({things});

**Comment by alex-shamshurin** [comment]
check this https://limonte.github.io/sweetalert2/

**Comment by dandart** [comment]
Ah excellent - this sounds like the ticket!

**Comment by t4t5** [comment]
Fixed in 2.0! Please check the [upgrade guide](https://sweetalert.js.org/guides/#upgrading-from-1x)

**Comment by limonte** [comment]
> check this https://limonte.github.io/sweetalert2/

this link is outdated, here's the correct one https://sweetalert2.github.io/
