### ISSUE TITLE
Passing params

### ISSUE THREAD

**Issue by chrishill627** [t4t5/sweetalert#264]
Hi Tristan, hope you are well.

I am using swal and would like to pass extra parameters to the function I call on confirmation.

function confirmFileUpload(file) {
            swal({
                title: "You have uploaded " + file.name,
                text: "Use it to add targets to the " + tmpl.data.title + " campaign?",
                showCancelButton: true,
                confirmButtonColor: "#95041e",
                cancelButtonColor: "#343434",
                confirmButtonText: "Confirm",
                cancelButtonText: "Cancel",
                closeOnCancel: false
            }, function (isConfirm, file) {
                if (isConfirm) {
                    parseCsv(file);
                } else {
                    fileInputElement.value = "";
                    App.sendAlert("Cancelled", "Please add a different file", "error");
                }
            });
        }

As you can see I am trying to pass the file into the confirmation function and then forward it on to my parseCsv if the user confirms the file name. I have redefined file from the element in the function as a work around for now but it would make for cleaner code if it was passed as a param, Thanks!

Awesome project, I am using it with Meteor and ionic, always do.

**Comment by t4t5** [comment]
Adding files is not a planned feature in SweetAlert, sorry.

Besides, I don't really see why you would need to pass a "file"-argument to the callback function anyway? You've already defined it in the scope of the function ```confirmFileUpload(file)``` right? So just run ```parseCsv(file)``` directly and it should all be good! (Sorry for the late answer btw)
