### ISSUE TITLE
[request] Add attribute to set custom icon with icon font

### ISSUE THREAD

**Issue by jaoued** [t4t5/sweetalert#265]
Hi,

It could be great if we have possibility to set an icon font (like FontAwesome).

Regards

**Comment by t4t5** [comment]
I'm not planning on a feature for this specifically. What you could do though is add a special class to your modal using ```customClass``` and then style it from there with CSS so that it has the right position!

**Comment by agiratech-vigneshm** [comment]
@t4t5 if I'm willing to give a try and submit a PR will you accept it? Is it either you don't have this as priority or you have any other concerns with this feature?

**Comment by t4t5** [comment]
@agiratech-vigneshm I just don't think this library should try to add too many features that aren't directly related to alerts/modals. There are many ways to render icons on the web, and as long as these aren't too difficult to integrate with SweetAlert, I don't really see a reason to bloat the library.

**Comment by GreenBayRules** [comment]
@t4t5 Hey, so I'm using sweetalert for a authentication system kind of thing, and I have one input as email. It would be helpful to have like a mail icon to make the modal look better. I think that authentication icons (such as mail, password - maybe a key, and phonenumber) is directly related to alerts/modals.
