### ISSUE TITLE
option to remove the OK/confirm button

### ISSUE THREAD

**Issue by Pczek** [t4t5/sweetalert#269]
I'am using sweetalert in my current project and make use of the 'timer' option to provide a quick visual feedback to the user that his keyboard shortcut worked.
It works great but the confirm button is obsolete due to the short timer.
As far as I checked there is no option to remove the button.

How about an option which is consistent with the 'showCancelButton' option -> 'showConfirmButton' which is by default true.

**Comment by chmontgomery** [comment]
:+1:

**Comment by t4t5** [comment]
I was skeptical of this feature at first, but you guys have convinced me. :) Added in v.0.4.2!

**Comment by makhnovskiy** [comment]
Thanks for the functionality!
