### ISSUE TITLE
No link to a page

### ISSUE THREAD

**Issue by Nibler9000** [t4t5/sweetalert#270]
Is it possible to make a link to a page after conforming the action?

**Comment by t4t5** [comment]
````
swal({
        title: "Search Google?",
        text: "By clicking 'OK', you will be redirected to Google!",
        showCancelButton: true,
    }, function(clickedOk) {
        if (clickedOk) {
            window.location.href = "https://www.google.com/?q=sweet+alert+is+awesome";
        }
    });
```

**Comment by Nibler9000** [comment]
And is it also possible to put that a warning message?

**Comment by Nibler9000** [comment]
<script type="text/javascript">// <![CDATA[
function myFunction() {
sweetAlert({
        title: "Search Google?",
        text: "By clicking 'OK', you will be redirected to Google!",
        type: "warning",
        showCancelButton: true,
    }, function(clickedOk) {
        if (clickedOk) {
            window.location.href = "https://www.google.com/?q=sweet+alert+is+awesome";
        }
    });
}
// ]]></script>

for waring ;)

**Comment by Nibler9000** [comment]
Already fixed it thanks
