### ISSUE TITLE
imageSize still broken - old version of sweet-alert.js is being loaded

### ISSUE THREAD

**Issue by jbrozena22** [t4t5/sweetalert#274]
I was noticing that using the imageSize parameter appeared to still be broken when I call the following:

swal({   title: "Sweet!",   text: "Here's a custom image.",   imageUrl: "images/thumbs-up.jpg" , imageSize: "80x80"});
[RETURNED] Undefined at SweetAlert.js:557

That led me to dig and determine that this bug was fixed in the latest release. Therefore I tried emptying my cache several different ways (empty cache and hard reload, clear cache from browser history, reset firefox, etc) and reloading the page. No matter what, it still appears to be loading the old version of the javascript. 

If I look at the html for the example page located here http://tristanedwards.me/sweetalert I see this on line 14:  <script src="/u/SweetAlert/lib/sweet-alert.js"></script>

If I go to that link http://tristanedwards.me/u/SweetAlert/lib/sweet-alert.js you can see that it is the old version of the javascript (check out line 557 and you still see the broken code for imageSize).

Not sure how, but this old version is getting sucked into a meteor package that I am relying on so that too is breaking when I use imageSize.

To replicate:
go to: http://tristanedwards.me/sweetalert
Open javascript console
Enter: swal({   title: "Sweet!",   text: "Here's a custom image.",   imageUrl: "images/thumbs-up.jpg" , imageSize: "80x80"});

Expected response: show sweet alert
Actual response: javascript error

**Comment by t4t5** [comment]
The version on tristanedwards.me is not always up to date, so I wouldn't rely on it as a CDN. :) It's been updated to the latest version (v0.5.0) now though! Thanks for reporting.
