### ISSUE TITLE
HTML Option Undocumented

### ISSUE THREAD

**Issue by posgarou** [t4t5/sweetalert#276]
Inside the source code there is an `html` option (and my testing shows that it works just fine), but I do not believe that this option is mentioned anywhere in the docs.

**Comment by lorensr** [comment]
Oh awesome, I was about to put in a FR for that.

**Comment by posgarou** [comment]
Yeah, it's pretty handy!  :+1:

**Comment by t4t5** [comment]
Fixed!

**Comment by posgarou** [comment]
Great, thanks!
