### ISSUE TITLE
bug when using IE11

### ISSUE THREAD

**Issue by foxpcteam** [t4t5/sweetalert#279]
Hi,
i have bug when using IE11
when you click on the button the alert appears for sec and closed right away
you can test in youe demo site. thats the bug i have.

Thanks

**Comment by foxpcteam** [comment]
when this bug will be fixed?

**Comment by alvipeo** [comment]
The bug is annoying!!!

**Comment by t4t5** [comment]
I cannot reproduce this. Is the issue still there?

**Comment by alvipeo** [comment]
No, it works like a charm now!

**Comment by t4t5** [comment]
Great!
