### ISSUE TITLE
Delay Before Submit

### ISSUE THREAD

**Issue by dannesh** [t4t5/sweetalert#283]
Am using sweetalert to submit delete forms. am using <pre>onSubmit="return validate();"</pre> so when i click on the confirm button, the page dismisses the swal modal before confirm success message shows. is there a way to delay submit to show confirm message before submit
Below is my code.
<pre>
$(document).ready(function(){
$(".deletestudent").click(function(){  
    $("#del_id").val($(this).attr("del_id"));
            swal({
                title: 'Are you sure?',
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#f55753",
                confirmButtonText: "Delete!",
                closeOnConfirm: false 
             }, 
             function(){
                swal("Deleted!", "Your imaginary file has been deleted.", "success");
                $("#delete_stdform").submit();
                            
            });
        })      
});

</pre>

**Comment by t4t5** [comment]
If I understand this correctly, you're not using AJAX to send your form, but rather just redirecting to the submit page?

I guess a simple setTimeout would work in that case.

```javascript
swal("Deleted!", "Your imaginary file has been deleted.", "success");
setTimeout(function() {
  $("#delete_stdform").submit();
}, 1000); // 1 second delay
```
