### ISSUE TITLE
Inside callback method not working

### ISSUE THREAD

**Issue by DmitrySumaroka** [t4t5/sweetalert#285]
```
     $scope.goBack = function() {
            var options = {
              title: "Careful!",
              text: "You will lose your metrics data",
              type: "warning",
              showCancelButton: true,
              confirmButtonColor: "#DD6B55",
              confirmButtonText: "Go Back Home",
              closeOnConfirm: true,
              closeOnCancel: true,
            };
            // If this is here, it happens!
            // $location.path('/navigation');
            swal(options, function(isConfirm) {

              if (isConfirm) {
                // If this is here, it DOESN'T!!!!!!
                $location.path('/navigation');
              }
            });
          }
```

In the callback is being called, its being hit but the modal does not close and the location.path('/navigation') is not being executed

**Comment by ahamidou** [comment]
as well as the AJAX calll:
```javascript
    swal({ title: "Are you sure?", text: "You will not be able to recover this!", type: "warning", showCancelButton: true, confirmButtonColor: "#DD6B55", confirmButtonText: "Yes, delete it!", cancelButtonText: "No, cancel!", closeOnConfirm: true, closeOnCancel: true }, function (isConfirm) {
        if (isConfirm) {
            swal.close();
           /*This is not working*/
            $.ajax({
                cache: false,
                url: 'URL',
                type: 'POST',
                dataType: 'json',
                data: JSON.stringify({ DATA}),
                contentType: 'application/json; charset=utf-8',
                success: function (done) {
                    if (done) {
                        swal({ title: "Deleted!", text: "Done", type: "success", timer: 2000 });
                    } else {
                        swal({ title: "Error!", text: "Cancelled.", type: "error", timer: 2000 });
                    }
                }
            });
        }
    });
```

**Comment by DmitrySumaroka** [comment]
@andrey-bahrachev That doesn't answer my problem though since I am not calling swal in in the callback so i would disagree my issue is still open.

**Comment by includeleec** [comment]
you must set 'closeOnConfirm' argument to 'false'.
''Set to false if you want the modal to stay open even if the user presses the "Confirm"-button. This is especially useful if the function attached to the "Confirm"-button is another SweetAlert.

**Comment by smartsdesign** [comment]
@includeleec you saved my bacon, thanks

**Comment by thomasphansen** [comment]
@DmitrySumaroka I use a dirty trick that works:
    swal( { /* blablabla... */, closeOnConfirm = false }, function (bIsConfirmed) {
        if (bIsConfirmed) {
            // Here comes the magic...
            window.sweetAlert.close();
            // Then do whatever you want!
        }
    })

Hope it helps! ;)

**Comment by shamoh19** [comment]
Any update on this? Facing same issue

**Comment by t4t5** [comment]
In SweetAlert 2.0, you no longer have to set `closeOnConfirm: false`, just use [promises](https://sweetalert.js.org/guides/#using-promises) :)

**Comment by shams-eldeen1307** [comment]
use that 
if(isConfirm.value==true){
do somthing....
}

**Comment by Muhammad-Atif-Ch** [comment]
Check this code 

https://github.com/Muhammad-Atif-Ch/Delete-Button-Sweet-Alert/blob/fe09e81d13963bdb8c3b358a7f80b9f8c5dccf26/.github/workflows/Delete%20Button%20Sweet%20Alert.php
