### ISSUE TITLE
SweetAlert open callback

### ISSUE THREAD

**Issue by IvoPereira** [t4t5/sweetalert#286]
Hello,

Is there any callback that I could use when SweetAlert is totally opened? I need to use some preloading sutff for SweetAlert content, however I was not able to find a callback to allow me to do this.

Any ideas?

**Comment by Untit1ed** [comment]
+1. We need a way to provide some optional event callbacks to sweetAlert. (`open`, `confirm`, `cancel`, `close`).

**Comment by EgoAleSum** [comment]
:+1: I would need this too

**Comment by KillerSquid** [comment]
It's not the best solution by a long shot but I needed to track something specific on a swal.close event so I unminified the code and added some custom script at line 83 with various returns based on variable values.
One could do the same thing for open, confirm, etc.
Again, not by any means the best solution but no matter how I try I can't get custom events to fire in this.  And for a single task it did the trick for me.
Thanks, Tristan, for the awesome plugin.  If you saw how much I use SweetAlerts you'd be blown away.  
Event callbacks would be a HUGE help, for sure!.

**Comment by sinaa** [comment]
Another :+1: here. This is really essential.

**Comment by mvalim** [comment]
+1 :+1:

**Comment by gustavolira** [comment]
+1

**Comment by andrey-bahrachev** [comment]
Totally support this event callbacks feature request!

**Comment by vinothkumarma** [comment]
waiting for it

**Comment by alvarotrigo** [comment]
+1 Pretty basic.

**Comment by artbels** [comment]
+1

**Comment by limonte** [comment]
[sweetalert2](https://github.com/limonte/sweetalert2) now supports open and close callbacks (`onOpen` and `onClose` parameters)

**Comment by ilkeryilmaz** [comment]
+1 waiting for it

**Comment by t4t5** [comment]
SweetAlert 2.0 now opens in a very synchronous way so you should be able to add stuff right after it quite easily.

```javascript
swal("Hello world!");
// The modal is now open
```

Please check out the [upgrade guide](https://sweetalert.js.org/guides/#upgrading-from-1x) and reopen this issue if there's a special use case that I've missed.

**Comment by noveweb** [comment]
How can i call onOpen using promises?

**Comment by Rod911** [comment]
```
swal.fire({
    didOpen: function () {
    }
})
```
Can also be done
