### ISSUE TITLE
input in the text property is not selectable with html: true

### ISSUE THREAD

**Issue by bulkan** [t4t5/sweetalert#289]
Setting `html` to true allows us to render a input box but I am not able to select it

```javascript
sweetAlert({
  title: "What is your name?",
  text: '<input type="text">', 
  type: "warning",
  showCancelButton: false,
  confirmButtonText: "Yes, delete it!",
  closeOnConfirm: false,
  html: true
}
```

**Comment by mattbucci** [comment]
Remove the visible class from your JS.

The part where it says setTimeout.... is breaking it...I can't seem to figure out why though as no css styles were being applied
  // Animation when opening modal
  function openModal() {
    var modal = getModal();
    fadeIn(getOverlay(), 10);
    show(modal);
    addClass(modal, 'showSweetAlert');
    removeClass(modal, 'hideSweetAlert');

    previousActiveElement = document.activeElement;
    var $okButton = modal.querySelector('button.confirm');
    $okButton.focus();

    setTimeout(function() {
      addClass(modal, 'visible');
    }, 500);

    var timer = modal.getAttribute('data-timer');

    if (timer !== "null" && timer !== "") {
      modal.timeout = setTimeout(function() {
        sweetAlert.close();
      }, timer);
    }
  }

**Comment by mattbucci** [comment]
So basically in order to 'fix this' I had to remove all keyboard support. Hope that helps, in my case I didn't need keyboard support anyway

**Comment by bulkan** [comment]
Thanks for following up on this. We decided to just use an actual modal when requiring user text input. We still use sweetalert for alerts :)

**Comment by t4t5** [comment]
Fixed in v0.5.0! Hope you replace your ugly prompt modals with SweetAlerts now @bulkan ;)

**Comment by costa974** [comment]
in woocommerce it shows an inputbox!

<fieldset>
      <input type="text" tabindex="3" placeholder="">
      <div class="sa-input-error"></div>
    </fieldset>

**Comment by costa974** [comment]
<fieldset>
      <input type="text" tabindex="3" placeholder="">
      <div class="sa-input-error"></div>
    </fieldset>
