### ISSUE TITLE
Creating batch of alerts

### ISSUE THREAD

**Issue by NicoSaul** [t4t5/sweetalert#292]
Hi, I have the following situation: I have a form and depending on some parameters I will show an alert and ask the user to confirm, the average number of alerts are 3 of about 5 posibles.

How can I make my code work as if it was synchronous? I need to call one alert, if users confirms call the other one, if users confirms call the other one...and so on.

I have looked for control flow librarys but prefer to hear an opinion here first.

Thanks!

**Comment by t4t5** [comment]
This should be much easier to do in the new SweetAlert 2.0 thanks to [promises](https://sweetalert.js.org/guides/#using-promises). If you combine it with ES2017 `async/await`, you can get a nice quasi-synchronous workflow! :)
