### ISSUE TITLE
Loading feature

### ISSUE THREAD

**Issue by chriscct7** [t4t5/sweetalert#302]
Is there any plans to add a loading feature similar to the Android fork of this (example in the Usage section of their readme) https://github.com/pedant/sweet-alert-dialog

**Comment by t4t5** [comment]
Definitely interesting. Will look into it!

**Comment by chriscct7** [comment]
This would be incredibly cool to have, especially for those using sweet alert in a form submission where we could show the loading state while data is being verified and after its validated show success and if not show the fail state.

**Comment by ecabuk** [comment]
It would be great! Do you considering to implement this feature?

**Comment by xming13** [comment]
+1

**Comment by serhiykrupka** [comment]
+1

**Comment by t4t5** [comment]
Will start working on this once the beta-tag for 1.0.0 is gone (about a week from now). From a UI perspective, I think it makes most sense to place the loading spinner on the action button (similar to this: http://lab.hakim.se/ladda). Any objections?

**Comment by chriscct7** [comment]
I prefer the one in the android fork because in the progress bar one you
have to be able to know a sense of how long an action will take. In an Ajax
request I might not have that luxury.

**Comment by GeekPress** [comment]
I'm agree with @chriscct7, a loading like the android fork will be just awesome!

**Comment by adrianricardo** [comment]
1+ for the loading spinner on the action button (indifferent about the progress bar)... the animations are pretty "sweet"

**Comment by viion** [comment]
Hello,

Is this still being worked on or is there a way to get spinners inside it?

I don't like the button one because it's "Another click" for the user. If I have a table of comments, each with a delete button, I want that delete button to popup just a modal with a spinner. The android one is perfect for this but I can't seem to find out how to implement that.

**Comment by djm61** [comment]
For me, when a user clicks a link [or a button], I want to submit >=1 records to the database so I have an animated gif that I show in a swal just before I start sending data.  When data is done sending, I close the swal (or if an error occurs, I show the error in another swal).

No extra clicks for the user unless an error occurs.

**Comment by t4t5** [comment]
Loading indicators on the buttons have been done for a while. In SweetAlert 2.0, you simply use `closeModal: false` in the [button options](https://sweetalert.js.org/docs/#button) to trigger this.
