### ISSUE TITLE
[feature request] swal without buttons | css class option

### ISSUE THREAD

**Issue by virgo79** [t4t5/sweetalert#304]
Hi,
I'm using sweet alert to show chained messages during various ajax executions.
I wondered if it would be possible to show a window message without any buttons.
It would be very useful for example to show a temporary waiting message.

Concerning this and other user requests, more in general, I think that adding a new option to let people  add a custom ccs selector class to a window will solve many customization requests.

Thank you very much in advance.

**Comment by t4t5** [comment]
Both of the features you mentioned are actually available!

1. Check out the example [A message with auto close timer](http://tristanedwards.me/sweetalert) to see how you can hide all buttons with ```showConfirmButton: false```

2. Check out the ["Configuration"-part](http://tristanedwards.me/sweetalert) for how to add classes to the modals with ```customClass```

**Comment by zmmorabya** [comment]
Hello there,

Is it possible to add classes to elements generated inside?
