### ISSUE TITLE
Redirect after pressing OK

### ISSUE THREAD

**Issue by azlannohara** [t4t5/sweetalert#305]
First of all, I would to say kudos to Sweet Alert. Nice interface, definitely better than default. 

I current using code to show the notification. 

//Success
echo '<script>' ;
echo 'swal("Applicaton updated !", "", "success"); ; ';  
echo 'location.href = "summary_pc.php" ; ';
echo '</script>'; 

The problem was, I did not get a chance to click the "OK" button and the page already redirected. 

Is there a way for me to redirect the page after I click "OK" button ? And I would love to maintain it in PHP

**Comment by t4t5** [comment]
I'm afraid it's very hard to tell what you're doing wrong unless you post your code. :)

Here's an example of simple redirecting with JavaScript that you should be able to use: https://github.com/t4t5/sweetalert/issues/199

**Comment by azlannohara** [comment]
here is my code 

echo '<script>' ;
echo 'swal("Applicaton updated !", "", "success"); ; ';  
echo 'location.href = "summary_pc.php" ; ';
echo '</script>';

**Comment by azlannohara** [comment]
Here is my code:

```
echo '<script>' ;
echo 'swal("Applicaton updated !", "", "success"); ; ';  
echo 'location.href = "summary_pc.php" ; ';
echo '</script>'; 
```
