### ISSUE TITLE
Features missing

### ISSUE THREAD

**Issue by azev** [t4t5/sweetalert#306]
Keyboard support is missing:
- Keys Left/Right: navigate buttons (cancel/confirm)

Custom positioning of the message box:
- bottom, top, bottom-right, ...

**Comment by alvarotrigo** [comment]
+1 Plus pressing "Enter" to accept the alert or "Esc" to cancel it.

**Comment by t4t5** [comment]
I think it's better to use tabs for jumping between the buttons and positioning the modal can be done using a custom class (with `className`) and some CSS.
