### ISSUE TITLE
[Docs] Missing some examples

### ISSUE THREAD

**Issue by toubou91** [t4t5/sweetalert#307]
The following two examples are missing from http://tristanedwards.me/sweetalert 

swal('OK', '', 'success');
![image](https://cloud.githubusercontent.com/assets/5684688/6601014/bb1269b8-c81b-11e4-9018-04cd0e311721.png)

swal('', 'OK', 'success');
![image](https://cloud.githubusercontent.com/assets/5684688/6601031/e05d4c7e-c81b-11e4-95be-944ec83a5efa.png)

**Comment by t4t5** [comment]
I think the first example is pretty straight-forward to be honest. Thanks though. :)
