### ISSUE TITLE
Call doneFunction after timer expires

### ISSUE THREAD

**Issue by yagop** [t4t5/sweetalert#312]
I would like to call `doneFunction` when the timer expires, it is possible?

**Comment by rymohr** [comment]
:+1: This one surprised me too.

**Comment by t4t5** [comment]
This is now available in 1.0.0 :)

**Comment by cosio55** [comment]
Hi, can anybody explain how to use this callback function? I looked for it on the codumentation but I couldn't find it :s.

I am trying to use it like this but it's not working:
```
swal({   
                    title: "¡Listo!",   
                    text: "Ya está la dirección de envío.",   
                    type: "success",
                    timer: 1000,   
                    showConfirmButton: false},   
                    function(){  
                       myFunction();
                    }
                    );
```

**Comment by xming13** [comment]
I replaced "myFunction()" with console.log('done') and it works correctly. Maybe the problem is with your "myFunction()". Try to use console.log and see if it works.

**Comment by cosio55** [comment]
I am using it on Meteor using this great package https://github.com/kevohagan/meteor-sweetalert so after further debugging I think the problem is on the version the package is currently using, so I will look for a way to update the version of the package, thanks @xming13 !
