### ISSUE TITLE
Wait before continue

### ISSUE THREAD

**Issue by azev** [t4t5/sweetalert#313]
If I display an error message with SWAL it won't wait until I click 'OK' to continue... it just go ahead and run the next line in code.

With standard alert() It won't run the next line in the code until the user press ok.

Is there a way to stop the code execution until the user clicks "ok" on swal?

**Comment by t4t5** [comment]
SweetAlert is not blocking like the normal alert, so you'll have to use the callback function to run something after the user has clicked "OK".

```javascript
swal({
  title: "Are you sure?",
  text: "You will not be able to recover this imaginary file!",
  type: "warning",
  showCancelButton: true,
  confirmButtonColor: "#DD6B55",
  confirmButtonText: "Yes, delete it!"
}, function(){
  console.log("No we run the next line of code!"
});
```

**Comment by PALYBOK** [comment]
Sorry but :
`console.log("No we run the next line of code!");`
Not:
`console.log("No we run the next line of code!"`
Just to joke ! :D
