### ISSUE TITLE
Implement password prompts

### ISSUE THREAD

**Issue by waldyrious** [t4t5/sweetalert#314]
Follow-up of #5

**Comment by parterburn** [comment]
This is closed with 0.5.0 release, change the inputType:

```js
  $('button.delete-account').click(function(e) {
    swal({
      title: "Are you sure you want to delete your account?", 
      text: "If you are sure, type in your password:", 
      type: "input",
      inputType: "password",
      showCancelButton: true,
      closeOnConfirm: false
    }, function(typedPassword) {
      console.log(typedPassword);
    });
  });
```

**Comment by t4t5** [comment]
As @parterburn said, just use ```inputType``` and you should be good to go! Also, feel free to check out the [SweetAlert tutorial](https://www.ludu.co/lesson/how-to-use-sweetalert) if you're unsure how to use the input features.

**Comment by waldyrious** [comment]
Thanks for the pointers, and sorry for the noise :)

**Comment by amrendraw3** [comment]
It's a working solution! Thanks :)

**Comment by abdoKa** [comment]
it work 👍
