### ISSUE TITLE
Preload value in sweet alert prompt

### ISSUE THREAD

**Issue by daybaryour** [t4t5/sweetalert#321]

**Comment by t4t5** [comment]
?

**Comment by daybaryour** [comment]
First of all i must say the sweetalert prompt is a beautiful addition made
my ui much more subtle.Thanks and well done.

I'm trying to add an initial parameter in the prompt box like in
javascript's prompt.

E.g prompt('This is the prompt', 'Initial parameter in the prompt box ');

Looking forward to hearing back from you.

**Comment by debussy2k** [comment]
I want this function, too. Thanks

**Comment by bendulum** [comment]
+1 shouldn't be too hard to add :)

**Comment by dgbeer** [comment]
try

$('input').val(startValue);

with your startValue after swal() call.

**Comment by barrykooij** [comment]
Would be great if this could be added as a property in the ``swal()`` call.
For now I've got it working but I feels 'hacky':
Code:
``jQuery('.sweet-alert input[type=text]:first' ).val('the val');``

**Comment by xming13** [comment]
+1

**Comment by tmos** [comment]
+1

**Comment by t4t5** [comment]
This is available in the latest version through `inputValue: 'someValue'`! :)

**Comment by webhacking** [comment]
+1

**Comment by rjuevesano** [comment]
`inputValue: "value here"`

**Comment by baig772** [comment]
> `inputValue: "value here"`

This doesn't work for me

**Comment by myparvind** [comment]
swal({
  content: {
    element: "input",
    attributes: {
      placeholder: "Type your password",
      type: "password",
      value: "Your value"
    },
  },
});
