### ISSUE TITLE
Use gulp-autoprefixer when building scss file

### ISSUE THREAD

**Issue by blaiprat** [t4t5/sweetalert#324]
Autoprefixer rocks! It saves you to have to write any vendor prefix in your styles, adding only those prefixes needed.

If you add `gulp-autoprefixer` in scss stream you can save yourself from writing `-webkit`, `-moz` ... in the original files.

**Comment by t4t5** [comment]
I'm planning to move SweetAlert from SCSS to PostCSS soon. As a nice side-effect, this will be easy to add!

**Comment by t4t5** [comment]
Well, "soon" turned out to be a little longer than expected! :P SweetAlert 2.0 now uses PostCSS and autoprefixer, yay!
