### ISSUE TITLE
Latest download files not working as in the docs

### ISSUE THREAD

**Issue by victorhazbun87** [t4t5/sweetalert#330]
Hello,

I tried to use the download files and they are not up-to-date. I tried to use TYPE option "input" and it was not working until I downloaded the source code from the source using my chrome inspector...

Please watch out for those kind of things... Thanks anyway!

**Comment by t4t5** [comment]
Did you download from Bower or NPM?

**Comment by EarthDweller** [comment]
sweetalert/lib/sweet-alert.min.js – witout apdates – d=["success","error","warning","info"]
https://github.com/t4t5/sweetalert/blob/master/lib/sweet-alert.min.js

**Comment by t4t5** [comment]
I'm not sure how you got this error since Bower and NPM are up to date for me. Closing.
