### ISSUE TITLE
allowOutsideClick is ignored

### ISSUE THREAD

**Issue by Untit1ed** [t4t5/sweetalert#334]
While SweetAlert animation is playing clicking outside will close the pop-up even if `allowOutsideClick` is set to `false`.

A quick workaround would be to set `closeOnCancel` to `false`. But of course it is not going to work for cases when you have a cancel button in your alert.

**Comment by Nimdis** [comment]
+1, I have the same issue.

**Comment by TomTasche** [comment]
i think https://github.com/t4t5/sweetalert/pull/327/files should fix your problem

**Comment by thejae** [comment]
Without @TomTasche pull request. I noticed it'll work if you set on `closeOnConfirm` and `closeOnCancel` to false.

**Comment by t4t5** [comment]
Fixed in 2.0 using `closeOnClickOutside: false`.

**Comment by SanaSalmanzadeh** [comment]
you must change
allowOutsideClick: "false",
to
allowOutsideClick: false,
it does not need " if you delete it is work correctly
