### ISSUE TITLE
Fails to spawn a sweetalert box when ajax response is returned too quickly

### ISSUE THREAD

**Issue by sanchitgoyal01** [t4t5/sweetalert#335]
$().ready(function() {
    $(".remove").click(function() {
        // store data for the ajax action -- or else it won't work!
        var sectionID = $(this).data("sectionId");
        var assistantEmpl = $(this).data("assistantEmpl");

        swal(
            {
                title: "Are you sure?",
                text: "This action cannot be undone",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#009900",
                confirmButtonText: "Yes, I'm sure!",
                closeOnConfirm: true,
                closeOnCancel: true
            },
            function(isConfirmed) {
                if (isConfirmed) {
                    $.ajax({
                        type: "DELETE",
                        url: "/proctoring/sections/" + sectionID + 
                            "/assistants/" + assistantEmpl,  
                        dataType: "json"
                    }).done(processResponse);
                }
            }
        );
    });

    $(".add").click(function() {
        // store data for the ajax action -- or else it won't work!
        var sectionID = $(this).data("sectionId");
        var assistantEmpl = prompt("Please enter your empl");

        $.ajax({
            type: "POST",
            url: "/proctoring/sections/" + sectionID + "/assistants/create/",
            data: {empl:assistantEmpl},
            dataType: "json"
        })
        .done(processResponse);
    });
});

function processResponse(response, redirectLink) {
    var reasonText;

    if (response.STATUS) {
        swal({
            title: "Nice!",
            text: "Your submission was successful!",
            type: "success",
            confirmButtonColor: "#090",
            allowOutsideClick: true
        }, function() {
            location.reload();
        });
    } else {
        switch(response.REASON) {
            case "InvalidPersonEmpl":
                reasonText = "Person not found in the system."
                break;

            case "DuplicateAssistantMembersip":
                reasonText = "Person is already an assistant for this course.";
                break;

            default:
                reasonText = "Your submission was unsuccessful."
        }

        swal({
            title: "Error!",
            text: reasonText,
            type: "error",
            confirmButtonColor: "#090",
            allowOutsideClick: true
        });
    }
}

**Comment by t4t5** [comment]
Sorry, I'm not sure I understand the problem here. Could you specify?

**Comment by sanchitgoyal01** [comment]
Sorry it seems to be an issue with an older version of sweet alerts we are using. I figure when we will update it should go away. I will close this for now and post a better and more informed issue later if I find it persists.
