### ISSUE TITLE
Module handle-click.js is broken

### ISSUE THREAD

**Issue by zauni** [t4t5/sweetalert#337]
Hi,
I just wanted to report a bug in the handle-click.js module.
If I use the /dist/sweetalert-dev.js or /dist/sweetalert.min.js it's throwing an error when I close the modal because in your handleConfirm or handleCancel Methods you do `sweetAlert.close();` where sweetAlert is undefined. I think this is because you don't import sweetAlert into the handle-click.js module, so the sweetAlert variable is never defined in the browserify output.
Maybe this is also the case in other modules.
Thanks for your time and hopefully you can resolve this issue easily :)

**Comment by SnidelyWhiplash** [comment]
I'm experiencing the same thing.

**Comment by t4t5** [comment]
I'm not able to reproduce this. Could you guide me through your setup quickly? It should be an easy fix! :)

**Comment by zauni** [comment]
I noticed that this is just visible if you use an AMD loader. If you don't use an AMD loader the sweetAlert variable is globally available on the window object and no exception is being thrown.

**Comment by t4t5** [comment]
Ref to #345. Please [upgrade to SweetAlert 2.0](https://sweetalert.js.org/guides/#upgrading-from-1x) :)
