### ISSUE TITLE
Publish version5 npm

### ISSUE THREAD

**Issue by HusseinTaha** [t4t5/sweetalert#338]
Hello,
Can you please publish version 5.0 to npm?
Because I need to use the input type of sweetAlert.
Thank you :)

**Comment by t4t5** [comment]
It is published, no? Just do `npm install sweetalert@0.5.0` if you want 0.5.0. I would recommend migrating to v1.0.0-beta soon though in order to use the new file system and be ready for upcoming updates!

**Comment by HusseinTaha** [comment]
Yes Thank you very much :)

**Comment by t4t5** [comment]
Np!
