### ISSUE TITLE
Doesn't Replicate Stopping Mechanism Of Alert

### ISSUE THREAD

**Issue by mrrobertcardona** [t4t5/sweetalert#339]
This library doesn't seem to be able to replace the alert completely, in particular the built in stopping mechanism the alert has. Here is an example:

```
if (false) {
  alert("This is the error message");
  location.reload();
} else {
  swal("Oops...", "This is the error message", "error");
  location.reload();
}
```

and you can test on [jsfiddle](http://jsfiddle.net/).

The first code block will wait until you click okay to reload the page, whereas your tool will reload immediately.

**Comment by lepickle** [comment]
One of the workarounds I used here is

	swal({
	  title: "Reload?",
	  text: "Reload?",
	  type: "warning",
	  confirmButtonText: "Reload!",
	},
	function(){
		location.reload();
	});

since you still need to create a function for the confirm button

**Comment by zauni** [comment]
You can wait until the callback is called to reload the page. Like this:
```javascript
sweetAlert({
  title: "Oops...",
  text: "This is the error message",
  type: "error"
}, function() {
  location.reload();
});
```

**Comment by t4t5** [comment]
As @zauni says, you can use the callback method to control the flow of your app. Event though it might look a little ugly, there's sadly no way around this as far as I know. Closing.
