### ISSUE TITLE
Array Indexof polyfill

### ISSUE THREAD

**Issue by ImBobby** [t4t5/sweetalert#34]
As discuss at https://github.com/t4t5/sweetalert/issues/27, this plugin won't work in IE8 (unless you're planning not to support IE8).

If you're planning to add IE8 support, adding [indexof polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf#Polyfill) might fix the issue.

If no IE8 support, I suggest add **Browsers Support** section in README.

**Comment by t4t5** [comment]
IE8 is now supported and the README has been updated with a browser compatibility list. :+1:
