### ISSUE TITLE
support requirejs for 0.5.0 version

### ISSUE THREAD

**Issue by drgrey87** [t4t5/sweetalert#340]
requireJs load sweet-alert.js, but in global scope i can't find swall and sweetalert. I think need add "window.swal = window.sweetAlert = sweetAlert = swal = function() {" to 223 string of sweet-alert.js

**Comment by tonillo** [comment]
i encountered the same problem and i tried to solve this issue as reported below: 
this is my solution for working properly with RequireJS
in sweetalert-dev.js change the RequireJS section from line 261 to 273

```javascript
/*
 * Use SweetAlert with RequireJS
 */
if (typeof define === 'function' && define.amd) {
  define(function () {
    if(typeof window !== 'undefined'){
      window.sweetAlert = window.swal = sweetAlert;
    }
    return sweetAlert;
  });
} else if (typeof module !== 'undefined' && module.exports) {
  module.exports = sweetAlert;
}
```

**Comment by drgrey87** [comment]
It works, but i got new problems:
1) When i installed sweetalert,  i didn't find sweetalert-dev.js in my folder (sweetalert). Than i downloaded this file from repository. But i don't know is it a good way?
2) When i call sweetalert, within sweetalert folder i got input tag (http://pix.toile-libre.org/?img=1432142244.png )
 
here my code:
 sweetAlert({   title: "Are you sure?",   text: "You will not be able to recover this imaginary file!",   type: "warning",   showCancelButton: true,   confirmButtonColor: "#DD6B55",   confirmButtonText: "Yes, delete it!",   closeOnConfirm: false }, function(){   sweetAlert("Deleted!", "Your imaginary file has been deleted.", "success"); });

**Comment by tonillo** [comment]
when you click on 'cancel' or 'delete it' the modal disappear?

try to download package from http://t4t5.github.io/sweetalert/

open sweetalert-dev.js, on line 261 change the RequireJS AMD definition as reported in my previous post... 

try this, it probably solve the second problem...

**Comment by drgrey87** [comment]
if a click on 'cancel' or 'delete it' the modal disappear, but input remain all the same.

**Comment by t4t5** [comment]
Have you guys tried the latest version (v1.0.1)? Hopefully the problem is fixed!
