### ISSUE TITLE
Theme externalisation

### ISSUE THREAD

**Issue by tmos** [t4t5/sweetalert#343]
In my opinion, sweetalert.css may not include the default theme, but just CSS for show/hide behaviour.

With the current setup, we have to redefine all the swal theme to the website's theme, or add classes and !important tags to our CSS properties to override default behaviour, and this is not a good thing.

In my opinion, that would be a better set-up :
- sweetalert.css : behaviour, show/hide
- themes/default.css : default theme (defining colors, borders, etc.)

That way, Sweet Altert would be by-default website adapted (using font style, buttons styles, etc.).

**Comment by t4t5** [comment]
Hm, that's a tough choice. I understand the idea, but at the same time I think the library should be as "plug-and-play" as possible. Forcing users to include three separate files just to get the basics to work seems overly complicated.

Do you really need that many `!important` tags for your theme? The only thing I've used them for in the alternative themes that come with SweetAlert is the button focus, and that's because it's a property set via JavaScript (so even splitting up the CSS into multiple files wouldn't fix that).

**Comment by tmos** [comment]
In my situation, I have a webiste with a complete theme (including theming for UI items, like raw buttons, inputs, etc.). So I have like a "kit", and every new item just adapt to the CSS, that is the more generic as possible.

So to adapt swal to my website, I have to create a full swal theme, copying/pasting my css properties. I'm not very comfortable with duplicating all my UI CSS.

It's true that people would have 3 files to include instead of two, but 
```
<script src="dist/sweetalert.min.js"></script>
<link rel="stylesheet" type="text/css" href="dist/sweetalert.css">
<link rel="stylesheet" type="text/css" href="theme/default.css">
```
don't seems "overly complicated" compared to 
```
<script src="dist/sweetalert.min.js"></script>
<link rel="stylesheet" type="text/css" href="dist/sweetalert.css">
```

It's true that this choice is important, but I think going in a (subtle) more modular architecture may open swal to more personalization, and so to have better integration on websites with a full graphic identity.

**Comment by SnidelyWhiplash** [comment]
+1, should definitely not have to redefine tons of styles.

Perhaps a middle ground would be to provide two versions. `/dist/sweetalert.css` could remain the same, but there could also be a `/dist/sweetalert-themeless.css` that just has the structural styling?

**Comment by tmos** [comment]
This may be a good choice, indeed.

If you want to go in this way without having a pain maintaining two CSS files, you may have a look at some CSS post-processors, like (pleeease.io)[pleeease]. It is useful to put multiple CSS files in one in a logical way.

**Comment by t4t5** [comment]
I've decided to include the default stylesheet into the JS-file instead. The good news is that it should be easier to theme the libray now thanks to the [new classes](https://sweetalert.js.org/docs/#theming)
