### ISSUE TITLE
TouchStart Event Not Handled for Mobile Devices

### ISSUE THREAD

**Issue by carlosrymer** [t4t5/sweetalert#349]
I'm not sure if this is part of the roadmap, but touchstart is not handled for clicking outside or on the buttons. I'm going to come back to this and open a PR fixing this issue.

**Comment by t4t5** [comment]
I believe touch support works better in mobile devices now. I'm unsure we really want `touchStart` specifically, since it could lead to accidental presses. `touchEnd` sounds better in that case. :)
