### ISSUE TITLE
Wrong font-size with "html:true" activated on Mobile Device

### ISSUE THREAD

**Issue by mr-sparks** [t4t5/sweetalert#357]
I've got the following problem:

When i activate HTML (Since i need a <br/> in my text) with html:true, the break is recognized, but the font-sizes is approx. 2-3px bigger than it should. Its working perfect on desktop, but not on mobile devices (tested on iPhone 6).

Better said:

.sweet-alert p is set to font-size:15px but with "html:true" it looks like font-size:18px;

Does anyone else experience the same?

**Comment by Maugik** [comment]
still looking but nothing yet sparks. Just published my website yesterday using swal and just realized it looks pretty awkward using i-phone

**Comment by anatolibarski** [comment]
I have same issue on iPhone 6. I think sweet alert has too many issues for enterprise

**Comment by t4t5** [comment]
`html: true` has been deprecated in favour of the [content option](https://sweetalert.js.org/docs/#content) as of 2.0. I believe this takes care of weird rendering issues.
