### ISSUE TITLE
Sweet alert is overriding the previous alert in a loop

### ISSUE THREAD

**Issue by usamamashkoor** [t4t5/sweetalert#359]
i am call the sweet alert function on inside a loop but sweetalert is only showing me one time,i think it is overriding the previous sweetalert,bcz when i do the simple alert it does pop up twice then but sweet alert is only showing me one time.
What i want to do is to to sweet alert to show the second or third alert when i click on ok aor cancel button otherwise dont't shwo the second or next alert according to loop itreration
Here is my code
    $.each(data,function(index,elem){  
               NotificationPopUpIsApprove();

```
                });
```

function NotificationPopUpIsApprove(){
swal({
          title: "Are you sure?",
          text: "The Task "+ task_name + " In Project " + project_name + "is Completed by " + uname  ,
          type: "warning",
          confirmButtonText: "Approve!",
          closeOnConfirm: false,
          confirmButtonColor: "#44E753",
          cancelButtonText: "Reasssign!",
          showCancelButton: true,

```
    },
    function(isConfirm){
      if (isConfirm === true) {
        return true;
      }else{
        return false;
      }
    });
```

}
thanks in advance.

**Comment by injaon** [comment]
I'm also affected with this bug. Did you find any solution?

**Comment by usamamashkoor** [comment]
@injaon Nope :(

**Comment by CEOHarshit** [comment]
I  am trying to call a swal sweet alert function from another function. Please help :( Its not working.

window.onload=function(){

      swal({   title: "Seconds2Website",   text: "Your FIRST Name:",   type: "input",   showCancelButton: true, OnConfirm:school();  
             animation: "slide-from-top",     inputPlaceholder: name }, function(inputValue){   if (inputValue === false) return false;
             if (inputValue === "") { swal.showInputError("You need to write something!"); return false } 
               document.getElementById("name").innerHTML=inputValue || "Unknown";

    });
        

     }

function school(){

      swal({   title: "Seconds2Website",   text: "Your FIRST Name:",   type: "input",   showCancelButton: true,   
             animation: "slide-from-top",     inputPlaceholder: name }, function(inputValue){   if (inputValue === false) return false;
             if (inputValue === "") { swal.showInputError("You need to write something!"); return false } 
               document.getElementById("name").innerHTML=inputValue || "Unknown";

    });



}

**Comment by t4t5** [comment]
Sorry, I'm having trouble reading your code, but I believe it should be easier to chain SweetAlerts after one another thanks to the new 2.0 that uses [promises](https://sweetalert.js.org/guides/#using-promises)
