### ISSUE TITLE
callback not cleared

### ISSUE THREAD

**Issue by Batistleman** [t4t5/sweetalert#367]
I'm having some problem with swal in chrome 43. I have isolated the bug to this:

```
swal({
        title: "Test",
        text: "swal test",
        showCancelButton: true,
        closeOnConfirm: false,
        animation: "slide-from-top"
    }, function(inputValue) {
        alert("test2");
        swal({
            title: "Success!",
            text: "testing...",
            type: "success"
        }, function(){
            alert("test1");
        });
    });
```

This code should call: 
- test2
- test1

But instead I get:
- test2
- test2
- test1

It seems as if the connected callback is not cleared. The weird thing is that I can't reproduce it in jsfiddle: http://jsfiddle.net/a82gtg4x/

(I'm using meteorjs and 1.0.1 of swal)

Can I somehow look at the swal callback?

**Comment by Batistleman** [comment]
it seems like it's more related to my setup (not meteor specifically). 

I've made a minimal MeteorPad to verify: http://meteorpad.com/pad/z4d5AzrkXLED6Dpvr/SwalTests

**Comment by stevenhornung** [comment]
I've been seeing a similar issue here too.  If one swal is opened then I open another in the same session, the first callback is always fired.  Any ideas here? This seems to be a fairly new bug as I have just started seeing it but have been using swal for a few months now.

**Comment by YannDanthu** [comment]
Hi, same here.
If I have 2 distincts swal (swal1 and swal2) with each one a different callback, if I open swal1 first its callback will be called.
But when swal2 is opened then the callback of swal1 is called, not the one from sawl2 !

**Comment by satyavh** [comment]
For me this was caused by meteorhacks:zones package

**Comment by t4t5** [comment]
This seems to be caused by external libraries. Please [upgrade to SweetAlert 2.0](https://sweetalert.js.org/guides/#upgrading-from-1x) and reopen if the issue persists.
