### ISSUE TITLE
Is it possible to add more than two buttons?

### ISSUE THREAD

**Issue by cosio55** [t4t5/sweetalert#368]
I think it would be nice to include more than just two buttons on the prompt, and let each one of them have its own callback function.

**Comment by maeishoj** [comment]
interested too.. anyone?

**Comment by masteradhoc** [comment]
+1

**Comment by maeishoj** [comment]
is this page dead?

**Comment by kirilgorbachov** [comment]
+1

**Comment by pchaganti** [comment]
+1

**Comment by cyberbobjr** [comment]
+1

**Comment by Sundfjord** [comment]
+1

**Comment by cmarfil** [comment]
+ 1

**Comment by rgraf20** [comment]
+1 Please!!!

**Comment by albert28** [comment]
+1!

**Comment by prYmea** [comment]
+1

**Comment by amandaerickson** [comment]
+1

**Comment by mayankchhabra** [comment]
+1!!!

**Comment by zamboney** [comment]
:+1:

**Comment by moshfeu** [comment]
I added the ability here: https://github.com/moshfeu/sweetalert. If it will be OK I will create a pull request and marge it to the plugin itself.

**Comment by ferchoslim** [comment]
@moshfeu how can i use the new ability?

**Comment by moshfeu** [comment]
For now, you can download the source code and using it like in the example. When I know how to "compile" it, I will commit with a minify version.

**Comment by t4t5** [comment]
@moshfeu You just need to run the "gulp" command. For the official repo, I'm a bit reluctant to just adding more and more features as object params, so I'm going to look into using some kind of templating system to let people customise their alerts more.

**Comment by moshfeu** [comment]
`You just need to run the "gulp" command` Where can I run it?

**Comment by Toooy** [comment]
急需此功能！感谢！

**Comment by thyhates** [comment]
@moshfeu When there is more than one alert in a page,some problem happen. https://plnkr.co/edit/xXefAOo4uPQfX8iGL4w6?p=preview

**Comment by moshfeu** [comment]
@thyhates  What problems? Can you explain?

**Comment by thyhates** [comment]
@moshfeu In the Plunker, first click "show 1",then click "show 2", it show the same btns as "show 1".
Then refresh page,if you first click "show 2",then click "show 1",it show the same btns as "show 2".

**Comment by SuperRiven** [comment]
+1

**Comment by Toooy** [comment]
＋1

**Comment by samuelg0rd0n** [comment]
+1 any updates on this?

**Comment by t4t5** [comment]
I've been working on a new major release of SweetAlert, which will solve this, and many other issues, in a very clean way. Stay tuned! :)

**Comment by t4t5** [comment]
Alright, it's finally here people, sorry for the long delay! In SweetAlert 2.0, you can add as many buttons as you like: https://sweetalert.js.org/guides/#customizing-buttons
