### ISSUE TITLE
Support for new lines in message?

### ISSUE THREAD

**Issue by koullislp** [t4t5/sweetalert#374]
What the title says, please??

**Comment by djm61** [comment]
If you set the ```html``` property to ```true```, then you can use line breaks --> the ```<br/>``` tag.

**Comment by dann1609** [comment]
How I do this?

**Comment by JunkyBulgaria** [comment]
swal({ html: true, title: 'hi', text: 'te<br/>st' });
doesn't seem to work for me

**Comment by themightystephen** [comment]
It works if you set the `html` property to the actual html itself (i.e. get rid of the `text` property and set the `html` property to the html content).

**Comment by paokodo** [comment]
It works for me,  use \n
swal("Oops", "Line 1.**\n** line2.", "error");

**Comment by waroakawa** [comment]
it works just in part of text like this :     
`swal("Oops",` "Line 1.\n line2.", "error");`
but if you want to make it in part of title .. it dosn't work : 
 `swal("Oops\nOops", "Line 1", "error");`

**Comment by Matheus-Ribeiro95** [comment]
sorry, but in my opnion doesnt make sense use multiple lines in title (and following a good design spec).

**Comment by romadhonbyar** [comment]
![image](https://user-images.githubusercontent.com/606799/91399789-d0782900-e868-11ea-8d12-c6d30fc3c40f.png)
![image](https://user-images.githubusercontent.com/606799/91400001-26e56780-e869-11ea-929d-068b623b59bb.png)

This is a solution, but not the best.

**Comment by CaptRango** [comment]
` 
  swal({            
            buttons: ["Wait ", "Add Details"],
             html: true,
             text: "Text one .\n  Text 2.\n Text 3."
   })
`
Here is the solution. Enjoy
