### ISSUE TITLE
sweetAlert no longer working for IE8

### ISSUE THREAD

**Issue by JohnRSim** [t4t5/sweetalert#377]
Line 442 Obj is not supported.
},{"./handle-dom":4,"./handle-swal-dom":6,"./utils":9}],4:[function(require,module,exports){

Running from IE8 VM modern.ie

**Comment by masteradhoc** [comment]
Hi John

Sweetalert from Version 1 on is no longer supporting Internet Explorer 8, im afraid..

**Comment by JohnRSim** [comment]
Thanks for the update.
I missed it in the release notes but I see it now :)
