### ISSUE TITLE
Method to change button text and color

### ISSUE THREAD

**Issue by thejae** [t4t5/sweetalert#380]
I am using SweetAlert to display a message while the user data is being populated. I want to change the confirmButtonText to 'Done' and the confirmButtonColor to green once all user data is done loading.

**Comment by t4t5** [comment]
Check out the new [button options](https://sweetalert.js.org/docs/#button) in SweetAlert 2.0 for customising your button values. The color should be set [using CSS](https://sweetalert.js.org/docs/#swal-button) and just appending classes imo.

**Comment by AnuGupta1** [comment]
function ssolLoginPopUp(ssoUrl) {
    swal({
        title: 'Organizational Login Detected',
        text: 'If you have an internal email, click "Continue" to proceed to organizational login. Otherwise, use Standard login.',
        type: 'info',
        showCancelButton: true,
        confirmButtonColor: "#0c4c00", // i tried here but not working 
        confirmButtonText: "Standard login", 
        cancelButtonText: "Continue",         
        closeOnConfirm: true,
        closeOnCancel: true
    }, function (isConfirm) {
        debugger;
        localStorage.setItem('popupLastShownTime', new Date().getTime());
        if (!isConfirm) {
            window.location.href = ssoUrl;
        }

    });
}i am not change my button colour too how can do this
