### ISSUE TITLE
Textarea tag support instead of input tag

### ISSUE THREAD

**Issue by PharaohMaster** [t4t5/sweetalert#383]
It would be great if textarea tag could be used instead of input tag because of multi line support of textarea tag.

**Comment by jhiver** [comment]
+1

**Comment by totalard** [comment]
any info?

**Comment by maurivan** [comment]
+1 :)

**Comment by PharaohMaster** [comment]
I've submitted PR on Jun 19th. Really don't know why it's not included already.

**Comment by boika** [comment]
+1 =)

**Comment by stephenvicino** [comment]
+1

**Comment by abhishekjadhav3017** [comment]
+1

**Comment by szigya** [comment]
+1

**Comment by kenberkeley** [comment]
use `html: true` can satisfy

http://stackoverflow.com/questions/37790965/how-to-add-textarea-tag-as-input-element-in-sweet-alert-using-jquery#answer-37791292

**Comment by t4t5** [comment]
This can now be done using the new [content option](https://sweetalert.js.org/docs/#content) in SweetAlert 2.0:

```javascript
swal({
  content: { 
    element: "textarea",
  } 
})
```

**Comment by ciaran036** [comment]
Hi @t4t5 , do you know which version of Sweet Alert 2.0 introduced the content option? Thanks :)

**Comment by CharlieBrownCharacter** [comment]
Any way you could style "textarea"?
