### ISSUE TITLE
Get current sweetalert instance

### ISSUE THREAD

**Issue by maeishoj** [t4t5/sweetalert#396]
I want to access the current sweetalert instance i have open and depending on what button the user clicks, change some value in the modal.

I cannot see to figure out however how to access the instance, is it possible?

**Comment by t4t5** [comment]
Not sure what value you want to change, but in 2.0 I would achieve this by first making sure the button doesn't close the modal using `closeModal: false` in the [button options](https://sweetalert.js.org/docs/#button), then simply changing the DOM with JS.
