### ISSUE TITLE
Support for isomorphic JS apps

### ISSUE THREAD

**Issue by Hagbarth** [t4t5/sweetalert#397]
So I'm working on an isomorphic JS app, that uses SweetAlert.
I require it in my main script, and it works great with browserify, but the issue is that the scripts is also rendered on the server, which throws an error because SweetAlert expects window to be defined.

I have done this:

``` javascript
if (typeof window !== 'undefined') {
  const swal = require('sweetalert');
}
```

Which fixes it, but seems hacky to me, especially when all my other imports are ES6 style, which cannot be in an if statement.

**Comment by t4t5** [comment]
SweetAlert 2.0 now supports universal JS apps! Sorry it took a while :)
