### ISSUE TITLE
Where are modules loaded from?

### ISSUE THREAD

**Issue by maeishoj** [t4t5/sweetalert#398]
Inside the dist folder, there is the module folder.

I wanted to change something in "set-params.js" but it's not that file that is loaded!

I changed line 156 from `hide($confirmBtn);` to `if($confirmBtn) hide($confirmBtn);`

when I inspect in chrome I see that has not changed and the set-params.js is actually not in the folder I expect, but in localhost:xxxx/Users/Tristan/dev/sweetalert/sweetalert.es.6.js

Can anyone explain me what's going on?

**Comment by lucascaton** [comment]
@maeishoj same is happening here, did you find out?

**Comment by t4t5** [comment]
Sorry for the far too long delay. The `dist` folder is only the compiled source of the `src` folder, so after changing something in `src` you need to compile it using `npm run build` (in 2.0).
