### ISSUE TITLE
Version to Material Design Lite

### ISSUE THREAD

**Issue by rafaelguinho** [t4t5/sweetalert#399]
It is possible to be created a version for Material Design Lite?

**Comment by kiempoturner** [comment]
Wew beat me

**Comment by rafaelguinho** [comment]
Sorry?

**Comment by t4t5** [comment]
It's quite simple to define your own stylesheets (check out the `themes` folder) so get any style you want. I'm not planning on making a material design theme atm myself, so feel free to try if you're up for the challenge. :)

**Comment by rafaelguinho** [comment]
Ok! ty for answer my question!

**Comment by JVRibeiro** [comment]
Any plans for creating a Sweet Alert's theme gallery, with themes created and submited by users? For example, I would enjoy to create a Material Design theme for swal.
