### ISSUE TITLE
how to add multi filed

### ISSUE THREAD

**Issue by manojsinghrwt** [t4t5/sweetalert#405]
How I can add two filed example: email and password in alert box.

**Comment by t4t5** [comment]
It's not possible right now unfortunately. The original purpose of the library is to show only quick short messages.

However, many seem to request more advanced configuration, using only sweetAlert's modal UI, so I'm going to start looking into expanding the library in the future. :)

**Comment by manojsinghrwt** [comment]
Thanks t4t5 for your response,

I found a way to add multi filed in alert box using jQuery append and it working fine for me.
