### ISSUE TITLE
sweetalert does not stop execution of js

### ISSUE THREAD

**Issue by BernardA** [t4t5/sweetalert#411]
Hello

May be I am missing something but, contrary to the 'regular' js alert, it seems tha Sweetalert DOES NOT stop js execution till the user dismisses the alert.

The code below is part of a success handler of ajax call.

While the regular alert ( commented out below ) stops the next steps, SA doesn't. 

Is there a way to avoid this behavior?

Thanks
Bernard
`
			else{
                            swal({
                           title:'alert',
                            text:msg1,
                            type:'success'
                        });
                      // alert(msg1);
                        $('#filtermodel').hide(1000);
                        $('#step1 .green_tick').show();
                            //this to fetch data to fill suggested comments
                            $.ajax({
                            url: "used_dataentry.php",
                            dataType:"html",
                            data:'code='+'pitch_fill',
                            success: function (data) {
                            $("#pitch").html(data);			
                            }
                            });   
                        $('#step_pitch').show();
                        $("#pitch").focus();
                       //$('#sales_pitch input[type="submit"]').attr('disabled','disabled');
                
			};		
`

**Comment by t4t5** [comment]
Unfortunately, it's impossible to replicate that behavior in the library. You'll need to refactor your code in some way to make it stop when the SweetAlert shows up.

**Comment by BernardA** [comment]
Hi Tristan

Thanks for taking the time to reply.

Regards
Bernard

**Comment by talha08** [comment]
```
 async largeFileAlert (file) {
        try {
           const alert =  await Swal.fire({
                title: 'Are you sure?',
                text: `Warning, your image file is ${utils.bytesToSize(file.size)}. please verify it is not too heavy for this specific format.`,
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Yes, Keep it!',
                cancelButtonText: 'No, Cancel it'
            });
           return !!(alert.value && alert.value === true);
        } catch (e) {
            console.log('error:', e);
            return false;
        }
    },
```
