### ISSUE TITLE
input field not functional when used on top of a bootstrap modal 

### ISSUE THREAD

**Issue by mteichtahl** [t4t5/sweetalert#412]
I am currently calling swal from within a bootstrap modal. It seems that the buttons work but the input of the swal is not accepting a click nor does it ever take focus. I'm wondering if this is a known issue or possibly something I'm doing.

**Comment by KillerSquid** [comment]
I had the same issue.  What I ended up doing was 'hiding' the modal with modal.hide, opening the swal, doing whatever you need with the inputValue, then show the modal with modal.show on success or cancel of the swal.
Hope this helps.

**Comment by mteichtahl** [comment]
Dan
I found a fix for this. I'll post it tomorrow 

Sent from Outlook




On Mon, Aug 10, 2015 at 6:52 AM -0700, "Dan Kaufman" <notifications@github.com> wrote:












I had the same issue.  What I ended up doing was 'hiding' the modal with modal.hide, opening the swal, doing whatever you need with the inputValue, then show the modal with modal.show on success or cancel of the swal.

Hope this helps.

**Comment by diederik555** [comment]
What was the fix?

**Comment by YannDanthu** [comment]
Hi,

Same issue with sweet alert (as well as sweetalert2).
The input field does not get the focus on firefox only. This happens only when opening a swal from a bootstrap modal.

Cannot figure out the problem yet. Really strange.

**Comment by Cu4rach4** [comment]
I have the same problem...any one have a solution?

**Comment by Cu4rach4** [comment]
hi, this allow to show input placeholder, but is not fix to focus on input...

[#537](https://github.com/t4t5/sweetalert/pull/537)

**Comment by lynnpen** [comment]
I have the same problem， can't find the fix...

**Comment by S0c5** [comment]
+1

**Comment by Cinamonas** [comment]
I found that the culprit is `tabindex="-1"` that's set on Bootstrap's modal.

The fix:
```js
// call this before showing SweetAlert:
const fixBootstrapModal = () => {
  const modalNode = document.querySelector('.modal[tabindex="-1"]');
  if (!modalNode) return;

  modalNode.removeAttribute('tabindex');
  modalNode.classList.add('js-swal-fixed');
};

// call this before hiding SweetAlert (inside done callback):
const restoreBootstrapModal = () => {
  const modalNode = document.querySelector('.modal.js-swal-fixed');
  if (!modalNode) return;

  modalNode.setAttribute('tabindex', '-1');
  modalNode.classList.remove('js-swal-fixed');
};
```

**Comment by timm3** [comment]
I have a nearly identical issue, except it only occurs if the modal is so tall that it is scrollable on the y-axis.

**Comment by eminumut** [comment]
Please help me...

**Comment by navas** [comment]
Cinamonas's tab fix didn't work for me :(

**Comment by Alagaesia93** [comment]
+1

**Comment by eminumut** [comment]
@Alagaesia93 

Would you show me some examples?

**Comment by Alagaesia93** [comment]
@eminumut 

`
fixBootstrapModal()
swal({whatever}, function(isConfirm){
  whatever
  restoreBootstrapModal()
}
`

It works for me :)

**Comment by caleb87** [comment]
The fix generates a syntax error in IE11

**Comment by Cinamonas** [comment]
@caleb87, I've updated the snippet not to use arrow functions.

**Comment by t4t5** [comment]
This seems to be an issue with Bootstrap so I will close for now. Thanks for the fix @Cinamonas!

**Comment by gopal9999** [comment]
Hi , I have faced the same issue .
This issue can be solved by removing { tabindex="-1" } from Bootstrap Modal.
It's work fine for me.

**Comment by madmark81** [comment]
Does anyone know how to apply this fix in R? I'm having the same issue, but my attempts to convert it to R have failed so far

**Comment by jhoanborges** [comment]
> I found that the culprit is `tabindex="-1"` that's set on Bootstrap's modal.
> 
> The fix:
> 
> ```js
> // call this before showing SweetAlert:
> function fixBootstrapModal() {
>   var modalNode = document.querySelector('.modal[tabindex="-1"]');
>   if (!modalNode) return;
> 
>   modalNode.removeAttribute('tabindex');
>   modalNode.classList.add('js-swal-fixed');
> }
> 
> // call this before hiding SweetAlert (inside done callback):
> function restoreBootstrapModal() {
>   var modalNode = document.querySelector('.modal.js-swal-fixed');
>   if (!modalNode) return;
> 
>   modalNode.setAttribute('tabindex', '-1');
>   modalNode.classList.remove('js-swal-fixed');
> }
> ```

genius

**Comment by MateusFGoncalves** [comment]
For those who have more than one modal, you can use: 
[Documento sem título (1).pdf](https://github.com/t4t5/sweetalert/files/3223606/Documento.sem.titulo.1.pdf)

**Comment by Rubncal04** [comment]
It doesn't work for me, I have the same issue. can anyone help me or tell me what's my problem?

fixBootstrapModal()
Swal.fire({whatever}).then((result) => {
restoreBootstrapModal()
})

**Comment by NathanDeMol** [comment]
I had the same issue, removing tabindex worked, so long as the container didn't overflow, which would block the input again. I added a global observer to the swal firing to detect the modal that caused the issue and prevent it from overflowing. When closing the swal again, I reset that overflow to its original state. This still combined with removing the tabindex attribute.
// Hook into SweetAlert2 globally
$(document).ready(function() {
  // Observe SweetAlert2 open/close events
  const SwalOpenObserver = new MutationObserver(function(mutations) {
    for (const mutation of mutations) {
      mutation.addedNodes.forEach(node => {
        if (node.classList && node.classList.contains('swal2-container')) {
          // SweetAlert opened
          const $activeModal = $('.modal.show');
          // Only affect the currently open modal
          if ($activeModal.length) {
            $activeModal.css('overflow', 'hidden')
                        .removeAttr('tabindex');
          }
        }
      });
      mutation.removedNodes.forEach(node => {
        if (node.classList && node.classList.contains('swal2-container')) {
          // SweetAlert closed
          const $activeModal = $('.modal.show');
          // Restore overflow when SweetAlert closes
          if ($activeModal.length) {
            $activeModal.css('overflow-y', 'auto');
          }
        }
      });
    }
  });
  // Start watching the DOM for SweetAlert2 containers
  SwalOpenObserver.observe(document.body, { childList: true });
});
