### ISSUE TITLE
sweetalert dialog closes immediateley after opening 

### ISSUE THREAD

**Issue by brandonSc** [t4t5/sweetalert#414]
If I open sweetalert from an event-handler function, it closes immediately after it opens. 
Here is the bit of code I use to register the event handler: 
```
            <form onsubmit="showEmptyRepoWarn()" id="measure-the-heat">
                <div style="padding-top:20px;">
                    <div class="input-field col s12">
                        <input id="url" type="text" name="url" class="validate">
                        <label style="position:absolute"class="active" for="url">Git URL:</label>
                    </div>
                </div>

                <div class="heatbtn" id="id">
                    <button type="submit" class="btn waves-effect waves-light">Measure the Heat</button>
                </div>
            </form>
```
and here is what the event handler looks like, which actually opens the dialog:
```
 var showEmptyRepoWarn = function() { 
           swal({
                  title: "Git URL is empty",
                  text: "You left the Git URL field empty. You can go back and enter a URL now, or view a HeatMap for a random repository.",
                  type: "warning",
                  showCancelButton: true,
                  cancelButtonText: "Go back",
                  confirmButtonColor: "#DD6B55",
                  confirmButtonText: "Random HeatMap!",
                  closeOnConfirm: false
            },
            function(isConfirm){
                console.log(isConfirm);
            });
        };
```
However if I show the dialog as soon as the page loads, like so:
```
        $(document).ready(function(){
            showEmptyRepoWarn();
        });
```
Then it works as expected, without closing immediately after. But of course, I want to show the dialog in response to an event (like the user clicking a button).

Is this a bug, or am I just missing something in my code here to make this work?

**Comment by t4t5** [comment]
I think it's because you're binding an action to "onsubmit" which will by default redirect from the page you're on. Try removing the `onsubmit=` part in your HTML and add this to your JavaScript instead (using jQuery):

```javascript
$( "form#measure-the-heat").submit(function(event) {

  event.preventDefault(); // Prevent the page from redirecting

  // Put the swal-code here
});
```

**Comment by brandonSc** [comment]
`event.preventDefault()` did the trick, thanks! I was a little suspicious since the default JavaScript `alert()` worked in my original code, but I guess there must be some built-in magic there to prevent the page from redirecting.

**Comment by purnima26995** [comment]
after using event.preventDefault() it will not be able to move again to same menu

**Comment by AhmedELGAMMUDI** [comment]
use Ajax

**Comment by VishalS047** [comment]
Looks like it's a form submit, So when you click the button the page refreshes. That's why you see the alert for a second and it hides.

<button type="submit" class="btn waves-effect waves-light">Measure the Heat</button>
try by changing type = button
<button type="button" class="btn waves-effect waves-light">Measure the Heat</button>

**Comment by harpsichord-exact-match** [comment]
I realized the solution https://opencodes.space/questions/is-there-a-way-to-refresh-only-a-specific-div-when-clicked
