### ISSUE TITLE
[Feature Request] Multi Input

### ISSUE THREAD

**Issue by Wixely** [t4t5/sweetalert#415]
Please support this feature, I notice other users need this too.

I needed a prompt that supported multiple fields a few weeks ago so I wrote a little hack to get it working with sweet alert since I am not in any shape able to install a ton of the swal dependencies. 

I have the hack available here for anyone who needs it in the meantime:
http://wixely.com/dev/sam/
Disclaimer: I use a chrome only environment and as such do not require it to work on other browsers.

**Comment by bnowak008** [comment]
This is awesome!  I just started to create my own hack for it and this is just what I was looking to create.  Thanks so much for this.  
As a side note.  I tested on firefox and safari and it is working well.  On mobile it is working properly on chrome, android internet browser, and safari.  It is not working properly on firefox mobile.

Thanks again!

**Comment by artyomLisovskij** [comment]
Man, thank you for this tweak.
But i've catched bug: click outside of swalert and function will be still execute. (I see JSON alert in your demos when click outside of alert area).

**Comment by Wixely** [comment]
Hmm I cant make that happen... If I click outside the modal box it doesnt do anything, the . I'm sure you've already sorted it for your specific case though, happy to help.

**Comment by artyomLisovskij** [comment]
@Wixely Sorry, i was wanted to tell you about click on cancel button.

**Comment by artyomLisovskij** [comment]
@Wixely click cancel button and function which goanna exec only on success will exec.

**Comment by Wixely** [comment]
I see that it shows the success dialogue, but it doesnt actually execute the console.log function that is protected inside the (inputValue!=false) statement. Anyway, I've added another (inputValue!=false) statement for the first dialogue, see if that fixes the problem for you :)

**Comment by sri984** [comment]
i want to use multiple inputs as a password recovery method in my project, i created multiple fields using the  "html", now i want to get the values from these fields and check against the database for their validity , if the given username exists i want to prompt the user his password, can someone help me out?

**Comment by t4t5** [comment]
This can now be done using SweetAlert 2.0's new [content option](https://sweetalert.js.org/docs/#content)
