### ISSUE TITLE
Show alert, success and close in 2 seconds.

### ISSUE THREAD

**Issue by amucino** [t4t5/sweetalert#416]
I have a form with a form that updates information. 
I am adding a button to call sweet alert when the information is saved. 

There are two problems with this code:
```

-- button code--

 <button type="submit" class="btn btn-primary btn-sm1" >Save changes</button>

-- script code-- 

 $(document).ready(function () {
             $('.btn-sm1').click(function () {                
                 swal("Sucess!", "Information saved!", "success") 
			 });
       }); 

```

The problem is that the alert closes right away, does not even wait for user to click "OK". As soon as the page redirects after saving. So there is no chance for user to read the confirmation. I could not find a way to add a timer to this alert. So it closes 2 seconds later. 

And the second thing I want to remove the "OK" button. So it closes with the timer and user doesn't have to click to close.

Help is appreciated.

**Comment by amucino** [comment]
Please let me know if you need more information.

**Comment by ehzhang** [comment]
Assuming your button is in a `<form>` element and you're using a default HTML5 form action, it may be trying to 'submit' the form by default, and reload or redirect the page.

If you change the code to this:
```

 $(document).ready(function () {
             $('.btn-sm1').click(function (event) {
                
                 swal("Sucess!", "Information saved!", "success") 
             });
       }); 
```

**Comment by amucino** [comment]
Edwin, this is the code for the form I am submitting:

<form name="form1" action="<%=MM_editAction%>" method="POST" class="form-horizontal" id="form1">

and this is my button:
<button type="submit" class="btn btn-primary btn-sm1" >Save changes</button>

The alert does come up but only for a fraction of a second, then it closes and the page is refreshed. There is no delay that will show the alert for 2 seconds before it closes, giving user time to read it and time for the success icon to do the animation.

**Comment by amucino** [comment]
Any ideas ?
