### ISSUE TITLE
sweetalert with webpack

### ISSUE THREAD

**Issue by lichunqiang** [t4t5/sweetalert#417]
Hi

when work with webpack, (sweetalert had installed via npm), there is a warning:

```
WARNING in ./~/sweetalert/dist/sweetalert.js
Critical dependencies:
4:115-122 This seems to be a pre-built javascript file. Though this is possible
 it's not recommended. Try to require the original source to get better results

 @ ./~/sweetalert/dist/sweetalert.js 4:115-122
```

**Comment by adamrneary** [comment]
We are seeing this, as well. It might relate to adding some combination of transforms a la http://dontkry.com/posts/code/browserify-and-the-universal-module-definition.html.

**Comment by tw0517tw** [comment]
I got this warning, too.

**Comment by chentsulin** [comment]
We should use `babel` to build a `lib` folder as `commonjs` entry point.

**Comment by chiedojohn** [comment]
Any update on this? I'm also getting that warning.
