### ISSUE TITLE
Confusing SweetAlert2 clone

### ISSUE THREAD

**Issue by jrean** [t4t5/sweetalert#418]
Hi,

As we all know you are the "original" it could be useful to add a note somewhere saying you are..

It is very confusing to find this "fork/clone/copy" tagged as **2**.
https://limonte.github.io/sweetalert2/

Even in Google it is coming in third position.
https://www.google.com/search?q=sweet+alert&oq=sweet+alert&aqs=chrome.0.69i59j69i60l2.2330j0j1&sourceid=chrome&es_sm=119&ie=UTF-8

J.

**Comment by KillerSquid** [comment]
Yeah- I can't believe that asshole even stole the source-code for the website.
Avoid SW2 at all costs, people.  Stick with the original.

**Comment by saada** [comment]
https://github.com/limonte/sweetalert2/issues/29

**Comment by alexsandro-xpt** [comment]
So, whats is orginal and trustworthy?

**Comment by t4t5** [comment]
Even though it's a bit confusing that the fork is called this now that [SweetAlert 2.0](https://sweetalert.js.org) is out, people are free to do anything they want with this library since it's MIT. :)
