### ISSUE TITLE
Can't display umlauts

### ISSUE THREAD

**Issue by tidet** [t4t5/sweetalert#419]
Hey,
I wan't to use your sweetalert-Script (which is very very nice by the way) in a German Web-Application... but I don't get it work with umlauts - even not with HTML entities &uuml; for example.

![screen](https://cloud.githubusercontent.com/assets/12529017/9084059/f7541774-3b6f-11e5-9e39-881267eac55c.PNG)

I'm using it within an jQuery Script to ensure is the Ajax Call really be fired.

![ajax](https://cloud.githubusercontent.com/assets/12529017/9084091/29301626-3b70-11e5-88b7-84ed8c724ad0.PNG)

Thank you for helping me :)

**Comment by t4t5** [comment]
Hi @tidet! Are you sure it's not a problem with PHP? Have you tried echoing the same string straight into the HTML page?

**Comment by tidet** [comment]
Hey @t4t5 - yes at this part there's no PHP Output.. PHP is just down in the AJAX Call. I've tried it anyway, with PHP (without alert) it works, yes.

**Comment by t4t5** [comment]
@tidet Oh sorry, I misread the code. :)

Alright then, have you added the UTF8 charset to your header?
```html
<head>
<meta charset="UTF-8">
</head>
```

**Comment by tidet** [comment]
Hey, yes it's UTF-8.

**Comment by t4t5** [comment]
@tidet Hmm, weird. I honestly don't know what it could be then. I tried creating a JSFiddle with the same special characters and it seems to work fine: http://jsfiddle.net/t4t5/51mazdub/1/

**Comment by tidet** [comment]
ah f*ck... a hint on stackoverflow leads me to the answer... the file itself was saved in ANSI instead of UTF-8... now it works. sorry and thank you for this very fast reply!

**Comment by t4t5** [comment]
No problem, glad it got solved!

**Comment by n1lt0n** [comment]
> ah f*ck... a hint on stackoverflow leads me to the answer... the file itself was saved in ANSI instead of UTF-8... now it works. sorry and thank you for this very fast reply!

I've to thank you, because I was going crazy with the same issue, and I found your message here, thanks friend!!!!

**Comment by rmed1na** [comment]
> ah f*ck... a hint on stackoverflow leads me to the answer... the file itself was saved in ANSI instead of UTF-8... now it works. sorry and thank you for this very fast reply!

Thanks for sharing. Saved me hours of debugging as well.
