### ISSUE TITLE
Does this work in IE Compatibility mode?

### ISSUE THREAD

**Issue by danrovito** [t4t5/sweetalert#422]
I am using this in an app, but the app is forced to compatibility mode in IE.  When in that mode, it says swal is not defined

**Comment by dhenson02** [comment]
what level of compatibility?  IE ...8/9/10...other...?

If it's 8 or lower, support was dropped at 1.0.0 beta 4 as it says in the README.

Also check your !DOCTYPE for XHTML 1.0 strict - if this is set, make sure your `<script>` tag has the `type="text/javascript"` in it.

**Comment by t4t5** [comment]
Old IE version are no longer supported as of 2.0.
