### ISSUE TITLE
Dist without min.css?

### ISSUE THREAD

**Issue by rafael-renan-pacheco** [t4t5/sweetalert#423]
Any plans to provide a minified css in the dist folder?

**Comment by acedesigns** [comment]
@rafael-renan-pacheco 

I think you can use some of the  [online css compressors](http://csscompressor.com/) alternatively

In your project you can use [Gulp](https://github.com/murphydanger/gulp-minify-css) or [Grunt](https://github.com/gruntjs/grunt-contrib-cssmin)

**Comment by rafael-renan-pacheco** [comment]
cc @t4t5
