### ISSUE TITLE
getTopMargin() calc margin-top has some mistake make sweet-alert not vertical middle

### ISSUE THREAD

**Issue by ghost** [t4t5/sweetalert#426]
file: dev/modules/handle-dom.js 
line: 71-80
The padding value should be not add. Because elem.clientHeight include padding.

**Comment by coppolaemilio** [comment]
I'm also having issues with the vertical alignment. Why not using transform: translate?

**Comment by SolidDev** [comment]
Fix: Within getTopMargin(): After padding is defined with the if statement, add something like:

if (!padding)
    padding = 0;

**Comment by t4t5** [comment]
SweetAlert 2.0 should now be correctly positioned!
