### ISSUE TITLE
showConfirmButton: false not working 

### ISSUE THREAD

**Issue by jsanders67** [t4t5/sweetalert#428]
Currently my showConfirmButton: false is not working with this basic code in my application:

```
<button id="button-swal" class="btn btn-primary">Sweet Alert</button>

<script>
  $('#button-swal').on('click', function() {
    swal({
      title: "Sweet",
      text: "Alert",
      showConfirmButton: false,
      timer: 2000
    });
  });
</script>
```

I am in a rails project and using the sweet-alert gem and the sweet-alert-confirm gem as well along with bootstrap

**Comment by jsanders67** [comment]
If anyone else is experiencing this issue just use sweetalert2

**Comment by t4t5** [comment]
In SweetAlert 2.0 you can now use `button: false` for a more bug-free experience :)
