### ISSUE TITLE
When the swal's Text is a HTML's input,can't input any words.

### ISSUE THREAD

**Issue by Tokumicn** [t4t5/sweetalert#429]
Thanks your share !
## Code:

swal({
                    title: "Password",
                    allowOutsideClick: "false",
                    text: '<div class="form-group">' +
                              '<input type="password" class="form-control" id="password" name="password" placeholder="Password">' +
                          '</div>',
                    showCancelButton: true,
                    confirmButtonColor: "#007AFF",
                    confirmButtonText: "OK",
                    closeOnConfirm: false,
                    html: true
                }, function (isconfirm) {
                    if (isconfirm) {
                        alert("Pwd");
                    }
                });
## Q:

 IE Browser and Firefox Browser  can input words , but Google Chrome Browser can't input any words.What to do to improve this situation?

**Comment by gremz** [comment]
Where is the input? I don't see that enabled in your configuration?

**Comment by t4t5** [comment]
Not sure what's happening here, but it sounds like you might want to use the new `content` option in SweetAlert 2.0: https://sweetalert.js.org/docs/#content
