### ISSUE TITLE
Form Support

### ISSUE THREAD

**Issue by ElegantScripting** [t4t5/sweetalert#432]
Using the prompt feature is OK for a single question, but completing entire forms with just one text-input is a real hassle for the end-user.

Can you add form support for SweetAlert popups? Things like SweetAlert radio buttons, checkboxes, and multiple inputs, customizable as JS objects?

**Comment by stephenbaidu** [comment]
+1

**Comment by sentiasa** [comment]
+1

**Comment by ElegantScripting** [comment]
Bump.

**Comment by saada** [comment]
+1

**Comment by sergomet** [comment]
+1

**Comment by henryg0mez** [comment]
+1

**Comment by ElegantScripting** [comment]
@t4t5

**Comment by ElegantScripting** [comment]
Bump.

**Comment by sudhindrapc** [comment]
+1

**Comment by ElegantScripting** [comment]
Ideally the alert could cover multiple inputs in one.

However, if that's asking too much, the next best option would be to have buttons that guide the user through a multi-step process. Each alert would have a "next" button that when clicked animates the old part of the form out, and the next part of the form in.

Similar to a swipe on an iPhone home screen, except with fades.

**Comment by izwick-schachter** [comment]
+1

**Comment by cyberpirate92** [comment]
+1

**Comment by mrsimpson** [comment]
+1

**Comment by Lindsayanng** [comment]
+1 on this as well please!

**Comment by t4t5** [comment]
Sweetlert 2.0 now comes with a handy [content option](https://sweetalert.js.org/docs/#content) which lets you add any custom DOM node!
