### ISSUE TITLE
Looping through multiple Alerts not working will only initialises once..

### ISSUE THREAD

**Issue by JohnRSim** [t4t5/sweetalert#433]
``` javascript
var x = 0;
for (x;x<3;x++) {
    sweetAlert("Oops...", "Something went wrong!", "error");
}
```

This will only initiate the alert once - 
expected result to initiate alert 3 times like this - 

``` javascript
var x = 0;
for (x;x<3;x++) {
    alert('Oops - Something went wrong!');
}
```

**Comment by gremz** [comment]
After the first call to sweetAlert(), the future calls will only update the existing sweetalert DOM element. This means there will be no fading in/out. Are you looking for a different effect perhaps?

**Comment by Stefany93** [comment]
I have the same issue, it would only appear once. Even when called without a function a couple of times, it will only appear once.

**Comment by gremz** [comment]
@t4t5 maybe a queue could be added to more closely replicate the native alert?

**Comment by limonte** [comment]
[SweetAlert2](https://github.com/limonte/sweetalert2) supports modals queue: https://limonte.github.io/sweetalert2/#chaining-modals

**Comment by t4t5** [comment]
This can be done in an easier way in 2.0 using [promises](https://sweetalert.js.org/guides/#using-promises)

**Comment by limonte** [comment]
> https://limonte.github.io/sweetalert2/#chaining-modals

this link is outdated, here's the correct one https://sweetalert2.github.io/#chaining-modals
