### ISSUE TITLE
Button Position

### ISSUE THREAD

**Issue by GabrielSt** [t4t5/sweetalert#434]
Is there any way to change position of confirm and cancel buttons?

**Comment by gremz** [comment]
Currently there isn't a way via configuration. You could rearrange a bit through CSS. The downsides are possible breakage when you update, and possible clutter of css trying to cover all breakpoints.

**Comment by xiaody** [comment]
The overwriting CSS could be like
```
.sa-button-container {
  display: -webkit-flex;
  display: flex;
  -webkit-justify-content: center;
          justify-content: center;
}
.sa-button-container .cancel {
    -webkit-order: 2;
            order: 2;
}
.sa-button-container .sa-confirm-button-container {
    -webkit-order: 1;
            order: 1;
}
```

**Comment by hraynaud** [comment]
@gremz I had the same issue. I looked in the source to see if I customize but couldn't find a non hacky way to custom the plugin itself. So I settled for a hacky way in my own code :-) If you are using jquery something like this works fine.

    function swapModalButtons(){
      $("button.cancel").before($("button.confirm"))
    }

**Comment by luhaining** [comment]
src:modules/injected-html.js line:53 u will see what u want, that's why u can't set it's order.
modify:sweetalert.min.js
find <button class="cancel" tabIndex="2">Cancel</button>, remove it's position, it's work.

**Comment by JustinCheong** [comment]
what did ghost mean by 
`find <button class="cancel" tabIndex="2">Cancel</button>, remove it's position, it's work.`

Remove what position?

**Comment by ryanmortier** [comment]
You guys should be using this fork by now: https://limonte.github.io/sweetalert2/

It's actually updated and it has a reverse button option.

**Comment by michaelcashe** [comment]
@ryanmortier I'm on a big project and I would have to go through a lot of red tape to use sweetalert2
@ghost  I've edited the injected-html.js and changed the order... I've attempted to change sweetalert.min.js.  That's a pretty messy job. I can't tell if I did it correctly or not. The buttons still haven't reversed.  What's the best way to edit a min file?

**Comment by t4t5** [comment]
This can now be done in 2.0 using:

```javascript
swal({ 
  buttons: { 
    confirm: true, 
    cancel: true,
  }
})
```

...to set the exact order!

**Comment by limonte** [comment]
> You guys should be using this fork by now: https://limonte.github.io/sweetalert2/

this link is outdated, here's the correct one https://sweetalert2.github.io/

**Comment by felipeoliveirar** [comment]
Hi. I had the same problem. And solve with this work arround. Go to the .min and look for:
div class="sa-button-container">\n  
    <button class="confirm btn btn-lg" tabIndex="2">Confirmar</button>\n      <div class="sa-confirm-button-container">\n        <button class="cancel btn btn-lg" tabIndex="1">Cancelar</button> 

and change the confirm to cancel and cancel to confirm. and it is done.
