### ISSUE TITLE
isConfirm arg breaks when buttons go from stacked to horizontal

### ISSUE THREAD

**Issue by lorensr** [t4t5/sweetalert#437]
``` coffeescript
swal 
  showCancelButton: yes
, (isConfirm) ->
  console.log isConfirm
```

Prints `true` when clicking cancel, when the screen is such a size that mousedown (which shrinks the button) causes the buttons to become one row (after which mouseup is over the confirm button).

![image](https://cloud.githubusercontent.com/assets/251288/9595620/9409c390-5036-11e5-831c-b6d2787baef3.png)

![image](https://cloud.githubusercontent.com/assets/251288/9595693/8c963200-5037-11e5-9531-353120e4b9fa.png)

**Comment by t4t5** [comment]
This should be fixed in 2.0.
