### ISSUE TITLE
swal works like confirm("") javascript

### ISSUE THREAD

**Issue by hebrao** [t4t5/sweetalert#438]
Hello!

Is there any way to create a javascript function to make swal work like confirm?
I would like to click a button and wait until user click YES or NO to continue postback (asp.net).
Tks!

**Comment by craigsheen** [comment]
https://www.ludu.co/lesson/how-to-use-sweetalert#ember1310

**Comment by andrewBalekha** [comment]
You should provide callbackfunction/doneFunction
```javascript
function(isConfirm){
    if (isConfirm){
      swal("Deleted!", "Your imaginary file has been deleted!", "success");
    } else {
      swal("Cancelled", "Your imaginary file is safe :)", "error");
    }
});
```

**Comment by mylastore** [comment]
this does not work for me it always goes to isConfirm even if I press cancel button.
`  swal({
    title: "Are you sure?",
    text: "You will not be able to recover this imaginary file!",
    type: "warning",
    showCancelButton: true,
    confirmButtonColor: '#DD6B55',
    confirmButtonText: 'Yes, I am sure!',
    cancelButtonText: "No, cancel it!"
  }).then(function(isConfirm) {
    if (isConfirm) {
      console.log('isConfirm', isConfirm);
      $.ajax({
        url:  "/admin/delete-booking/" + bookingId,
        type: "GET"
      }).done(function(data) {
        swal({
          title: "Deleted",
          text: "Member has been successfully deleted",
          type: "success"
        },function() {
          location.reload();
        });
      })
        .error(function(data) {
          console.log(data);
          swal("Oops", "We couldn't connect to the server!", "error");
        });

    } else {
      console.log('got to else');
      swal("Cancelled", "Your imaginary file is safe :)", "error");
    }
  })`
