### ISSUE TITLE
php redirect after swal

### ISSUE THREAD

**Issue by lucafrassineti** [t4t5/sweetalert#441]
I'm trying to set sweetalert before automatic redirect on login if the user is not logged, but it appear just a second and redirect start immediately, how can i set to wait user click?

my actual code:
```
if ($_SESSION[logged] != 'yes') { 
echo '
<script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>
<link rel="stylesheet" href="stylesheets/sweetalert.css">
<script src="javascripts/custom/sweetalert.min.js"></script>
<script>
$( document ).ready(function() {
	swal("Oops...", "Not logged!", "error");
	document.location.href="/login.html"
});
</script>';
exit; 
```

**Comment by andrewBalekha** [comment]
if ($_SESSION[logged] != 'yes') { 
echo '
<script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>
<link rel="stylesheet" href="stylesheets/sweetalert.css">
<script src="javascripts/custom/sweetalert.min.js"></script>
<script>
$( document ).ready(function() {
    swal({}, function() {
});
    document.location.href="/login.html"
});
</script>';
exit;

**Comment by lucafrassineti** [comment]
I solved with this thank you!

```
if ($_SESSION[logged] != 'yes') { 
echo '
<script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>
<link rel="stylesheet" href="stylesheets/sweetalert2.css">
<script src="javascripts/custom/sweetalert2.min.js"></script>
<script>
$( document ).ready(function() {
	swal({
         title: 'Oops..',
       text: 'Not logged!',
       type: 'error',
}, function(isConfirm) {
     document.location.href="/login.html"
});
});
</script>';
exit; 
};
```

**Comment by pocapratica** [comment]
How can I call the swal function without jQuery?
