### ISSUE TITLE
swal.dissableButtons()

### ISSUE THREAD

**Issue by Rapso** [t4t5/sweetalert#443]
function swal.dissableButtons() does not work at all, i can still click confirm button twice or more

swal({
                title : 'title',
                text : 'text',
                type : 'warning',
                showCancelButton : true,
                confirmButtonText : 'y',
                cancelButtonText : 'n',
                closeOnConfirm : true,
                closeOnCancel : true
            }, function(isConfirm) {
                swal.disableButtons();
                if (isConfirm) {
                    confirmed();
                } else {
                    canceled();
                }
            });
        };

**Comment by andrewBalekha** [comment]
As far as I understand you should use it like this
```javascript
swal({
        title: 'title',
        text: 'text',
        type: 'warning',
        showCancelButton: true,
        confirmButtonText: 'y',
        cancelButtonText: 'n',
        closeOnConfirm: true,
        closeOnCancel: true
      }, function(isConfirm) {
        if (isConfirm) {
          confirmed();
        } else {
          canceled();
        }
      });
      swal.disableButtons();
```

**Comment by jlgasparrini** [comment]
`swal.dissableButtons()` isn't available...

```Uncaught TypeError: swal.disableButtons is not a function``` in the js console.

**Comment by t4t5** [comment]
The easiest way to do this in SweetAlert 2.0 is probably just pure JS:

```javascript
document.querySelector('.swal-button').disabled = true
```
