### ISSUE TITLE
How to change sweetalert text?

### ISSUE THREAD

**Issue by Malavos** [t4t5/sweetalert#444]
Suppose I have this block of code here:

```
 swal({   title: "Confirm delete",
     text: "Do you want to delete these files?", 
     type: "info",   showCancelButton: true,
     closeOnConfirm: false,
     showLoaderOnConfirm: true, },
     function(){
        setTimeout(function(){
            swal("Ajax request finished!");   }
        , 2000); 
     });
```

(this is taken from the example).

And I wanted to do, at the click of the Ok button, to change the text of the alert. How can I manage to do so?

**Comment by t4t5** [comment]
You can use jQuery's `text()`-method: http://api.jquery.com/text/

**Comment by kagan94** [comment]
For the button texts you can you "buttons" param:
`buttons: ["Your text for NO btn", "Your text for YES btn"],`
