### ISSUE TITLE
Foundation Fieldset Issue

### ISSUE THREAD

**Issue by masonfox** [t4t5/sweetalert#445]
A fieldset is injected every time an alert is launched. I know it is not a fault in the javascript as I have even used a single title and it still pops up. It looks like it is coming from foundation, but I still can't find it. Let me know if anyone else has run into this and found a solution. Much appreciated.

<img width="1280" alt="screen shot 2015-09-09 at 1 36 57 pm" src="https://cloud.githubusercontent.com/assets/13393712/9769430/2a0f27be-56f8-11e5-98ec-358248673711.png">

**Comment by jbrooksuk** [comment]
The fieldset is part of the sweetalert Javascript code, it just looks to get its formatting from Foundation. I just added:

```scss
.sweet-alert fieldset {
    margin: 0;
    padding: 0;
}
```

To my SCSS file.

**Comment by t4t5** [comment]
Fixed in 2.0 since it no longer adds hidden input fields by default.
