### ISSUE TITLE
Animation property not working

### ISSUE THREAD

**Issue by ipolevoy** [t4t5/sweetalert#448]
No matter what value I set animation property to, the behavior does not change. The modal double-pops in the middle of screen. Am I doing something wrong? 

```JavaScript
swal({
    title: "Are you sure?",
    text: "You will not be able to recover this imaginary file!",
    type: "error",
    animation: "slide-from-top",
    showCancelButton: true,
    confirmButtonText: "Yes, delete it!",
}, function () {
    console.log("Delete was pressed!");
});
```

**Comment by gremz** [comment]
What values have you tried changing the animation property to? slide-from-top seems to work just fine in a fiddle http://jsfiddle.net/wgqtoLzb/. You can use pop, none, slide-from-top, slide-from-bottom.

**Comment by ipolevoy** [comment]
ok, this works, but to be fair, I'm using http://lipis.github.io/bootstrap-sweetalert/. 
Closing this  issue, as I will investigate  locally
