### ISSUE TITLE
Content flickers toggling the scroll bar

### ISSUE THREAD

**Issue by UGAROY** [t4t5/sweetalert#449]
In the current workflow, the "overflow:hidden" is applied when an alert box is opened.

It is not elegant to have a scrollbar there, but it is also quite annoying, visually, that the content behind jump back and forth.

See an example here: http://screencast.com/t/2380qe3S9B

**Comment by JamoCA** [comment]
I was hoping to search the issues section for a resolution to this visual annoyance.

A potential CSS orverride was suggest here, but others are still opening and reporting it as a new issue using different language:
https://github.com/t4t5/sweetalert/issues/362#issuecomment-128113814

**Comment by rafael-renan-pacheco** [comment]
Consider migrate you project to [sweetalert2](https://github.com/limonte/sweetalert2)

This problem, and many others, does not exists there.

**Comment by t4t5** [comment]
This shouldn't happen anymore in 2.0
