### ISSUE TITLE
Not displaying properly - iFrame woes perhaps?

### ISSUE THREAD

**Issue by ghost** [t4t5/sweetalert#452]
I have a page which essentially gives the entire screen over to an iframe.
The page (the parent document, or the top document if you prefer, though there are only two levels - parent and iframe) can use swal just fine.

The iframe tries to use swal and fails. It's hard to describe the error, and I am just guessing that it is because swal is running in an iframe.

It appears that everything swal creates is under the iframe (in terms of z-index). iframe content is pushed up from the bottom of the page just a little.

I've grabbed a screen shot of the bottom of the page in question.
The dark gray section touches the bottom of the page before swal is called.

![forswal](https://cloud.githubusercontent.com/assets/9857137/10142098/c995a3ba-65cd-11e5-86aa-9c647fa25f49.png)

This is on firefox. If I go into firebug and make the largest div (id="foundation") in the iframe display: none, i get the following:

![forswal2](https://cloud.githubusercontent.com/assets/9857137/10142183/511143c6-65ce-11e5-8d9f-8a8ff447ed12.png)

And finally if I manually change the margin-top from its current -73px to 200px on the main sweet-alert div (not sweet-overlay) then I see the following:

![forswal3](https://cloud.githubusercontent.com/assets/9857137/10142295/142d2744-65cf-11e5-88ea-eace7c1320e6.png)

I'm open to suggestion. The tool looks fun and very useful. I'd love to get away from alert or hand-coded overlay layers.

Yishmeray

p.s. - forgot to give the call. I had been using various others but settled on one out of the examples:
swal({
  title: "Error!",
  text: "Here's my error message!",
  confirmButtonText: "Cool"
});

p.p.s. - I tried a little work-around pending input from author or contributor - at the invocation in the sweetalert-dev.js file, I changed 'document' to 'parent.document ? parent.document : document' which seems to have done the trick.

Would this be an acceptable approach? What say you?

**Comment by rafaelhdr** [comment]
I had the same problem here (in iframe)
Solved with @ghost help

Edited the last `document` to `parent.document`

**Comment by t4t5** [comment]
Seems like iFrame issues can be resolved with @rafaelhdr's method. Closing for now :)
