### ISSUE TITLE
Small "glitch" lines where sa-fix is for success on Chrome/Win8

### ISSUE THREAD

**Issue by BenWoodford** [t4t5/sweetalert#455]
[Here's a shot of it](http://i.imgur.com/70KgoOu.png)

I'm trying to use it on a dark background, which was going swimmingly till I got to this. it seems to be present on the demo page as well, but it's a lot less noticeable on a white background than a dark one.

Has anyone got any suggestions on how I can get rid of this? There's no borders or anything like that which could be causing it, I assume it's a rendering glitch which doesn't fill me with hope for a fix.

**Comment by t4t5** [comment]
Sorry for the delay. Will continue conversation in the duplicate issue #712.
