### ISSUE TITLE
swal form validation before submit

### ISSUE THREAD

**Issue by henryg0mez** [t4t5/sweetalert#456]
Hello SweetAlert creator,

I first of all want to congratulate on developing a beautiful and easy to use pop-up script.

For the past week I have tried to use Swal and jquery form validation examples to validate input before submitting a form and I have reached a big brick wall and need to reach out for  help.

I have a swal pop-up on my website (http://plantswap.com.au) that appears when you click on "Tell a friend" button. The SWAL componnent works fine, but it submits the form even if I haven't entered any input. Also, I am not sure that anything actually happens on submit. When submit is clicked, a php file is called through AJAX that should send an email. 

Here is the javaScript in my header.php file:

-->

```
    <script>

         document.querySelector('div.sweetpop1 button.tell').onclick = function(e){
         e.preventDefault();
            swal({
                title: "Tell your friends!",
                text: '<form role="form" id="contact-form" method="post"><div class="control-group"><label for="friend_name">Your friend\'s name</label><input type="text" placeholder="Your friend\'s full name" id="friend_name" name="friend_name" required></div><div class="control-group"><label for="email">Email</label><input type="email" placeholder="Your friend\'s Email" id="email" name="email" required></div></form>',
                html: true,
                showCancelButton: true,
                showConfirmButton: true,
                confirmButtonText: "Submit",
                function( confirmed ) {
                        if( confirmed )
                            $(this).closest('form').submit();
                }
                });
            };


    $('#contact-form').on('submit', function(e){
        e.preventDefault();
        var myForm = $("#contact-form");
        if(myForm.valid()){

            var theData = {
                 friend_name: $('#friend_name').val(),
                 email: $('#email').val(),

            };

            $.ajax({ // ajax call starts
                url: "http://plantswap.com.au/wp-content/themes/flatads/tell_a_friend.php",
                type: 'post',
                data: theData,
                success: function(data)
                {
                    swal("Your request has been received!", "We will contact you for confirmation soon", "success");
                    document.getElementById('friend_name').value='',
                    document.getElementById('email').value='';

                }

            });
        }
    });
```

</script>

if you test this, you will see the swal pops up but the validation does not work. I even tried using the tramero SWAL addition (swal.forms) but the alignment and horizontal and vertical scroll bars were all wrong, so I gave up on that.

Can you please help me modify the above source code to get the form validation working, as well as follow through on the submit so the parameters are passed to my PHP file via the submit POST?

Thanks in advance.

Kind regards,
Henry

**Comment by henryg0mez** [comment]
I would also like to add that I tried using some "rules/messages" jquery validation as below but this didn't work at all:

-->

     $("#contact-form").validate({

				errorElement: "label", // default is 'label'
				errorPlacement: function(error, element) {
				error.insertAfter(element);
			},

         // Specify the validation rules
         rules: {
             friend_name: "required",
             email: required
         },

         // Specify the validation error messages
         messages: {
             friend_name: '<i class="fa fa-exclamation-circle rediconcolour"></i> ' + " Poor friend!! IThey has no name!! " + ' <i class="fa fa-exclamation-circle rediconcolour"></i> ',
             email: '<i class="fa fa-exclamation-circle rediconcolour"></i> ' + " Email is required. " + ' <i class="fa fa-exclamation-circle rediconcolour"></i> ',
         },
			submitHandler: function(form) {

			swal({
			  	 		title: "Confirm Plant Ad submission",
			  	 		text: "You are about to submit this Plant Ad. Do you wish to proceed?",
			  	 		type: "warning",
			  	 		showCancelButton: true,
			  	 		confirmButtonColor: "#DD6B55",
			  	 		confirmButtonText: "Yes, let's Plantswap!",
			  	 		cancelButtonText: "No, I changed my mind",
			  	 		closeOnConfirm: false,
			  	 		allowOutsideClick: true },
			  	 		function(){   swal("Success!", "Your Ad was successfully submitted for approval!", "success");
			  	 							form.submit();

			  	 		}
			  );
		}

<--

**Comment by henryg0mez** [comment]
Anyone??? Tristan Edwards???

**Comment by t4t5** [comment]
@henryg0mez So if I understand things correctly, the problem is that your form gets submitted even though you haven't entered any input? 

Is this really a problem with SweetAlert? Keep in mind that the only recommended way to handle user inputs through swal is by using `type: input`. Everything else with custom HTML should be considered a "hack".

If your form submits even though it's empty, I can only guess that the problem lies within the  `myForm.valid()`-function.

And when it comes to "I am not sure that anything actually happens on submit. When submit is clicked, a php file is called through AJAX that should send an email", well, you should be able to just log your stuff in the PHP console to check if it went through or not. Can't really help you anymore than this. :)

**Comment by henryg0mez** [comment]
@t4t5 - yes, the email did submit at first until I modified the code in an attempt to stop the send function if nothing was typed in the fields.

Surely there has to be a way to stop SweetAlert from submitting the form and verify there are actually valid values entered in the fields? I would really like to get form validation working on Swal. Otherwise I am looking at using Wordpress' Contact Form 7 with pop-up as a work around.

**Comment by henryg0mez** [comment]
Here is my latest attempt at form validation in Swal:

		     document.querySelector('div.sweetpop1 button.tell').onclick = function(e){
		     e.preventDefault();
				swal({
					title: "Tell your friends!",
					text: '<form role="form" id="contact-form" method="post"><div class="control-group"><label for="friend_name">Your friend\'s name</label><input type="text" placeholder="Your friend\'s full name" id="friend_name" name="friend_name" required></div><div class="control-group"><label for="email">Email</label><input type="email" placeholder="Your friend\'s Email" id="email" name="email" required></div></form>',
					html: true,
					showCancelButton: true,
					showConfirmButton: true,
					confirmButtonText: "Submit"
					},
					function (isConfirm) {
        			if (isConfirm) {

					     // Setup form validation on the #primaryPostForm element
					     $("#contact-form").validate({

									errorElement: "label", // default is 'label'
									errorPlacement: function(error, element) {
									error.insertAfter(element);
								},

					         // Specify the validation rules
					         rules: {
					             friend_name: {
					             	required: true,
					             	minlength: 3
					             	},
					             email: {
									 required: true,
									 email: true
					             }
					         },

					         // Specify the validation error messages
					         messages: {
					             friend_name: '<i class="fa fa-exclamation-circle rediconcolour"></i> ' + " Poor friend!! They have no name!! " + ' <i class="fa fa-exclamation-circle rediconcolour"></i> ',
					             email: '<i class="fa fa-exclamation-circle rediconcolour"></i> ' + " It is useful to include their email address... " + ' <i class="fa fa-exclamation-circle rediconcolour"></i> '
					         }

   						}); // end contact-form validate
				    }		// end if statement
					}); // end swal
				};

**Comment by grinsteindavid** [comment]
this is working for me

```
$('.swal-article-create').click(function(e, params) {
    var localParams = params || {};

    if (!localParams.send) {
      e.preventDefault();
    }

    swal({
        title: "Desea continuar?",
        text: "Se creara un nuevo articulo con la informacion proporcionada.",
        type: "warning",
        showCancelButton: true,
        confirmButtonColor: "#6A9944",
        confirmButtonText: "Confirmar",
        cancelButtonText: "Cancelar",
        closeOnConfirm: true
      },
      function(isConfirm) {
        if (isConfirm) {
          $(e.currentTarget).trigger(e.type, {'send': true});
        }
      }
    );
  });
```

**Comment by grinsteindavid** [comment]
The form will not submit the data if you have inputs with 'required' html attribute, and if your back-end check validations then will reload the page with html errors list

**Comment by eddyhoole** [comment]
This works:
`$('.swal-article-create').click(function(e, params) {
    var localParams = params || {};

    if (!localParams.send) {
      e.preventDefault();
    }

    swal({
        title: "Desea continuar?",
        text: "Se creara un nuevo articulo con la informacion proporcionada.",
        type: "warning",
        showCancelButton: true,
        confirmButtonColor: "#6A9944",
        confirmButtonText: "Confirmar",
        cancelButtonText: "Cancelar",
        closeOnConfirm: true
      },
      function(isConfirm) {
        if (isConfirm) {
          $(e.currentTarget).trigger(e.type, {'send': true});
        }
      }
    );
  });

` Just change the .click of button to .submit of the form and HTML validate will work.

**Comment by t4t5** [comment]
For advanced modal usage, I recommend the new [content option](https://sweetalert.js.org/docs/#content) introduced in SweetAlert 2.0

**Comment by MateusFGoncalves** [comment]
I had the same problem the other day, but you can use the **preConfirm** method of swalAlert, so in the end you return FALSE for the sweet does not close and only closes the SweetAlert with **swal.close ();** when you want... 

my example: 


```
    swal({
        title: 'Adicionar novo documento',
        html: $('<form id="documentos_paciente" enctype="multipart/form-data"></form>').html('\
                <div class="form-group">' +
                    '<label for="refente_familiar">REFERENTE:</label >' +                    
                    '<select name="refente_familiar" class="required form-control" required>' + 
                    '</select>' +
                    '<span class="help-errors">' +
                        '<strong></strong>' +
                    '</span>' +                    
                '</div>' 
                ),
        showCancelButton: true,
        cancelButtonText: 'Cancelar',
        confirmButtonText: 'Enviar',
        showCloseButton: true,
        allowOutsideClick: false,        
        preConfirm: () => {    
            
              
            //validate the front here if you wish (valid is the variable to say on the front is ok)
            var valid = true;
            
            //ENVIO DE DADOS PARA O SEERVIDOR
            if(valid)
            {
                var documentos_paciente_form = new FormData($('#documentos_paciente')[0]);                        
                valid = false;

                $.ajax({
                    url: '/admin/pacientes/adicionarDocumento/' + top.id_paciente,
                    type: 'post',
                    data: documentos_paciente_form,
                    processData: false, 
                    contentType: false,                
                        success: function (data)
                        {
                            if(data.status == 'success') 
                            {                                                                                                                     
                                swal.close();
                                
                                swal({
                                    title: 'Tudo ocorreu corretamente!',
                                    text: 'Documento adicionado com sucesso!',
                                    type: 'success'
                                });
                            }   
                            else 
                            {
                                valid = false;

                            }
                        },                        
                        error: function(data)
                        {          
                            //dealing with the error that came from the back end
                           if(data.status == '422')
                           {
                                var errors = data.responseJSON.errors;
                                
                                for(var error in errors)
                                {
                                         ///do as you please
                                }
                           }                         
                        }                        
                })       
            }  
            
            // This way the sweety does not date
            return false;
        }
    });    
```

If you do not understand, use the translator for a few words because it is in Brazilian
