### ISSUE TITLE
Page jumps to top when sweetalert is opened

### ISSUE THREAD

**Issue by caseyWebb** [t4t5/sweetalert#467]
Fix in PR #466

**Comment by pennstump** [comment]
I am having this same issue.

**Comment by sbolel** [comment]
Yep, me too

**Comment by dreyk213** [comment]
still actual +1

**Comment by azizk-araneux** [comment]
Same issue.

**Comment by t4t5** [comment]
Sorry for such a long delay. I believe the issue is fixed in [2.0](https://sweetalert.js.org/guides/#upgrading-from-1x). Please have a look!

**Comment by azizk-araneux** [comment]
@t4t5 Issue has been resolved. Thank you :)
