### ISSUE TITLE
Minifying sweetalert.css for Distribution

### ISSUE THREAD

**Issue by OrkanCom** [t4t5/sweetalert#476]
Hello,

Nice api you've got there. Thanks for sharing us.

We have one little problem; Can you minify "sweetalert.css" ? 
And maybe put the minified file to "../Dist/sweetalert.min.css" ?

( we are using our css/js minify & bundle system on production-side, but that's not the case. I think it could be nice if we had minified file of the css. )

Thanks, have a nice day...

**Comment by pbassut** [comment]
+1. Why this is not minified?
I thought it was because there's a 'dev' version. I figured that one would not be minified

**Comment by t4t5** [comment]
The CSS file has been removed in 2.0 and is now included (+ minified) in the JS file.
