### ISSUE TITLE
Using SA as a loading dialog

### ISSUE THREAD

**Issue by unclelarrysvan** [t4t5/sweetalert#477]
Is it possible to open SweetAlert straight into the loading animation?

**Comment by jannejava** [comment]
Ever found a solution to this?

**Comment by unclelarrysvan** [comment]
I did not, although, I didn't spend too much time looking into it.

**Comment by t4t5** [comment]
In the new 2.0 release, you can customise your SweetAlert to show anything you want using the the [content option](https://sweetalert.js.org/docs/#content). You could stick a loader element in there. :)
