### ISSUE TITLE
html doesn't seem to be working

### ISSUE THREAD

**Issue by deronsizemore** [t4t5/sweetalert#481]
Here's what I have:

    sweetAlert({html: true, allowOutsideClick: true, confirmButtonColor: "#53b5e6", title: "Oops...", text: "Something went wrong. Please try again or <a href="/contact">contact us</a> if you continue to have problems." , type: "error", confirmButtonText: "Try Again" });

In console, I'm just seeing: `Uncaught SyntaxError: Unexpected identifier` error. I'm sure this is probably an obvious thing here, but I can't seem to see it. Any ideas?

**Comment by wapacro** [comment]
You can't use double quotes inside a string.
Try this:
`sweetAlert({html: true, allowOutsideClick: true, confirmButtonColor: "#53b5e6", title: "Oops...", text: 'Something went wrong. Please try again or <a href="/contact">contact us</a> if you continue to have problems.', type: "error", confirmButtonText: "Try Again" });`

**Comment by deronsizemore** [comment]
Ah... well that's embarrassing. I don't claim to be an expert with javascript but I know enough to know better than that. :) Thanks.

**Comment by oneseral** [comment]
it's not worked.e.g:
![2345 20151211142304](https://cloud.githubusercontent.com/assets/8988730/11737295/ca5c1232-a012-11e5-894c-e7507d3be6fb.png)
