### ISSUE TITLE
selenium issues with sweetalert

### ISSUE THREAD

**Issue by estivalet** [t4t5/sweetalert#485]
Hi, I have a web application that uses this component and I'm responsible for the automated tests. I have an issue in an alert that confirms a exclusion of a record. Selenium runs too fast and when the alert popsup it clicks very fast in the "OK" button to confirm the deletion. But for some reason it seems that the function behind this button is not called and the record is not deleted.

If I add a delay in the execution it works as expected.

Has anybody experiencing this problem?

**Comment by luanmuniz** [comment]
Have you sync the moment that selenium do the `click` with the `DOMContentLoaded` event?
sweetAlert take some time to be fully loaded. You should wait until `DOMContentLoaded` (or `$(document).ready()`) is called to do anything.

**Comment by wubin1989** [comment]
@estivalet about 'If I add a delay in the execution it works as expected', would you like to tell me how to add the delay? I is encountering the problem these days, and I can not fix it. I am very glad to find that you have solution. Please kindly share it with me. Thank you!

**Comment by luanmuniz** [comment]
Maybe this can help you.
http://stackoverflow.com/questions/15122864/selenium-wait-until-document-is-ready
https://gist.github.com/double16/e3dfa7ec496264f11648

I use a selenium like and its javascript, so i have access to the javascript events.
Can you add a timer? Wait for a few seconds before executing the code. Try this and tell us if the problem still exist.

**Comment by sundling** [comment]
As far as I can see, by looking at the code, this is how this library is supposed to work.

sweetalert performs a 500ms fadeIn when opening the modal.
During this time the OK/Cancel buttons will not run the callback function, it will close the modal instead.
An unexpected/confusing behaviour according to me.

sweetalert will add the class `visible` when the animation has finished.

Using Capybara for testing you could use the following:
```
within ".sweet-alert.visible" do
  ...
end
```

**Comment by jsrn** [comment]
@sundling, you just saved me a real headache, thanks! :+1:

**Comment by Anjali05** [comment]
I am testing a web app that uses sweet alert. My automation framework is in selenium + Java + TestNG. The driver runs too fast to catch the alert and I am getting NoAlertPresentException. If I add wait, I get TimeoutException.
Has anyone come across this issue and is able to resolve it?

**Comment by stevetong83** [comment]
I got it to work this way.

```
within ".sweet-alert.visible" do
  find('button.confirm').trigger('click')
end
```

**Comment by t4t5** [comment]
Sorry for such a long delay. In SweetAlert 2.0, there should no longer be a delay for the buttons' actions. Please read the [upgrade guide](https://sweetalert.js.org/guides/#upgrading-from-1x)
