### ISSUE TITLE
Uncaught ReferenceError: logStr is not defined

### ISSUE THREAD

**Issue by gabyrusu** [t4t5/sweetalert#487]
Hey, guys! I'm using sweetalert 1.1.3 installed with npm and i keep getting this error: 

"Uncaught ReferenceError: logStr is not defined." in sweetalert-dev.js:1035

What could be the problem? Any ideas?

Thanks!

**Comment by maddy2308** [comment]
I did the same thing as mentioned by you and I am myself receiving the same errors. Don't know whats going wrong

**Comment by yoshiokatsuneo** [comment]
Maybe same as https://gist.github.com/ajitbohra/e0bb2f430894e62eaff4 ?

**Comment by gabyrusu** [comment]
yep, I was using danger instead of error.

**Comment by jmagnusson** [comment]
Though it does seem that `logStr` is not imported in [set-params](https://github.com/t4t5/sweetalert/blob/master/lib/modules/set-params.js). AFAIK this is not a global function.

**Comment by eddyhoole** [comment]
I have had the same issue , used danger instead of error as type.

**Comment by Acidic9** [comment]
This should be fixed.

**Comment by rcabral827** [comment]
i have the same error, sucess, but right is success.. Now is working

**Comment by t4t5** [comment]
`logStr` has been removed in 2.0 so this should no longer be an issue.

**Comment by kuez** [comment]
`            SweetAlert.swal(
              {
                title: "Process complete",
                text: "Your data will be confirmed, at a time a representative will contact you.",
                type: "Success", /** ----->> Check the first  letter, all must be lower case **/
                ///
              },
              function() {
               ///
              }
            );`
