### ISSUE TITLE
Uncaught Syntax Error: Unexpected Token (

### ISSUE THREAD

**Issue by deronsizemore** [t4t5/sweetalert#490]
$('.delete').click(function() {
	    sweetAlert({
		    html: true,
		    allowOutsideClick: true,
		    confirmButtonColor: "#53b5e6",
		    title: "You sure?",
		    text: "You're about to delete everything. Are you sure?",
		    type: "warning", confirmButtonText: "Do it!"
	    });

	    function(isConfirm) {
            /* ajax stuff to delete a thing */
	    });
    });

Any idea what I'm doing wrong here? I keep getting the unexpected token ( on this line:

`function(isConfirm) {`

**Comment by rafael-renan-pacheco** [comment]
Your `function(isConfirm)` is in the wrong place. It should be put as the second param:

```js
$('.delete').click(function() {
    sweetAlert({
        html: true,
        allowOutsideClick: true,
        confirmButtonColor: "#53b5e6",
        title: "You sure?",
        text: "You're about to delete everything. Are you sure?",
        type: "warning", confirmButtonText: "Do it!"
    }, function(isConfirm) {
        /* ajax stuff to delete a thing */
    });
});
```

**Comment by deronsizemore** [comment]
Well... that's embarrassing. I see it now in the example but not sure how I glossed over that earlier. I must have looked at it for an hour comparing to what I had. Thanks.
