### ISSUE TITLE
Drop Down focus input text field overlapping

### ISSUE THREAD

**Issue by jon9** [t4t5/sweetalert#491]
I'm having an issue where the drop down (focus) text input field shows on top of Sweet Alert popup. Sweet Alert already has z-Index set to 99999, however, the div is set to fixed.

See screenshot below. Does anyone have a fix for this issue? 

![screenshot_2015-12-09-20-21-22](https://cloud.githubusercontent.com/assets/7460310/11736125/0a8ff75c-9f90-11e5-9ae1-6a8fc510a7bb.png)

**Comment by t4t5** [comment]
This sounds like an issue of your app's CSS being too general. Please upgrade to [SweetAlert 2.0](https://sweetalert.js.org) if the problem persists!
