### ISSUE TITLE
Ability to check if modal is opened

### ISSUE THREAD

**Issue by fracz** [t4t5/sweetalert#493]
I.e.:

``` js
swal.isOpened()
```

Why? In order to check if we have something to close:

``` js
if (swal.isOpened()) {
  swal.close();
}
```

I know I can call the `swal.close()` even if there is no modal, but it [can cause problems](https://github.com/t4t5/sweetalert/issues/492).

Current workaround:

``` js
if ($(".sweet-alert.visible").length > 0) {
  swal.close();
}
```

**Comment by senseluo** [comment]
+1

**Comment by scorpionhiccup** [comment]
Is there any update on this issue?

**Comment by Zexorz** [comment]
as far i know, this repository is abandoned, but there's sweetalert2 on github which is a fork of this.

**Comment by scorpionhiccup** [comment]
thanks @Zexorz  will have a look

**Comment by t4t5** [comment]
In the new 2.0 release, you can use `swal.getState()` and then check whether the `isOpen` value is true or false. Make sure you read the [upgrade guide](https://sweetalert.js.org/guides/#upgrading-from-1x)!

**Comment by imightknoiw** [comment]
Use a check:
```javascript
if(swal){
  swal.close();
}
```
edit: \
i am aware this is a old issue

**Comment by luisvaldez** [comment]
Swal.getPopup() returns null if the popup is closed... Hope this helps.

**Comment by MuhammedBayat** [comment]
`Swal.isVisible()` use this code
