### ISSUE TITLE
What about cancelButtonColor?

### ISSUE THREAD

**Issue by ghost** [t4t5/sweetalert#496]
Are you able to add a parameter cancelButtonColor?

**Comment by fiote** [comment]
Hi @thomasmorelli. If you still need it, I just requested a pull with that.
https://github.com/t4t5/sweetalert/pull/499

**Comment by thomasmorelli** [comment]
@fiote Thank you!

**Comment by thomasmorelli** [comment]
@t4t5 are you able to accept the pull please?

**Comment by fracz** [comment]
+1

**Comment by t4t5** [comment]
I decided to take another approach.`confirmButtonColor` is now deprecated and both buttons can now be styled in CSS instead using the classes `.swal-button--confirm` and `.swal-button--cancel`. Make sure you read the [upgrade guide](https://sweetalert.js.org/guides/#upgrading-from-1x)!
