### ISSUE TITLE
Text in alert is getting cut off

### ISSUE THREAD

**Issue by nkalupahana** [t4t5/sweetalert#501]
When there is too much text passed into a SweetAlert, it will cut off the text instead of expanding the alert. Example:

![prompt](https://cloud.githubusercontent.com/assets/7347290/11910465/02800dd2-a5ac-11e5-9a46-0283bde2dbd4.png)

Is there is a CSS fix to this? Will you please fix it? Thanks!

**Comment by NeutronStar408** [comment]
I figured out what was happening. Because there is no space in front of the commas, the entire list of file names is taken as one word. However, this is still an issue. Could you please fix it as soon as possible? Thanks!

**Comment by t4t5** [comment]
This should be fixed in 2.0. Sorry for such a long delay.
