### ISSUE TITLE
When inputValue specifed, select in input box

### ISSUE THREAD

**Issue by mike-ward** [t4t5/sweetalert#503]
Feature request:

When `inputValue` is specified, the prompt dialog should appear with the input text selected so it can be easily typed over.

**Comment by yoshiokatsuneo** [comment]
Workaround: Run the following command after calling swal()...
```
$('.sweet-alert input').select();
```

**Comment by mike-ward** [comment]
I don't use jQuery but I see what you mean.

**Comment by t4t5** [comment]
I think @yoshiokatsuneo workaround is pretty good (but the class name in 2.0 is now `.swal-input`). In the new release, you can also customise the content more precisely using the new [content](https://sweetalert.js.org/docs/#content) option!
