### ISSUE TITLE
Alert window overflows screen on long message

### ISSUE THREAD

**Issue by electronicsguy** [t4t5/sweetalert#504]
first of all, congrats on this great utility! I tried using it with a really long message. The alert window height becomes so large that it overflows the screen and you cannot see the 'OK' or 'cancel' buttons anymore. Is there any way to restrict the alert dialog maximum height, and have the long text scroll inside it?

**Comment by rankill** [comment]
#521 it could be your solution

**Comment by t4t5** [comment]
In the new 2.0, the window should be scrollable if the modal is too long. :)
