### ISSUE TITLE
Is there a way to prevent popup to not close when the escape key is pressed.

### ISSUE THREAD

**Issue by yrshaikh** [t4t5/sweetalert#505]
I am using to show a loading message. And do not want the loader message to be closed by using the escape key.

**Comment by jasel-lewis** [comment]
yrshaikh -

Have you looked at the SweetAlert [documentation](http://t4t5.github.io/sweetalert/)?  Scroll down to the "Configuration" section and you'll see the allowEscapeKey argument (which defaults to _true_).  Pass _false _to it and you should get your desired behavior.
