### ISSUE TITLE
Error on close timing...

### ISSUE THREAD

**Issue by Zax** [t4t5/sweetalert#507]
If the callback function contains a second call to sweetalert
the second alert is shown but immediately closed, probably due to the fact that the closure of the first alert causes the closure of the second one.

Example of code:
swal({ title: 'first' }, function(){ swal('second') });

We cannot use the  {closeOnConfirm: false} option since when we call the first sweetalert in the way reported in the example we are not sure that we will have another sweetalert call on the callback.

ty

**Comment by malthejorgensen** [comment]
Because of the way the library is written right now you _do_ need to use the `closeOnConfirm: false` to do what you describing here.

**But**, to work around it you could delay the second modal a bit:

```
swal({
  title: 'first'
}, function(){
  setTimeout(function() {
    swal('second');
  , 600);
});
```

**Comment by t4t5** [comment]
In 2.0, you no longer need to use `closeOnConfirm: false`, so this can be closed. :)
