### ISSUE TITLE
How to convert it into a login popup with username and password fields

### ISSUE THREAD

**Issue by akkipatil** [t4t5/sweetalert#512]
![login](https://cloud.githubusercontent.com/assets/16742788/12377158/f0a296e4-bd38-11e5-95d4-129894c26e5a.jpg)

not able to add 2 input fields

**Comment by sunilsmith** [comment]
look [swal forms](https://github.com/taromero/swal-forms) you will get some idea

**Comment by t4t5** [comment]
This project isn't going to support setting custom HTML as strings, as I think it reinforces bad design patterns. If you want a custom modal, it should be built from scratch or using another library. SweetAlert just aims at providing a better version of `alert` with some extra features, NOT replace all your modals. :)
