### ISSUE TITLE
In the http://t4t5.github.io/sweetalert/ ,double-click the any button.it's will show & hide ..

### ISSUE THREAD

**Issue by visten** [t4t5/sweetalert#514]
##### 

If you quick click the button to open sweetalert,it will show and hide and show and.....

Also.
If you disable the button when click it ,and 

`
    swal({title:"tip"},function(){
        //enable button
    })
`

It's can't execute the callback function.

Do you have any other solution?
Thanks!

**Comment by t4t5** [comment]
The expected behaviour is that SweetAlert will close whenever something outside of it is clicked. Double-clicking the button triggering the alert could lead to that. Please try the new 2.0 release.
