### ISSUE TITLE
Run function on prompt box okay button clicked

### ISSUE THREAD

**Issue by zanedb** [t4t5/sweetalert#517]
Hi, I'm using SweetAlert on my webpage, and I want people to be able to write their name in a prompt box. When they click okay, I would like to run a function that sends their name to a PHP file and adds it to a database. I understand the PHP part, but how do you call your own function on the okay button click, and how do you get the inputValue variable out of the swal(). I might've missed something very obvious, so if I did I apologize. Anyway, please get back to me as soon as you can! Thanks!

**Comment by dkfiresky** [comment]
I think something like the following should help you, but I didn't tested it working.

```javascript
swal({
  title: "What is your name?",
  text: 'Please write your name:',
  type: 'input',
  showCancelButton: false,
  closeOnConfirm: true,
  animation: 'slide-from-top'
}, function(inputValue){

  $.ajax({
    url: 'http://mysite.com/myphpfile.php',
    type: 'POST',
    data: {
      name: inputValue
    },
    onSuccess: function() {
      alert('YAY! Name saved!');
    },
    onError: function() {
      alert('Oh noo! Error occurred!');
    }
  });
  
});
```
