### ISSUE TITLE
Redirection opening in the same tab when click on "ok" button in a sweet alert modal dialog.

### ISSUE THREAD

**Issue by Jimmaki** [t4t5/sweetalert#519]
I'd like for my visitors after click the "ok" button to redirect.
Now, the think is, I want to place it in the specific swal below.

`swal("Good job!", "You clicked the button!", "success")`

I love sweet alerts!

**Comment by t4t5** [comment]
Using SweetAlert 2.0:

```javascript
swal("Good job!", "You clicked the button!", "success")
.then(willRedirect => {
  if (willRedirect) {
    window.location.href = "http://stackoverflow.com";
  }
})
```
