### ISSUE TITLE
Adding link images in a sweet alert modal dialog.

### ISSUE THREAD

**Issue by Jimmaki** [t4t5/sweetalert#520]
How do I add a link (or more) image like: `<a href="mylink.lol" target="_blank"><img src="myimage.png" alt="something"></a>` inside the `swal("Good job!", "You clicked the button!", "success")` sweet alert modal?

**Comment by sunilsmith** [comment]
swal({   
title: "SUCCESS!!!",
text: "You have done it !!! ",
imageUrl: "js/1.png" });

**Comment by t4t5** [comment]
This project isn't going to support setting custom HTML as strings, as I think it reinforces bad design patterns. If you want a custom modal, it should be built from scratch or using another library. SweetAlert just aims at providing a better version of `alert` with some extra features, NOT replace all your modals. :)

**Comment by Jimmaki** [comment]
Sorry for late response, fixed!
https://jimmydance.com/contact-jimmy.html?r=1

**Comment by sunilsmith** [comment]
@Jimmaki may i know how you did that with swal ?

**Comment by Jimmaki** [comment]
@sunilsmith 

As you can see [here](https://jimmydance.com/dance-studios.html) I copy and paste the whole FOOTER section (html) in the TEXT field of SWAL.

Example:
swal({title: "Your message has been sent!!"  , 
text: "<footer><a href=\"anylink.com\" target=\"_blank\" class=\"// I added a sprite image like spr3-wslogo\"></a></footer>", 

*Don't forget to escape special characters

Let me know if it works

**Comment by jkjha** [comment]
Hi @Jimmaki  can you paste your code in text.. I tried to add the html like above but it didn't work for me.

**Comment by Jimmaki** [comment]
Hi there

[SweetAlert Jimmy.zip](https://github.com/t4t5/sweetalert/files/1611039/SweetAlert.Jimmy.zip)

**Comment by Hanenbadarjah** [comment]
y,u,

**Comment by dhia06** [comment]
Hi, how can i a use an image as a background(not an Icon ) for the sweet alert. thanks

**Comment by moaazib123** [comment]
Hi,
Actually, I don't understand the question well , do you ask how to use an
image as a background in CSS ?
if that is your question then it's simple
you can use
background-image: url('but here the directory of the image');
