### ISSUE TITLE
Form Modal Input

### ISSUE THREAD

**Issue by sagargulati** [t4t5/sweetalert#522]
Greetings,
How can we make multi input boxes in modal so that we can make an ajax request using it?

Thanks!

**Comment by funchiat** [comment]
I don't have the concrete solution but I think this URL might help
https://www.ludu.co/lesson/how-to-use-sweetalert#ember1310

**Comment by lancedouglas1** [comment]
Take a look as [swal-forms.](https://github.com/taromero/swal-forms).  I have just used it thoroughly for a complex multi-popup solution that has several calls and forms.

**Comment by sagargulati** [comment]
Great.
That will help! :)
Closing now!
Thanks @funchiat and @lancedouglas1
