### ISSUE TITLE
[Suggestion] Short and easy way to use SweetAlerts with Angular

### ISSUE THREAD

**Issue by pranav7** [t4t5/sweetalert#523]
https://gist.github.com/pranav7/d075f7cd8263159cf36a

``` javascript
'use strict';

angular
  .module('sweetalert', [])
  .factory('swal', SweetAlert);

function SweetAlert() {
  return window.swal;
};
```

**Comment by t4t5** [comment]
Nice solution! It should be even easier now not to depend on other libraries with the new 2.0 release. Closing since it's not an issue. :)
