### ISSUE TITLE
Failure when executing on document.ready()

### ISSUE THREAD

**Issue by omnidan** [t4t5/sweetalert#53]
I have the following source code, which only works when uncommenting the two lines.
```javascript
$(document).ready(function(){
  //setTimeout(function() {
    swal({
      title: "Done!",
      text: "",
      type: "success",
      confirmButtonText: "Ok"
    });
  //}, 500);
});
```
When running it like this, it reutrns: `Uncaught TypeError: Cannot read property 'querySelector' of null`

**Comment by yalmasri** [comment]
that worked for me too, thanks!

**Comment by t4t5** [comment]
Fixed.

**Comment by little-apps** [comment]
I just wanted to leave this here for future reference. I was having this problem and found that I was an outdated version SweetAlert. The cause of the outdated version was I downloaded the package from [ShapBootstrap](http://shapebootstrap.net/item/sweetalert-bootstrap/) and they (obviously) don't link to the [GitHub download for SweetAlert](https://github.com/t4t5/sweetalert/archive/master.zip)

**Comment by remberi** [comment]
I also encountered similar problems

**Comment by cordoval** [comment]
I think the problme is a setTimeout because sweetalert does not have it seems an even to listen upon document ready? i am finding out that if i settimeout the call it works. cc @leftdevel

**Comment by leftdevel** [comment]
The setTimeout is more of a hack than a solution. It should be possible to listen the ready event once the lib has fully loaded, and then execute the swal() code. I haven't checked the source code thoroughly though, but it doesn't seems there is anything running async, which  I find odd (it would mean that it's safe to invoke swal() on a $(document).ready(); callback };

**Comment by leftdevel** [comment]
I tested with a standalone html page, and it works without setTimeout and without using the jQuery ready function. Maybe it's the way/order of the the js scripts. cc: @cordoval.

**Comment by cordoval** [comment]
you have a sample bower.js, why not you try to use that loading all assets?

**Comment by mamathabhavana** [comment]
Thanks its worked for me to
