### ISSUE TITLE
open alert in "loading" mode

### ISSUE THREAD

**Issue by hmsuchier** [t4t5/sweetalert#531]
Hi,
 According to the documentation, it is only possible to put a Sweet Alert in a loading mode from a click on submit button. Is there a way to open a SweetAlert in a "loading" state directly  ? For example: 
 1/ user clicks on a button on main panel 
 2/ ajax action is triggered + an alert displays 'your request is being processed' 
 3/ the alert is replaced by another alert "done" if all is ok, or "argl!" if there is a problem
Thanks !

**Comment by MiWebDesign** [comment]
You can put this instructions at success ajax function.. for example:
```
$(".sweet-overlay, .sweet-alert").remove();
swal("Loading","done","success");
```

if all is ok, else you can write a sweetalert error message.

**Comment by mudphilo** [comment]
do it like this 

`swal({   
		title: "Are you sure?",   
		text: "This action will completely remove "+data.fullNames,   
		type: "warning",   
		showCancelButton: true,   
		confirmButtonColor: "#DD6B55",   
		confirmButtonText: "Yes, delete it!", 
		showLoaderOnConfirm: true,  
		closeOnConfirm: false }, 
		function(isConfirm)
			{
			   if (isConfirm) 
					{
						var toPost = {userId: data.userId , token: accessToken};

						$.ajax({
								url: apiURLDeleteUsers,
								data: JSON.stringify(toPost),
								type: "POST",
								success: function (json) 
									{
										response = json;
										swal("Deleted!", "User deleted successfully "+json.success, "success");
									},
								error: function (jqXHR, textStatus, errorThrown)
									{
										var res = jqXHR.responseJSON;
										swal("Cancelled", "User not deleted "+res.error, "error");
									}    
							});

					} 
				else 
					{     
						swal("Cancelled", "User not deleted ", "error");   
					}
			}
	);`

**Comment by gerardreches** [comment]
I want this feature too. I have my own form and I want to use the SweetAlert loader on send without having to press a second confirm button.

**Comment by mudphilo** [comment]
`swal({   
        title: "Are you sure?",   
        text: "This action will completely remove "+data.fullNames,   
        type: "warning",   
        showCancelButton: true,   
        confirmButtonColor: "#DD6B55",   
        confirmButtonText: "Yes, delete it!", 
        showLoaderOnConfirm: true,  
        closeOnConfirm: false }, 
        function(isConfirm)
            {
                // confirm button was pressed
               if (isConfirm) 
                    {
                        // get your data here
                        var toPost = {userId: data.userId , token: accessToken};
                        // prepare ajax
                        $.ajax({
                                url: apiURLDeleteUsers,
                                data: JSON.stringify(toPost),
                                type: "POST",
                                success: function (json) 
                                    {
                                        // on success display message back
                                        response = json;
                                        swal("Deleted!", "User deleted successfully "+json.success, "success");
                                    },
                                error: function (jqXHR, textStatus, errorThrown)
                                    {
                                        // error occured. display error
                                        var res = jqXHR.responseJSON;
                                        swal("Cancelled", "User not deleted "+res.error, "error");
                                    }    
                            });
                    } 
                else  // user pressed cancel
                    {     
                        swal("Cancelled", "User not deleted :)", "error");   
                    }
            }
    );`


![swal](https://cloud.githubusercontent.com/assets/4658901/23392233/4dadfd54-fd8b-11e6-9edb-4d45d0c6b41e.png)

**Comment by mudphilo** [comment]
make sure you have

`showLoaderOnConfirm: true`

**Comment by t4t5** [comment]
SweetAlert cannot show a loading state on its buttons by default. What you can do in the new 2.0 version though is create a custom component and pass it into the [content option](https://sweetalert.js.org/docs/#content). There you could show a spinner. :)

**Comment by sunny2208** [comment]
Use the below code and you will get a popup with loading.

 **window.swal({
            title: "Checking...",
            text: "Please wait",
            imageUrl: "images/page_loader1.gif",
            showConfirmButton: false,
            allowOutsideClick: false
        });**

![Untitled](https://user-images.githubusercontent.com/30391894/59596889-3241ec80-9116-11e9-967d-acf4019572c2.png)

**Comment by DavidRayner** [comment]
For v2 you can use this:

``` js
  swal({
    title: "Loading...",
    text: "Please wait",
    icon: "/images/loading.gif",
    button: false,
    closeOnClickOutside: false,
    closeOnEsc: false
  });
```

**Comment by KevinPan** [comment]
Is it able to add a customer style to the icon if the icon is an image, like width: 30px...
