### ISSUE TITLE
Bug: pressing enter very fast will dismiss the modal instead of confirming it

### ISSUE THREAD

**Issue by alvarotrigo** [t4t5/sweetalert#539]
You can reproduce it on the [demo page](http://t4t5.github.io/sweetalert/) by clicking over the 4th "Try me" (example with callback) and then pressing the key enter very fast.
(Latest Chrome under Windows)

This makes it quite unreliable when users want to accept the modal as fast as possible.

It seems the problem doesn't always take place, but just sometimes.

Here's a video:
![sweeterror](https://cloud.githubusercontent.com/assets/1706326/13252060/274353b8-da2c-11e5-9dbb-19ce29e33846.gif)

**Comment by alvarotrigo** [comment]
Possibly related with https://github.com/t4t5/sweetalert/issues/528

**Comment by mcavalletto** [comment]
Yes, this is identical to #528.

**Comment by rafael-renan-pacheco** [comment]
Fixed in this fork:

https://github.com/limonte/sweetalert2

**Comment by NeXTs** [comment]
I'm surprised this issue still open in almost year after publishing and half of year having proposed fix in separate repo..

**Comment by chekovsky** [comment]
@NeXTs this issue was fixed a long time ago in https://github.com/limonte/sweetalert2

**Comment by NeXTs** [comment]
@chekovsky Yeah I saw but on my current big project sweetalert is used and it's not that easy to migrate in my case

**Comment by t4t5** [comment]
Sorry for the delay people. This should no longer be an issue in SweetAlert 2.0. Make sure you read the [upgrade guide](https://sweetalert.js.org/guides/#upgrading-from-1x)!
