### ISSUE TITLE
SweetAlert closes itself while typing in a textarea

### ISSUE THREAD

**Issue by StephanBijzitter** [t4t5/sweetalert#541]
When the user of my application presses the spacebar multiple times, I want to show a message.

Now, this works, certainly. However, If I spam the spacebar on my keyboard the message will show up and automatically close, and I seem to be unable to disable this behaviour.

I do NOT want this message to listen to the spacebar!

**Comment by StephanBijzitter** [comment]
@t4t5 PR ready

**Comment by limonte** [comment]
It seems like this repo is inactive now, I added TEXTAREA type (`input: 'textarea'` parameter) and some additional features to [sweetalert2](https://github.com/limonte/sweetalert2).

Take a look on example: https://jsfiddle.net/47L0mf97/3/

**Comment by StephanBijzitter** [comment]
@limonte All good, but that's not related to this PR in any way.

**Comment by t4t5** [comment]
@StephanBijizitter Thanks! Will add in v1.1.4!

**Comment by t4t5** [comment]
Decided to remove the space bar event listener in 2.0 instead. Try the new release and let me know if there are any similar issues!
