### ISSUE TITLE
Allow background color change

### ISSUE THREAD

**Issue by dyelton** [t4t5/sweetalert#543]
I would like to adjust the background color in the theme based on a success, warning or error response. I don't see in the CSS where this is possible now.

**Comment by ekv88** [comment]
You need to target class: .sweet-alert
or you can use JS:
``javascript
$(".sweet-alert").css('background-color', '#000');
``

**Comment by paddotk** [comment]
@ekv88 I've tried this (also .sweet-overlay, as I want to disable the transparent black page overlay) in both jQuery (after stating the sweetalert) and in CSS, but it doesn't do anything at all.

**Comment by t4t5** [comment]
You can style the class: `.sweet-alert` to achieve this. Just make sure your custom CSS comes AFTER SweetAlert's CSS file.
