### ISSUE TITLE
[BUG] `closeOnConfirm` to false break tab button

### ISSUE THREAD

**Issue by Buom01** [t4t5/sweetalert#544]
Hi,
I find a bug (tested in firefox):
in a form, you can press tab to go to the next input, but after this code:

``` JavaScript
swal({
    title: "Simple question",
    closeOnConfirm: false,
},function(){
    window.setTimeout(function(){
        swal("Simple confirmation", "and tab breaking", "success");
    },0);
});
```

you can't use tab button in form anymore :(

**Comment by Buom01** [comment]
Temporary solution find in: https://github.com/t4t5/sweetalert/issues/391

**Comment by alex-shamshurin** [comment]
The same issue is here. Solution is `window.onkeydown = null` in onClose callback

**Comment by t4t5** [comment]
Closing since it's a duplicate of #391. Will investigate soon.
