### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by KKDeep** [t4t5/sweetalert#545]
Hi,
is it possible to add/integrate the google analytics with the Popup? I'm using popup as the Thankyou message & so want to check the footprints on the website.

The corresponding code is 
`	echo '<script type="text/javascript">swal({title: "",text: "Thank you for your interest.We will get back to you soon! :-)",imageUrl: "images/unbrake.png"})</script>';
`

**Comment by ekv88** [comment]
Well you can allways try with

```javascript
$(document).on('click', '#thanxButton', function() {
  swal({
    title: 'Whatever',
    text: 'Whatever here?'
  });
  // Then just a Google Analitycs code:
  ga('send', 'event', 'Button', 'Click', 'He clicked on tnx button');
});
```
