### ISSUE TITLE
 Translate How I can customize texts Sweetalert to Spanish or another language?

### ISSUE THREAD

**Issue by juanlopezdev** [t4t5/sweetalert#546]
Hola,
Hi there, Sweetalert has an option called " confirmButtonText " or " cancelButtonText " to change the language to the buttons ; the problem is that I want setear default text in Spanish , without having to use these options at any time to call a Sweetalert object.
How can I do it?

**Comment by adriennetacke** [comment]
There is a method called `setDefaults`. 

As stated in the documentation: 

> If you end up using a lot of the same settings when calling SweetAlert, you can use setDefaults at the start of your program to set them once and for all!

So you could try something like this: 
```javascript
swal.setDefaults({ 
    confirmButtonText: "Confirmar",
    cancelButtonText: "Cancelar" 
});
```

**Comment by juanlopezdev** [comment]
Thanks 👍

**Comment by leo108** [comment]
@t4t5 Hi, how to customize texts in version 2, my code is 

```
swal.setDefaults({
  buttons: ['确认', '取消']
});
```

but it doesn't work.
