### ISSUE TITLE
Error in sample on http://t4t5.github.io/sweetalert/

### ISSUE THREAD

**Issue by Mart-Bogdan** [t4t5/sweetalert#549]
Snippet for **An HTML message** is corrupted

``` javascript
swal({
   title: "HTML <small>Title</small>!",
   text: "A custom <span style="color:#F8BB86">html<span> message.",
   html: true
 });
```

should be:

``` javascript
swal({
   title: "HTML <small>Title</small>!",
   text: 'A custom <span style="color:#F8BB86">html<span> message.',
   html: true
 });
```

the issue is with " character inside string literal

**Comment by Mart-Bogdan** [comment]
I've found gh-pages, so made pull request #555 fixing this issu

**Comment by t4t5** [comment]
Thanks for the pull request! I decided to deprecate the `html` option though since it's much more error prone than using custom DOM nodes with `content` in 2.0.
