### ISSUE TITLE
Feature request: no bounce

### ISSUE THREAD

**Issue by edencorbin** [t4t5/sweetalert#550]
Maybe I'm missing something but can you adjust/turn off the bouncy effect, love the look/etc but would prefer not to have it bounce like that.

**Comment by adriaanzon** [comment]
You can set the animation to false, 'slide-from-top' or 'slide-from-bottom'.

**Comment by edencorbin** [comment]
Okay thanks I'll give that a try, nice plugin!

**Comment by happysailingdude** [comment]
Where would we set the animation as above please?
