### ISSUE TITLE
\9; is breaking our build process. 

### ISSUE THREAD

**Issue by zoltanradics** [t4t5/sweetalert#556]
I see these "\9" things in the dist/sweetalert.css. I am not a css guru, but it not seems to be a valid css for me. On the top, it breaks our build process. Do you have any idea where it comes from? - i could not find the in the dev files.

.sweet-alert .sa-icon.sa-error .sa-line.sa-left {
  -ms-transform: rotate(45deg) \9; }

.sweet-alert .sa-icon.sa-error .sa-line.sa-right {
  -ms-transform: rotate(-45deg) \9; }

/\* Success icon */
.sweet-alert .sa-icon.sa-success {
  border-color: transparent\9; }

.sweet-alert .sa-icon.sa-success .sa-line.sa-tip {
  -ms-transform: rotate(45deg) \9; }

.sweet-alert .sa-icon.sa-success .sa-line.sa-long {
  -ms-transform: rotate(-45deg) \9; }

**Comment by limonte** [comment]
It seems like this repo is inactive now, there's no such issue in [sweetalert2](https://github.com/limonte/sweetalert2). You can swith to it without changing any code in you project.

**Comment by t4t5** [comment]
`/9` has now been removed. It was old legacy IE9-compatible code.
