### ISSUE TITLE
Option to change the order of the cancel/ok buttons?

### ISSUE THREAD

**Issue by abayob** [t4t5/sweetalert#557]
Hello,

I was trying to switch the order of the OK/CANCEL buttons, but sadly the option is not there?

I would love to add this option by forking it and helping your awesome project, but the -dev.js is written in frameworks not familiar to me, so sadly I can only ask for a change :)

Love your plugin!

**Comment by limonte** [comment]
It seems like this repo is inactive now, I added the ability to switch the order of the OK/CANCEL buttons (`reverseButtons` parameter) and some additional features to [sweetalert2](https://github.com/limonte/sweetalert2).

**Comment by abayob** [comment]
Thank you! That was exactly what I was looking for. Thank you for the information :+1:
