### ISSUE TITLE
Please add minified CSS version

### ISSUE THREAD

**Issue by kevgathuku** [t4t5/sweetalert#562]
I have been using Sweetalert and I am loving it!
Could you please include the minified version of the CSS?
There currently only seems to be the unminified version in the [`dist`](https://github.com/t4t5/sweetalert/tree/master/dist) folder

**Comment by GGG-KILLER** [comment]
Apparently minifying the code breaks the ie9 version as mentioned on line 38 of gulpfile.js:
https://github.com/t4t5/sweetalert/blob/79f3338fffd2c5c0df92ecbc688e311077d9404d/gulpfile.js#L38

**Comment by kevgathuku** [comment]
Okay. Thanks for clarifying @GGG-KILLER :+1:

**Comment by JemarJones** [comment]
Why not use blesscss to solve this problem as others have? https://github.com/BlessCSS/gulp-bless
