### ISSUE TITLE
Double click on a button calling swal() consider second click as "cancel"

### ISSUE THREAD

**Issue by Colin-b** [t4t5/sweetalert#564]
Hi,

When double clicking on button displaying Sweet Alert on click, Sweet alert is considering second click as a click on "Cancel" button.

[Issue reproduced here](https://jsfiddle.net/th9Lxvgr/)

Regards

**Comment by kriddile** [comment]
Removing the "|| targetedOverlay" from [this line](https://github.com/t4t5/sweetalert/blob/master/dist/sweetalert-dev.js#L422) seems to fix this problem.  Doing so likely breaks allowOutsideClick, but I always have that option set to false anyways.

**Comment by t4t5** [comment]
I think this is the expected behaviour. You can however use `closeOnClickOutside: false` in SweetAlert 2.0 to prevent these kind of user errors.
