### ISSUE TITLE
Location of second alert

### ISSUE THREAD

**Issue by xauxatz** [t4t5/sweetalert#566]
Hi -

I have an alert asking the user whether he wants to update his payment info.
If "yes", I pop up a second alert, saying "Processing - please don't push any buttons." (type info)
And when done, I pop up a third alert, saying "Updated - success!"

But the three alerts show up at very different places on the screen.
Is there a way to get them to show up in the same spot?

**Comment by t4t5** [comment]
This sounds like a weird CSS issue. Please try the 2.0 release, and reopen if the problem persists.
