### ISSUE TITLE
New type: <select>

### ISSUE THREAD

**Issue by mouro001** [t4t5/sweetalert#569]
First: Thank you for your work. Sweet Alert is amazing!
I have one suggestion, you create a new type of alert. Like input but with <select> and <option>, and then having a options when you can put the options "value,text,value,text,..."
Something like this:
type: "select",
options: "1,Some Text,2,Another Text"

(english isn't my first language, sorry for any typos)

**Comment by limonte** [comment]
It seems like this repo is inactive now, I added SELECT type (`input: 'select'` parameter) and some additional features to [sweetalert2](https://github.com/limonte/sweetalert2).

Take a look on example: http://limonte.github.io/sweetalert2/#select-box

**Comment by t4t5** [comment]
This can now be done using the new `content` option: https://sweetalert.js.org/docs/#content

**Comment by AALMA** [comment]
@t4t5 I don't see in the documentation how to implement a select, am I missing something or has it not been added to documentation yet?

**Comment by Abdul-Rafay-Qureshi** [comment]
aaaa

**Comment by z639** [comment]
> 

Note: that version of Sweet Alert (sweetalert2) comes with "cancer-code" (code which is completely irrelevant to functionality), due to limonte's personal hatred/racism for the Russian people.

**Comment by z639** [comment]
> @t4t5 I don't see in the documentation how to implement a select, am I missing something or has it not been added to documentation yet?

https://github.com/t4t5/sweetalert/issues/835
