### ISSUE TITLE
block process on alert?

### ISSUE THREAD

**Issue by smolleyes** [t4t5/sweetalert#572]
hi

i use swal in a _.each loop, is it possible to act like a real alert and so block the loop until i clicked the confirm or cancel button ? now it s just replacing the content of the error dialog so i only see the last "error" in my loop not each errors :/

thanks

**Comment by t4t5** [comment]
Unfortunately, there's no way of simulating the blocking behaviour of a real alert() AFAIK. If there ever is in the future, we can reopen this.
