### ISSUE TITLE
Callback is not called when pressing the cancel button

### ISSUE THREAD

**Issue by StephanBijzitter** [t4t5/sweetalert#573]
The confirm button always calls the callback with an argument of `true`, but the cancel callback _never_ calls the callback.

Using master.

**Comment by infoeon** [comment]
Same issue. There is a handleCancel function that checks the number of arguments on the callback. If the callback function has no arguments then it isn't called. swal({...}, function(){}) won't get called, but swal({...}, function(reason){}) will get called on cancel.

But, there is a flaw in the code and it checks the number of arguments in a very hack-ish way by trying to parse the callback as a string. This method fails if you change the context of the callback using bind such as swal({...}, function(reason){}.bind(someContext))   The code should be updated to use the .length property of the callback:

if(params.doneFunction.length > 0){
    params.doneFunction(false);
}

**Comment by limonte** [comment]
It seems like this repo is inactive, I made [sweetalert2](https://github.com/limonte/sweetalert2).

There's no such issue in swal2, but you'll need to change your code from

```javascript
swal(
  {...}, 
  function(isConfirm) {
    ...
  }
);
```

to:

```javascript
swal({...}).then(
  function(isConfirm) {
    ...
  }
);
```

**Comment by StephanBijzitter** [comment]
Why check for arguments at all? Just pass it even if the callback does not take any arguments, that's the beauty of JavaScript!

**Comment by NoMan2000** [comment]
I fixed the issue, but the problem is that his Travis CI build needs to be updated, it doesn't have Qunit installed.  

"Why check for arguments at all? Just pass it even if the callback does not take any arguments, that's the beauty of JavaScript!"

It's because he passes in false as an argument if they click on cancel.  If you pass in the callback without arguments, it will always call the "success" callback when they click on cancel.

**Comment by t4t5** [comment]
Sorry, for the long delay. The new [2.0 release](https://sweetalert.js.org) uses promises instead of callback and should be more reliable. The confirm button always returns a promise value of `true`, and cancel returns `null`.
