### ISSUE TITLE
Replace buttons options

### ISSUE THREAD

**Issue by rafaelcastrocouto** [t4t5/sweetalert#575]
It would be really nice if we had some options, maybe called `confirmButtonHTML`, `cancelButtonHTML` and `buttonsHTML` that would totally replace the buttons for the HTML strings passed... 

It would be easier, for example, to make a form with a submit button or an download link without the need of hiding the default buttons and creating fake ones on the message.

**Comment by limonte** [comment]
It seems like this repo is inactive now, I added the ability to use custom HTML in OK/CANCEL buttons and some additional features to [sweetalert2](https://github.com/limonte/sweetalert2).

Take a look at the "Custom HTML description and buttons" example here https://limonte.github.io/sweetalert2/

**Comment by rafaelcastrocouto** [comment]
Thx a lot @limonte ... that's awesome!

**Comment by huglester** [comment]
@limonte thanks!

**Comment by t4t5** [comment]
I'm not so keen on adding text string in JavaScript to generate HTML markup. I think it reinforces bad patterns, so this project won't support that. :)
