### ISSUE TITLE
Confirm Button Issue(Extra Spacing Above Text)

### ISSUE THREAD

**Issue by EnumC** [t4t5/sweetalert#576]
Hello! I just installed sweetalert for my website. But I am encountering a very strange issue with the confirm button. if you go here: https://hypertech.io/  , and then click menu on the top right, and click either "Log In", or "Sign up", the alert box will pop up, but there is extra spacing above the "Alright" text. And the text is in a grey color, instead of white. I did not change anything since the download, and I merely added:

```
swal({
                title: "Oops!",
            text: "This feature is not yet implemented!",
            type: "error",
                confirmButtonText: "Alright"
            });
```

So I have no clue where the extra line came from. I checked, and everything seems to be just fine. Can anyone take a look, and see whats wrong? Thanks.

**Comment by t4t5** [comment]
I cannot access the website anymore, but my guess would be that you've defined too general CSS classes for styling. Closing for now.
