### ISSUE TITLE
Doesn't hide confirmButtonText when showLoaderOnConfirm: true

### ISSUE THREAD

**Issue by essivision** [t4t5/sweetalert#577]
Hi

I want to use sweetalert with `showLoaderOnConfirm: true` but when user click on confirmButton preloader show and also confirmButtonText show. I want to click confirmButton, hide confirmButtonText and just show preloader.

Thanks

**Comment by huglester** [comment]
Hello,

I switched to https://github.com/limonte/sweetalert2

**Comment by t4t5** [comment]
This should be fixed in SweetAlert 2.0, using `swal({ button: { closeModal: false }})` for example
