### ISSUE TITLE
How do I include Javascript Variables inside the message?

### ISSUE THREAD

**Issue by krishnamraju** [t4t5/sweetalert#581]
How do I include Javascript Variables inside the message?

swal({   title: "Error!",   text: "Javascript Variable?"   type: "error",   confirmButtonText: "Cool" });

**Comment by WeirdestYeti** [comment]
`var myVariable = 'Hello World'
swal({ 
title: "Error!",
text: myVariable,
type: "error",
confirmButtonText: "Cool"
 });`

**Comment by jsandleraol** [comment]
and how can I edit the color of the text after assigning a variable to it?

**Comment by zenflow** [comment]
@jsandleraol https://sweetalert.js.org/docs/#swal-text
