### ISSUE TITLE
Could sweetalert show a success or error message that doesn't cover the whole page?

### ISSUE THREAD

**Issue by guoyunhe** [t4t5/sweetalert#584]
I have a delete button on an article page, when users click delete button and confirmed in the first dialog, users can be redirect to article list, and show an message:

"You article XXX has been deleted." with a button to "Undo".

But I hope users can ignore the second alert. The second alert will not cover the whole page, just a tiny float box on the page. After 10 seconds, it disappears automatically.

Just like [toasts in Android](https://developer.android.com/guide/topics/ui/notifiers/toasts.html).

Is it possible to add this option to sweetalert?

**Comment by guoyunhe** [comment]
Screenshot of the idea implemented in Android:

![eu8vy](https://cloud.githubusercontent.com/assets/5836790/15618216/8157a872-2455-11e6-8f99-a445e1ff7876.png)

**Comment by macpham** [comment]
You can do custom css class by passing a `customClass` value and then style the sweet alert however you want.

**Comment by t4t5** [comment]
SweetAlert is specifically for dialogs that "freeze up" the rest of the page. I agree that it's not always the best UI though, so if you want something that's more like toasts, you should use another library!
