### ISSUE TITLE
Can I use an icon along with the input type?

### ISSUE THREAD

**Issue by Creationsphere** [t4t5/sweetalert#587]
I'd really like to be able to use the warning or danger type for the icon, but input type to include an input box. It's a shame the input type does not include an icon. Is there a way to do this? Thank you!

**Comment by limonte** [comment]
You can do this with [sweetalert2](https://github.com/limonte/sweetalert2): https://jsfiddle.net/4eLfp047/

**Comment by Creationsphere** [comment]
Thanks @limonte, however the fiddle doesn't seem to be working, and I can't see in the code where this works?

**Comment by t4t5** [comment]
In the new [2.0 release](https://sweetalert.js.org), you can do this using `icon: "warning"` and `content: "input"`.
