### ISSUE TITLE
Project still active?

### ISSUE THREAD

**Issue by CodeBrauer** [t4t5/sweetalert#592]
- There are PR that are ready to merge for over 1 year and also nearly 2 year old open issues.
- Also the last code update is nearly 8 months ago.
- There is even a fork, that is under active support by @limonte (https://github.com/limonte/sweetalert2)

So will this project continue in near future?

If not, how about adding a badge that this repository is [INACTIVE]?
More about this: https://helloanselm.com/2013/handle-deprecated-unmaintained-repositories

**Comment by Potherca** [comment]
To quote from #571

> @t4t5 commented on 26 Apr 2016
> ---
> The project isn't dead. I just haven't had time to go through pull requests and issues lately.
> 
> sweetalert2 was forked before v1.0, so the structure of the project is quite different. This doesn't necessarily mean that it's not a good alternative. If there's a feature in there that you need, you should of course use it.
> 
> It kinda bugs me that it's called sweetalert2 though, since that makes it sound like it's a natural progression of this project, even though I'm planning a 2.0 release later this year...
> 
> Anyways, free software, do what you like. Just wanted to say sorry for being unresponsive, and that I'm planning on becoming more active soon.
> 
> If there are any good candidates to help me maintain the project, please let me know!
