### ISSUE TITLE
wanner show cancelButton on top right corner of sweetAlert

### ISSUE THREAD

**Issue by YeZhiqiuSev** [t4t5/sweetalert#595]
I suppose there will be another cancelButton seems like style 'x' on the right top corner of the sweetAlert dialog. The cancelButton 'x' will appear on every type of sweetAlert ,what should i do?

**Comment by limonte** [comment]
There is `showCloseButton` option in [sweetalert2](https://github.com/limonte/sweetalert2).

This project is inactive currently, I suggest you switch to sweetalert2, here's the simple migration guide: https://github.com/limonte/sweetalert2/wiki/Migration-from-SweetAlert-to-SweetAlert2
