### ISSUE TITLE
modalIsVisible 通过hasClass 判断有延迟, 正在显示时 modalIsVisible 会判断为 false

### ISSUE THREAD

**Issue by angular-moon** [t4t5/sweetalert#599]
快速的双击触发按钮会导致 alert 被关闭

**Comment by angular-moon** [comment]
else if (doneFunctionExists && modalIsVisible || targetedOverlay)  
change to
else if (doneFunctionExists && modalIsVisible || (targetedOverlay && params.allowOutsideClick))

**Comment by wolfidea** [comment]
我们也遇到这个情况。但是一些低版本不存在此情况。

**Comment by lxk0301** [comment]
你这个是速度太快了.那个遮布层还没出来,你就点击了,然后弹窗就关闭了把

**Comment by t4t5** [comment]
Sorry guys I don't understand this, but the issue is probably fixed in the new 2.0 release. :)
