### ISSUE TITLE
on page load

### ISSUE THREAD

**Issue by vishalmo123** [t4t5/sweetalert#608]
HI I am trying to use alert by placing code in head section.

i am not able to execute , how to execute onload from body section of html .

Please help!
Thanks
Vishal Mohakar

**Comment by souzamarcos** [comment]
Place code in footer section after script and stylesheet of sweetalert.
You can post the code?

**Comment by vishalmo123** [comment]
Hi ,
Placing code in footer ??
I have put the code in the body section , On my website I have 20 pages , so the  problem is every time the any page lod , pop up appears .

I want that it should come only once .

What can be done ??

Thanks in advance !!

Vishal

**Comment by t4t5** [comment]
If you need help with your code, you need to post your code. :) Closing.
