### ISSUE TITLE
How to run a function after close timer alert close

### ISSUE THREAD

**Issue by souzamarcos** [t4t5/sweetalert#609]
Hi,
I need run a function after close timer alert.
How I can do this?
I can do this only using alert witht confirm button.
Thanks

**Comment by mishengqiang** [comment]
@souzamarcos I suggest you use [sweetalert2](https://github.com/limonte/sweetalert2)

**Comment by souzamarcos** [comment]
Thanks @mishengqiang. I'll use

**Comment by t4t5** [comment]
Using the new 2.0 release: 

```javascript
swal({ timer: 2000 }).then(() => console.log("ohai"));
```
