### ISSUE TITLE
怎么修改对话框的取消按钮颜色？ 

### ISSUE THREAD

**Issue by teddymail** [t4t5/sweetalert#612]
cancelButtonColor:'#aaa  我使用这个表示并不好用啊？，正确的该怎么改变呢？

**Comment by wYhooo** [comment]
You can only change the color of confirm button.

**Comment by mishengqiang** [comment]
cancelButtonColor这个参数并不存在，仅仅存在confirmButtonColor这个参数，你可以查看中文版文档http://www.mishengqiang.com/sweetalert/，如果你非常想使用sweetalert，我建议你使用[sweetalert2](https://github.com/limonte/sweetalert2/)。

**Comment by t4t5** [comment]
The cancelButton should be styled with CSS. :)
