### ISSUE TITLE
"Not valid!" message appears on success type

### ISSUE THREAD

**Issue by tetreum** [t4t5/sweetalert#613]
![Error](http://i.imgur.com/2bwsAgq.png)

http://i.imgur.com/2bwsAgq.png
**Version**: 1.1.1
**Code**:

``` js
swal({title: "¡Success!",
                text: "sdf",
                type: "success",
                html: false
            });
```

¿Why is that message appearing?

**Comment by r3wt** [comment]
atleast the alert displays for you. this is what i get:

![img](http://puu.sh/qU30A/78e97e3e0c.png)

**Comment by AcarMeel** [comment]
I'm having the same issue when I deployed my site. I'm using .net and win server 2008 r2

**Comment by SkyHacks** [comment]
For me, the issue was not including the sweetalert css file on the page.

**Comment by alvaro-paco** [comment]
Just include this SCSS [sweetalert.scss](https://github.com/t4t5/sweetalert/blob/master/dev/sweetalert.scss) in your code.

**Comment by t4t5** [comment]
SweetAlert 2.0 improves the rendering of modal content by building it from scratch every time `swal()` is called, so this bug shouldn't exist anymore!
