### ISSUE TITLE
Swal after each other

### ISSUE THREAD

**Issue by dud3** [t4t5/sweetalert#614]
The second one overwrite the first one.

``` js
swal({
            title: "Note",
            text: "Blah",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
          });
```

``` js
swal({
            title: "Note 2",
            text: "Blah",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
          });
```

On the other hand if we have our usual simple alert, we can easily do `alert('a'); alert('b')` and they'll work properly.

**Comment by limonte** [comment]
You probably should switch to [sweetalert2](https://github.com/limonte/sweetalert2) as this project is inactive for 11 months.

In sweetalert2 there's `queue()`, take a look at the example: https://limonte.github.io/sweetalert2/#chaining-modals

Migration guide: https://github.com/limonte/sweetalert2/wiki/Migration-from-SweetAlert-to-SweetAlert2

**Comment by t4t5** [comment]
You can chain promises in SweetAlert 2.0: https://sweetalert.js.org/guides/#using-promises
