### ISSUE TITLE
Is it possible to load text propery of an alert using ajax?

### ISSUE THREAD

**Issue by am2222** [t4t5/sweetalert#616]
Hi,
My themplate uses sweetAlert to show alerts to users, I want to have a context loader dialog which when user clicks a link alert appears and shows an animation which says it is loading and when an ajax call responded it updates the text property of alert, 
I have seen some example but they only work when user clicks a button on alert,
Can you please help me with it?
thanks

**Comment by t4t5** [comment]
Check out [SweetAlert 2.0](https://sweetalert.js.org/docs/#content)'s new `content` option in combination with the button options `swal.stopLoading()`. You should be able to build more advanced user interfaces with that.
