### ISSUE TITLE
Background Color not rendering

### ISSUE THREAD

**Issue by NTAuthority98** [t4t5/sweetalert#618]
![capture](https://cloud.githubusercontent.com/assets/13150392/18475852/50748482-79c8-11e6-87a4-cc50ab6b18a4.PNG)
Everything works great except for the button's background-color which seems not to render as expected no matter what. I even tried copying the exact same button (style included) but it doesn't change anything. This is really nagging me and I hope someone can help me out here, I really can't get my head around this!

**Comment by symach1ne** [comment]
Did you manage to solve this problem? I'm having the same problem myself right now and can't figure it out...

**Comment by NTAuthority98** [comment]
Yes! My template css was broken and as a consequence every button's background-color was overriden by the css. Make sure the template's css is fine.

**Comment by symach1ne** [comment]
Aha of course, I see my mistake now. Thanks!
