### ISSUE TITLE
Option to disable animation

### ISSUE THREAD

**Issue by blackrosezy** [t4t5/sweetalert#62]
Can we have an option to disable the animation? Thank you :)

**Comment by t4t5** [comment]
In 0.4.0 you can now pass ```animation: false``` to disable animations.

**Comment by hasanablak** [comment]
> In 0.4.0 you can now pass `animation: false` to disable animations.

It does not work, what can I do?

**Comment by ceciiiron** [comment]
> > In 0.4.0 you can now pass `animation: false` to disable animations.
> 
> It does not work, what can I do?

You can pass empty string to "popup" to showClass config

```js
Swal.fire({
  showClass: {
	  popup: "",
  },
});
```
