### ISSUE TITLE
swal not working on android browser

### ISSUE THREAD

**Issue by nugrahawahyu** [t4t5/sweetalert#622]
Swal is working on chrome but not working on built in samsung android browser.

**Comment by QiiSyhx** [comment]
i have the same problem, it's can alert message,but the callback function is not working.

**Comment by kamikazekip** [comment]
Please do fix this!

**Comment by t4t5** [comment]
Could someone with an Android phone check if this problem persists with the promises in SweetAlert 2.0?

**Comment by ethmz** [comment]
I tested the examples on an asus android phone and it worked fine.

**Comment by t4t5** [comment]
Thanks @ethmz, I'll close it then. :)
