### ISSUE TITLE
How to upload files with SweetAlert2

### ISSUE THREAD

**Issue by Nalcom** [t4t5/sweetalert#623]
Hi everybody.

I try to upload files with SweetAlert2.

I've no problem if I make very simple window like 

```
swal({
    html: '<form action=\"script/php/upload.php\" method=\"post\" enctype=\"multipart/form-data\"><input name:\"upload[]\",id:\"fileToUpload\",accept: \"application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet\" multiple></input></form>'
})
```

but with this technic I don't use all the powerful of SweetAlert.
So I do that in **Javascript/Ajax** file

```
swal({
    input: 'file',
    inputAttributes: {
        name:"upload[]",
        id:"fileToUpload",
        accept: "application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        multiple:"multiple"
    },
    showCloseButton: true,
    showCancelButton: true
}).then(function() {
    var formData = new FormData();
    formData.append('fileToUpload', $('#fileToUpload')[0]);
    $.ajax({type:"POST",url:"script\\php\\upload.php",data: formData,processData: false,contentType: false,headers:{"Content-Type":"multipart/form-data"},async:false});
})
```

and my **PHP**

**$total = count($_FILES['upload']['name']);
echo($total);

for($i=0; $i<$total; $i++) {
  $tmpFilePath = $_FILES['upload']['tmp_name'][$i];

  if ($tmpFilePath != ""){
    $newFilePath = "d:/web/site_sig_cclo/site_3_administration/script/python/" . $_FILES['upload']['name'][$i];

```
if(move_uploaded_file($tmpFilePath, $newFilePath)) {
}
```

  }
}**

that's return nothing.

If I use console.log on my input file after that `.then(function(file) {`I've :

![20](https://cloud.githubusercontent.com/assets/10656432/19147979/fae43846-8bba-11e6-94cc-4e4ce1daae96.png)

And if I do the same on my FormData it seems to be empty 

![10](https://cloud.githubusercontent.com/assets/10656432/19147980/fae4b2bc-8bba-11e6-97bc-fecf0e436b82.png)

So, do you know how can I do this with Sweetalert2 ?

Thank you for your help.

Nalcom

**Comment by brunomperes** [comment]
Guess you went to the wrong repo, this is for the old (and apparently unmaintained) sweetalert, the SweetAlert2 repo is https://github.com/limonte/sweetalert2

**Comment by dramosbarajas** [comment]
[document.pdf](https://github.com/t4t5/sweetalert/files/1431885/document.pdf)
