### ISSUE TITLE
sweetalert-install-error

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [t4t5/sweetalert#627]
# sweetalert-install-error

what's going on ?

![sweetalert-install-error](https://cloud.githubusercontent.com/assets/18028768/19765809/f01cb546-9c7c-11e6-9009-5360c59a61cf.png)

**Comment by t4t5** [comment]
This doesn't seem to be happening when I'm installing SweetAlert 2.0 through NPM so I'm going to close this issue.

**Comment by xgqfrms-GitHub** [comment]
# too later!
