### ISSUE TITLE
Add width/padding option

### ISSUE THREAD

**Issue by kroese** [t4t5/sweetalert#628]
When I use sweetalert to display an image to the user, there is a large amount of white spacing around the image. This gets even worse when you disable the OK button through the config.

It would be nice to have an option to specify the amount of padding. Another option to set the width of the dialog could also come in handy, because currently I have to override the CSS for that.

**Comment by limonte** [comment]
You probably should switch to [sweetalert2](https://github.com/limonte/sweetalert2) as this project seems to be unmaintained.

In sweetalert2 there are both `width` and `padding` options.

Migration guide: https://github.com/limonte/sweetalert2/wiki/Migration-from-SweetAlert-to-SweetAlert2

**Comment by t4t5** [comment]
Overriding the CSS is better than having lots of custom JS options imo. It's now easier to do thanks to the new class names is SweetAlert 2.0: https://sweetalert.js.org/docs/#theming
