### ISSUE TITLE
Issue when using type input and not setting closeOnConfirm

### ISSUE THREAD

**Issue by davesierra** [t4t5/sweetalert#629]
http://codepen.io/anon/pen/ozKbJP

The working example is taken straight out of the example on the demo page, and the not working example is the exact same code but with closeOnConfirm commented out.

I haven't dug through the docs to see if this is expected to be in the options, but at least throwing an error or warning would be sufficient and save alot of hair pulling.

**Comment by t4t5** [comment]
This was indeed an annoying part of the old version of the library. In 2.0, `closeOnConfirm` has been deprecated and this should be easier to implement using `content: "input"`.
