### ISSUE TITLE
CSS selectors are too generic

### ISSUE THREAD

**Issue by adambutler** [t4t5/sweetalert#63]
I think that the CSS selectors should be prefixed with `swal-`

The CSS selectors are far too generic. These are all scoped to `.sweet-alert` which means that they should not affect anything else on the site but rather the site CSS could affect sweetalert. Here are some of the CSS selectors that I think should be prefixed.

`.icon`
`.error`
`.info`
`.success`
`.warning`
`.placeholder`
`.fix`
`.tip`
`.long`
`.custom`
`.line`
`.left`
`.right`
`.dot`

**Comment by sushantdhiman** [comment]
Any updates when this enhancement will be included?

**Comment by t4t5** [comment]
Added in v0.4.2! Thanks guys!

**Comment by adambutler** [comment]
:+1: Thanks
