### ISSUE TITLE
Sweet Alert does not work offline

### ISSUE THREAD

**Issue by edwinokugbo** [t4t5/sweetalert#631]
I am using sweetalert on a non web project. I noticed that sweetalert does not work when I am offline. This new project will be used in environments which may be offline so this a real issue for me.

Is there a way to make it work offline?

Would appreciate any info. 

Cheers

**Comment by mateuskalz** [comment]
How do you refer the swal in your project? Can you show the code?

**Comment by t4t5** [comment]
SweetAlert definitely works offline. There's no code referring to any external script. It must be your code that's wrong. Check your JavaScript console. :)

**Comment by Waseem403** [comment]
Sweet alert is not working offline,is there anyway to get it offline

**Comment by Miloudi-Imad** [comment]
just download it using idm and use it as local js (and css) file.
