### ISSUE TITLE
Why cancel callback don't work when using a bind(this)?

### ISSUE THREAD

**Issue by lucasumberto** [t4t5/sweetalert#632]
I need to use scope variables to stop the loading effect in my view. But swall does'ent exec the callback function when it has .bind(this) on it... why?

swal({
  title: "Are you sure?",
  text: "You will not be able to recover this imaginary file!",
  type: "warning",
  showCancelButton: true,
  confirmButtonColor: "#DD6B55",
  confirmButtonText: "Yes, delete it!",
  cancelButtonText: "No, cancel plx!",
  closeOnConfirm: false,
  closeOnCancel: false
},
function(isConfirm){
  if (isConfirm) {
    successFunction.bind(this); // it works
  } else {
    myfunction.bind(this); // it is ignored
  }
});

**Comment by lucasumberto** [comment]
I found a workaround for this issue, if someone else needs:
Store the scope in a var, i called it "_this":

`var _this = this;`

and use it to call the scope inside the else box!

**Comment by t4t5** [comment]
Since SweetAlert works differently now through the use of [promises](https://sweetalert.js.org/guides/#using-promises), I'm going to close this.
