### ISSUE TITLE
uncaught exception: cancel

### ISSUE THREAD

**Issue by sastrahost** [t4t5/sweetalert#635]
This error will show when i click "cancel" button in Sweetalert2

`swal({
		  title: menu_title,
		  text: title,
		  input: "text",
		  showCancelButton: true,
		  animation: "slide-from-top",
		  showLoaderOnConfirm: true,
		  inputPlaceholder: lang.write_your_comment,
		  preConfirm: function(inputValue) {
				return new Promise(function(resolve, reject) {
							resolve('ok');
					});
				})
			},
			allowOutsideClick: false
	}).then(function(result){
		var res = $.parseJSON(result);
		if(res.status){
			swal({
				title: lang.thankyou+"!",
				text: lang.your_feedback_sent,
				type: "success"
			}).then(function(confirm){
				location.reload();
			});
		} else{
			swal({
				title: lang.sorry+"!",
				text: res.message,
				type: "warning"
			});
		}
	});`

**Comment by mjniuz** [comment]
when click close icon, it show error too, 
sweetalert uncaught exception: close

**Comment by t4t5** [comment]
Should be posted here: https://limonte.github.io/sweetalert2/

**Comment by eminx** [comment]
In case someone comes here and gets stuck (because `sweetalert != sweetalert2`!)

At the end of the `swal({...})`, add this: `catch(() => swal.close())`

**Comment by stzoran1** [comment]
@eminx you saved my day :)

**Comment by SantiM96** [comment]
@eminx me too!!
