### ISSUE TITLE
imageSize doesn't work

### ISSUE THREAD

**Issue by rstudner** [t4t5/sweetalert#64]
swal({
                                    title: "Sweet!",
                                    text: "Here's a custom image.",
                                    //imageSize: "177x100",
                                    imageUrl: "assets/images/final-cry.gif"
                                });

If I uncomment image size I get an undefined error here:
```javascript
          $customIcon.css({
            'width': imgWidth + 'px',
            'height': imgHeight + 'px'
          });
```

$customIcon needs to be wrapped in $() for this to work.

**Comment by t4t5** [comment]
This has been fixed now! :+1:
