### ISSUE TITLE
Mismatched anonymous define() module

### ISSUE THREAD

**Issue by kellerkichel** [t4t5/sweetalert#642]
Sometimes when I use sweet alert combined with more modules I have these issue:
![image](https://cloud.githubusercontent.com/assets/4204423/21618475/39de0948-d1d2-11e6-9a1e-43d005b8b2eb.png)

To prevent it, I name the module and all be cool, following the code I changed:

At line: **1248**
```javascript
define(function () {
  return sweetAlert;
});
```

**to:**
```javascript
define('sweetalert', [], function () {
  return sweetAlert;
});
```

**Comment by t4t5** [comment]
This should no longer be an issue in SweetAlert 2.0. Please reopen if the problem persists! 👍

**Comment by sharrondenice** [comment]
Thank you @kellerkichel this saved me additional hours of heartache.
