### ISSUE TITLE
Date Input

### ISSUE THREAD

**Issue by IronCoderXYZ** [t4t5/sweetalert#647]
Hi, 

I am really loving the Sweet Alert 2 project.

I have used the chaining modals option to collect user input, but I really need to collect a date as well. I cannot figure out how to do this, I can't embed any datepicker either.

Please advise!

Thank you

**Comment by Gigex** [comment]
Have you found any solution for this? i seem to have the same need as you

**Comment by t4t5** [comment]
This can now be done using the `content` option: https://sweetalert.js.org/docs/#content
