### ISSUE TITLE
How to load the css file from webpack while using postcss

### ISSUE THREAD

**Issue by yinanfang** [t4t5/sweetalert#651]
Here's my css config:
```
{
  test: /\.css$/,
  loaders: [
    'style',
    'css?sourceMap&modules&importLoaders=1&localIdentName=[path][name]__[local]__[hash:base64:5]',
    'postcss?sourceMap=inline',
  ],
}
```
If I do `@import "sweetalert/dist/sweetalert.css";` in the css file, the style will have prefix and suffix, which will be something like `src-style__sweetalert__lkafr` and all the stylings are broken.

Is there any way to correctly import the css file using webpack?

**Comment by t4t5** [comment]
In SweetAlert 2.0, you no longer need to import the CSS file yourself. It's now embedded in the single JS-file, which makes things easier. :)
