### ISSUE TITLE
QUESTION how to put language variable in .js

### ISSUE THREAD

**Issue by PrestaShark** [t4t5/sweetalert#653]
Hi. 
I have general question how to put language variable into SW

Work but i dont want to show button, and want to set timer
swal('', max_item, 'error');

So i make this and its not work
swal({title: "", text: "**max_item**",  type: "error", showConfirmButton: false,  timer: 3000});

**max_item** is here 
{addJsDefL name=**max_item**}{l s='You cannot add more than %d product(s) to the product comparison' sprintf=$comparator_max_item js=1}{/addJsDefL}

Thanks for help

**Comment by t4t5** [comment]
If you want to add a variable from another language than JS, you'll have to print in out to the DOM somewhere and then pick it up with JS. Then you can use `"You cannot add more than " + numberOfProducts + " to the product comparison".
