### ISSUE TITLE
Change default confirmButtonColor for warning type alerts

### ISSUE THREAD

**Issue by gerardreches** [t4t5/sweetalert#655]
Is there a way to set in the `swal.setDefaults()` function a default `confirmButtonColor` only for warning alerts?

I mean, by default I want the confirm button to be green, so I set it in the `swal.setDefaults()`, but I want this button to be red by default only when the alert has `type: "warning"`, without having to override it on each warning alert.

**Comment by agentphoenix** [comment]
Agreed. Would be nice to be able to specify a class or something so that we can control button styles based on the type of alert.

**Comment by t4t5** [comment]
In SweetAlert 2.0, there's a new `dangerMode`. I think that's what you're looking for! https://sweetalert.js.org/docs/#dangermode
