### ISSUE TITLE
inside a loop and function issue

### ISSUE THREAD

**Issue by vaibhavc95** [t4t5/sweetalert#658]
this is the function in order to check if a scale/field is empty or not...if its empty..it should show alert boxes...i am new to coding.... accessing through a button...i.e. onclick="submit()"...i just replace alert with swal to run my code...it is not working...it displays just once for a less than a second and disappears,,,not checking further conditions...please help me!!

function submit1() {
                var totlevel = document.getElementById("totlevel").value;
                var survey_name = document.getElementById("survey_name").value;
                var type = "13";
                var sticks = "";
                var ques = "";
                var scales1 = "";
                var scales2 = "";
                var scales3 = "";
                var scales4 = "";
                var scales5 = "";
                for (i = 1; i <= totlevel; i++) {
                    var stick = document.getElementById("stick" + i).value;
                    var scale1 = document.getElementById("scale1" + i).value;
                    var scale2 = document.getElementById("scale2" + i).value;
                    var scale3 = document.getElementById("scale3" + i).value;
                    var scale4 = document.getElementById("scale4" + i).value;
                    var scale5 = document.getElementById("scale5" + i).value;
                    sticks += document.getElementById("stick" + i).value + "##";
                    ques += document.getElementById("ques" + i).value + "##";
                    scales1 += document.getElementById("scale1" + i).value + "##";
                    scales2 += document.getElementById("scale2" + i).value + "##";
                    scales3 += document.getElementById("scale3" + i).value + "##";
                    scales4 += document.getElementById("scale4" + i).value + "##";
                    scales5 += document.getElementById("scale5" + i).value + "##";
                    if (stick === "option") {
                        
                        if (scale1 == "") {
                                         
                           alert("Please write on scale 1 field");        
                        }
                        if (scale2 == "") {
                            
	                   
                                          
                              
                           alert("Please write on scale 2 field");
                        }
                        if (scale3 == "") {
                           
	                   
                                            
                           alert("Please write on scale 3 field");
                        }
                        if (scale4 == "") {
                           
	                 
                                                            
                            alert("Please write on scale 4 field");
                        }
                        if (scale5 == "") {
                           
	                   
                                                        
                           alert("Please write on scale 5 field");
                        }
                    }
                }

**Comment by t4t5** [comment]
`sweetAlert` is non-blocking, contrary to `alert`, so you'll have to refactor your code to take that into account. Also, remember the [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) principe. :-)
