### ISSUE TITLE
Nuget update

### ISSUE THREAD

**Issue by weedkiller** [t4t5/sweetalert#663]
Hi looks like the nuget is a 2 yrs old version , can you please update.

Also whats the difference between this and sweetalert2?

thanks

**Comment by limonte** [comment]
> Also whats the difference between this and sweetalert2?

https://github.com/limonte/sweetalert2#whats-the-difference-between-sweetalert-and-sweetalert2

**Comment by t4t5** [comment]
I have no control over the Nuget version unfortunately.

**Comment by djm61** [comment]
I created the NuGet repository, however I'm going to let it die as the future for NuGet is to not have content files anymore.  I would recommend having this package added to NPM or Bower or something.  Maybe I'll do that - no promises.

**Comment by ImTheKeyMaster** [comment]
Hi Tristan,
Sorry to bother you.  But, is it possible to create a new NuGet for the 2.x version?  I only see 1.1.3 and it works wonderfully (accept in IE11).  NuGet is the preferred method of package inclusion in Visual Studio.

**Comment by djm61** [comment]
See my comment right above yours.  NuGet is no longer for content packs.  Please use NPM or Bower [which is also baked into Visual Studio]

**Comment by weedkiller** [comment]
but thats an issue for people with older projects
