### ISSUE TITLE
Why is there a half-second delay inserted here?

### ISSUE THREAD

**Issue by lgommans** [t4t5/sweetalert#664]
For alerts with input fields, there is a 0.4 second delay introduced on this line:

https://github.com/t4t5/sweetalert/blob/3b9d8eb90268e0b1f8f58b2eba240631df0ad18f/dev/modules/set-params.js#L115

Why is this done? I suspected it had something to do with waiting for an animation, but the input field is there already. Setting the delay to 1 millisecond, it works just fine.

If there is no particular reason for this, I'd personally prefer to just get rid of it -- why make users wait before they can type? Not just users but also power users who know this thing will pop up and want to input something and be done with it. At the very least it could be a setting, if there is some reason (other than compatibility, in that case it might be necessary no matter your preference) to keep it.

**Comment by t4t5** [comment]
Agreed. There's no delay in SweetAlert 2.0 anymore. :)
