### ISSUE TITLE
prompt doubt ¿?

### ISSUE THREAD

**Issue by mentamarindos** [t4t5/sweetalert#670]
How can I put multiple _input text_ in a prompt?

**Comment by ekv88** [comment]
Nop, but you can call another SWAL right after, that can even be cool if you have 2 or 3 inputs.

**Comment by t4t5** [comment]
This is now possible with the new `content` option: https://sweetalert.js.org/docs/#content

**Comment by limonte** [comment]
> https://limonte.github.io/sweetalert2/#multiple-inputs

this link is outdated, here's the correct one https://sweetalert2.github.io/#multiple-inputs
