### ISSUE TITLE
grabing values from input fields and checking them against database

### ISSUE THREAD

**Issue by sri984** [t4t5/sweetalert#672]
i want to use multiple inputs as a password recovery method in my project, i created multiple fields using the "html", now i want to get the values from these fields and check against the database for their validity , if the given username exists i want to prompt the user his password, can someone help me out?

**Comment by mentamarindos** [comment]
same problem here... any help?

**Comment by abr4xas** [comment]
Ajax is all you need.

**Comment by t4t5** [comment]
As @abr4xas, that's beyond the scope of this library. I would use AJAX to post the fields to an API of some kind, and do the validation there.
