### ISSUE TITLE
Use html:true to enable parser html is working incorrect 

### ISSUE THREAD

**Issue by avatarr** [t4t5/sweetalert#674]
I have setting like this 

``` javascript
  swal({
          title: 'my title',
          text: 'A custom <span style="color:#F8BB86">html<span> message.',
          html: true,
          type: 'warning',
          showCancelButton: true,
          confirmButtonColor: '#3085d6',
          cancelButtonColor: '#d33',
          confirmButtonText: 'เล่น Lotto'
        }).then(function () {
          // angular service
          GamePlayerService.create(params, function(){
            setTimeout(function () {
              window.location.reload();
            }, 1000);
          });
        });
```

Then I run above code I got 'TRUE' show in UI instead sweetalert parse html as my expectation 

<img width="543" alt="screen shot 2560-03-07 at 11 48 25 pm" src="https://cloud.githubusercontent.com/assets/1640817/23667501/a94f9194-0390-11e7-89f9-0690f661ec55.png">

**Comment by ajoah** [comment]
Hi @avatarr 

I think you confuse https://github.com/t4t5/sweetalert and https://limonte.github.io/sweetalert2/

If you get true instead of html parsed, you use sweetalert2 so you must do like this : 

```
 swal({
          title: 'my title',
          html: 'A custom <span style="color:#F8BB86">html<span> message.',
          type: 'warning',
          showCancelButton: true,
          confirmButtonColor: '#3085d6',
          cancelButtonColor: '#d33',
          confirmButtonText: 'เล่น Lotto'
        }).then(function () {
          // angular service
          GamePlayerService.create(params, function(){
            setTimeout(function () {
              window.location.reload();
            }, 1000);
          });
        });
```

**Comment by avatarr** [comment]
@ajoah Thank you for your help and I have solved

**Comment by limonte** [comment]
> I think you confuse https://github.com/t4t5/sweetalert and https://limonte.github.io/sweetalert2/

this link is outdated, here's the correct one https://sweetalert2.github.io/

**Comment by Cliffy786** [comment]
> Hi @avatarr
> 
> I think you confuse https://github.com/t4t5/sweetalert and https://limonte.github.io/sweetalert2/
> 
> If you get true instead of html parsed, you use sweetalert2 so you must setting like this :
> 
> ```js
>  swal({
>           title: 'my title',
>           html: 'A custom <span style="color:#F8BB86">html<span> message.',
>           type: 'warning',
>           showCancelButton: true,
>           confirmButtonColor: '#3085d6',
>           cancelButtonColor: '#d33',
>           confirmButtonText: 'เล่น Lotto'
>         }).then(function () {
>           // angular service
>           GamePlayerService.create(params, function(){
>             setTimeout(function () {
>               window.location.reload();
>             }, 1000);
>           });
>         });
> ```

Thanks this really helped me as well
