### ISSUE TITLE
Possibility to change order of buttons

### ISSUE THREAD

**Issue by mmrupp1** [t4t5/sweetalert#675]
Hi,

after discussing with many people how they expect where OK and Cancel are, I would ask for an enhancement, because your implementation use an unexpected order. 

I would like to have an option where I can specify the order of the buttons...

**Comment by limonte** [comment]
Take a look in https://github.com/limonte/sweetalert2 it has reversed buttons order by default. Also, there's the `reverseButtons` parameter so you can always configure the order of buttons.

**Comment by mmrupp1** [comment]
Got it. Thanks.

Michael

**Comment by t4t5** [comment]
You can now set the exact order of the buttons in SweetAlert 2.0.

For a simple reverse of cancel and confirm, you would write:

```javascript
swal({ 
  buttons: { 
    confirm: true, 
    cancel: true,
  }
})
```
