### ISSUE TITLE
add img to swal and remove Alert icon

### ISSUE THREAD

**Issue by Linton-Samuel-Dawson** [t4t5/sweetalert#676]
I add Image but alert icon `<div class="sa-icon sa-info" style="display: block;"></div>` is still there
how can I remove it?

` swal({
                    title: "Send ",
                    text: "Send",
                    type: "info",
                    showCancelButton: true,
                    closeOnConfirm: false,
                    showLoaderOnConfirm: true,
                    confirmButtonText:"ok",
                    confirmButtonColor:"#5cb85c",
                    cancelButtonText:"cancel",
                    imageUrl:'/img/logo.png',
                },
                function(){
                    setTimeout(function(){
                        $.ajax({
                            method:'POST',
                            url:'/store',
                            headers: {
                                'X-CSRF-TOKEN': CSRF_TOKEN
                            },
                            data:arr,
                            success:function(response){
                                console.log(arr)
                            }
                        });

                        swal("OK!");
                    }, 500);
                });`

**Comment by ekv88** [comment]
Just remove type: "info"
