### ISSUE TITLE
Some way yo handle error responses in json

### ISSUE THREAD

**Issue by vexilo** [t4t5/sweetalert#681]
Hi i have this function for deleting users via ajax

```
swal({
    title: 'Are you sure do you want to delete?',
    showLoaderOnConfirm: true,
    preConfirm: function () {
        //  make an ajax request like a promise (works fine)
        return App.delete('/users/' + user.id, this.form)
    }.bind(this)
}).then(function () {
    swal({
        title: 'User Deleted!',
        type: 'success',
    });
});
```

Actually works fine but i trying to simulate an unexpected error response and when the response is for example a 500 response code and a simple string the message shows in the modal.

Thats nice, but in my app i want that the default response for ajax errors was a json. In this case now the error message says: "[object Object]".

I think a good feature will be a configuration option to manage the error response, something like a function, for example:

```
{
 //... Another options,
   errorParser: function (error) {
       if(/*error_is_json*/) {
           // Returns some attribute from my object
           return error.message; 
       },
       return error;
   }
}
```

**Comment by t4t5** [comment]
You're probably looking for the [SweetAlert 2 fork](https://github.com/limonte/sweetalert2) since this library does not support any `preConfirm` option.
