### ISSUE TITLE
Sweet alert with phpmailer

### ISSUE THREAD

**Issue by FerchoM** [t4t5/sweetalert#682]
Hi everybody!.

In my index.html page have a form wich submit to a second one named mailer.php (wich uses phpMailer), here my code:
`<p><?php
<p>require_once("includes/class.phpmailer.php");
<p>$Nombre = $_POST['name'];
<p>$Correo = $_POST['email'];
<p>$Telefono = $_POST['phone'];
<p>$Mensaje = $_POST['message'];
<p>$correo = new PHPMailer();
<p>$correo->CharSet = 'UTF-8';
<p>$correo->IsSMTP();
<p>$correo->SMTPAuth = true;
<p>$correo->SMTPSecure = 'tls';
<p>$correo->Host = "myhost";
<p>$correo->Port = 587;
<p>$correo->Username   = "myuser";
<p>$correo->Password   = "mypass";
<p>$correo->SetFrom('myuser');
<p>$correo->AddAddress("mydestination");
<p>$correo->Subject = "Contacto desde sitio web";
<p>$correo->Body     =  "Nombre:  ".$Nombre."\r\n\r\n".
<p>"Email:  ".$Correo."\r\n\r\n".
<p>"Tel:  ".$Telefono."\r\n\r\n".
<p>"Mensaje:  ".$Mensaje."\r\n\r\n";
<p>if(!$correo->Send()) {
<p>echo "<script>alert('Error al enviar los datos, favor de intentarlo de nuevo.');location.href ='https://mydomain';</script>";
<p>} else {
<p>echo "<script>alert('Datos enviados, en breve nos comunicaremos con usted.');location.href ='https://mydomain';</script>";
<p>}
<p>?>`

This code is working very well, but I dont like the alert, so I change it to sweet alert and I'm trying to use swal inside of the condition but is not working, here is my code:

<p>if(!$correo->Send()) {
<p>echo "<script>swal('Error', 'Error al enviar los datos, favor de intentarlo de nuevo.', 'error');location.href ='https://mydomain';</script>";
<p>} else {
<p>echo "<script>swal('Datos enviados','En breve nos comunicaremos con usted.', 'success');location.href ='https://mydomain';</script>";
<p>}

I've been trying at least for 1 week and I cant do it, I've tried in my index page and swal is working with normal buttons, but when I send the info to mailer.php just dont work, I really have no problem with the syntax to send the mail (I'm using it with a few websites), but I'd really like to use sweet alert instead just alert.

I hope you can help me.

**Comment by abdurrahman** [comment]
It seems redirecting when trying to initializing sweet alert instance. I guess so, you shouldn't be redirect right after, have you tried that way ever ?

**Comment by FerchoM** [comment]
Actually is my first time using swal.
I've changed my mailer.php for the next:

<p>if(!$correo->Send()) {
<p>echo "<script type='text/javascript'>swal({
<p>  title: 'Error',
<p>  text: 'Lo sentimos, por el momento no hemos logrado enviar tu mensaje, intentalo nuevamente.',
<p>  type: 'error',  
<p>  confirmButtonText: 'Ok',
<p>  closeOnConfirm: false
<p>},
<p>function(){
<p>  window.location.href='mydomain';
<p>});
<p></script>";
<p>} else {
<p>echo "<script type='text/javascript'>swal({
<p>  title: 'Mensaje enviado,',
<p>  text: 'Gracias por contactarnos, en breve nos comunicaremos contigo.',
<p>  type: 'success',  
<p>  confirmButtonText: 'Cool!',
<p>  closeOnConfirm: false
<p>},
<p>function(){
<p>  window.location.href='mydomain';
<p>});
<p></script>";
<p>}
<p>?>
<p></script>
<p></body>
<p></html>

Is not what I wanted but it works really well and it's a good alternative.

**Comment by abdurrahman** [comment]
Yes, thats a quite solution as what you want 👍 
The first way which you posted, it'll be work to.. But you shouldnt use location href because, page will redirecting your domain while show up to sweet alert as i said :face_with_head_bandage: 

Have a good day ! :sun_behind_small_cloud:
