### ISSUE TITLE
SweetAlert Prompt issue in bootstrap modal

### ISSUE THREAD

**Issue by mathiastm** [t4t5/sweetalert#683]
I have been trying for more than two days to run SweetAlert prompt in a modal bootstrap without success ... the input is not accessible and I don't understand why. I need help please...

JsFiddle:
[https://jsfiddle.net/4tbmj9nL](https://jsfiddle.net/4tbmj9nL)

**Comment by yusucan** [comment]
https://github.com/t4t5/sweetalert/issues/412#issuecomment-234675096

**Comment by t4t5** [comment]
As @yusucan pointed out. It seems like this is related to the Bootstrap version of the library. Closing.
