### ISSUE TITLE
after confirm nothing happend using sweet alert in asp.net c#

### ISSUE THREAD

**Issue by OkkayChing** [t4t5/sweetalert#686]
pls check my following code :
<asp:Button ID="btnSubmit"  runat="server" Text="Submit" style="margin-bottom:20px;" OnClientClick="return Validate(this,event);" OnClick="btnSubmit_Click" />

  function Validate(ctl, event) {
        event.preventDefault();
        swal({
            title: "Do you want to save it?",
            text: "Please check Information before Submiting!",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Save",
            cancelButtonText: "Cancel",
            closeOnConfirm: true,
            closeOnCancel: true
        },
            function (isConfirm) {
                if (isConfirm) {
                
                    return true;
                } else {
                    return false;
                  
                }
            });
    }

**Comment by t4t5** [comment]
I have no idea where `btnSubmit_Click` is defined in your code. This is not an issue with SweetAlert.

**Comment by selenevs** [comment]
Hi, i hope someone can help me, i´m facing the same problem.  Sweet alert does pops(shows), but does no insert in the db. I´ve tried with other options without sweet alert and does works, but i want to use sweet alert. HELP ME 👍 

ASPX:
  <asp:Button ID="btnCheckin" runat="server" Text="Registrar" OnClientClick="return Confirm(this,event);"  OnClick="btnCheckin_Click" class="btn-login-with"  />

JAVASCRIPT
<script type = "text/javascript">
 function Confirm(ctl, event) {
event.preventDefault();
swal({
title: "Confirma tu identidad?",
text: "Colaborador",
type: "warning",
showCancelButton: true,
confirmButtonColor: "#DD6B55",
confirmButtonText: "Sí soy yo",
cancelButtonText: "No soy",
closeOnConfirm: true,
closeOnCancel: true
},
function (isConfirm) {
if (isConfirm) {
               return true;
            } else {
                return false;           
            }
        });
}
</script>

C#
protected void btnCheckin_Click(object sender, EventArgs e)
        {
        try
            {
                c._nip = _Text_Input.Value.Trim();
                c._colaborador = c.ValidarNIP(Convert.ToInt32(_Text_Input.Value))._colaborador;
                c._nomina = c.ValidarNIP(Convert.ToInt32(_Text_Input.Value))._nomina;
                if (c._nip != String.Empty)
                {
                    //Si el NIP ingresado es igual al obtenido en la búsqueda
                    if (_Text_Input.Value.Trim() == c.ValidarNIP(Convert.ToInt32(c._nip))._nip)
                    {
                        //insert 
                        c.RegistrarSubsidio(c._nomina);

                    }
                    else
                    {
                        msj.ErrorMsj("try once again", Page);
                    }
                }
            }
            catch (Exception ex)
            {
                HttpContext.Current.Response.Write(ex.ToString());
            }
        }
