### ISSUE TITLE
content not change when I make two alert with html content

### ISSUE THREAD

**Issue by tomoyuen** [t4t5/sweetalert#688]
A sweetalert with HTML content, i want show another when clicked this alert's confirm button,  the title is change normally, but the text is not change.

this is a [example](https://codepen.io/Toomo/pen/eWdXMY?editors=1111)

**Comment by t4t5** [comment]
That's a weird bug indeed. Thanks for reporting! I think using the new `content` option in SweetAlert 2 is much more reliable for rendering custom HTML now.
