### ISSUE TITLE
Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by drunkBottle6** [t4t5/sweetalert#689]
I'm newbie with web programming.
I try to change default alert with sweetAlert. 
here my code,

_print '<script src="'. base_url("dir") .'/plugins/jQuery/jquery-2.2.3.min.js"></script>'
                .'<link rel="stylesheet" href="'.base_url("dir") .'/plugins/sweetalert/dist/sweetalert.css">'
                .'<script src="'.base_url("dir") .'/plugins/sweetalert/dist/sweetalert.min.js"></script>'
                . '<script>'
                .'$( document ).ready(function() {'
                . 'swal("Warning","warning","error");'
                . '});'_

the alert didn't show up and when i see in the console, its said 
' Uncaught ReferenceError: exports is not defined '. 
Am i doing it wrong?

I appreciate any help, Thanks a lot !

**Comment by t4t5** [comment]
This must be something unrelated to SweetAlert. Click the error line in your console to see where the `exports`-function is defined and you'll find the source of your error.

**Comment by drunkBottle6** [comment]
Thanks a lot @t4t5  for you respond. i'm already fixed it. it happens maybe because i'm importing sweetalert.dev and sweetalert.min together.
