### ISSUE TITLE
Support for Internet Explorer 9 and 10?

### ISSUE THREAD

**Issue by mikece** [t4t5/sweetalert#69]
It seems that this only works on Internet Explorer 11 and newer.  Is there supposed to be support for IE 9 (the current browser baseline where I work)?

**Comment by t4t5** [comment]
Fixed.

**Comment by hyper0923** [comment]
Hii, I make a website where I use Sweet Library but the website work on all other browser but not work on IE11 (Internet Explore) what I can do please help, it's argent !
Thank you
