### ISSUE TITLE
OK Button

### ISSUE THREAD

**Issue by jonjie0317** [t4t5/sweetalert#692]
How can I remove **[**OK**]** button in `swal();` ? like this:<br>
`swal("Created!", "User has been created successfully!", "success");`
<br><br>

it has an **[**OK**]** button everytime you call `swal();`.
<br><br>

Thanks

**Comment by t4t5** [comment]
Hey there! You can hide the confirm button by using `{ showConfirmButton: false }`. You can find this option in the [docs](http://t4t5.github.io/sweetalert/).

**Comment by GullapalliAkhil** [comment]
@t4t5 thanks for the comment, it is helpfull
