### ISSUE TITLE
How to use multi alert in single method ?

### ISSUE THREAD

**Issue by Thilagavathi1** [t4t5/sweetalert#693]
Hi @t4t5 We have used your plugin it's useful for us. We are facing one issue, please check that.
FYI:  
I have used  two alerts in single method. But it works only one alert.For Your reference i have 
 created the fiddle please check the [link](https://jsfiddle.net/thilagavathi/uqn1hbwp/).

**Comment by t4t5** [comment]
Why would you want to show 2 alerts at the same time? That's a very weird example.

**Comment by deltab** [comment]
I think the intention is to show one after the other, not at the same time:

* show an alert telling the user which file to select;
* then open the file selector;
* then show another alert;
* then the second file selector.

It's just lacking code to wait for one step to complete before going on to the next.

@Thilagavathi1: would it be better to use a form? The user can see the whole process at once, read all the explanations, click when they are ready to upload, choose which order to do things in, and correct mistakes.

**Comment by t4t5** [comment]
Sorry for the late response, but yes, I think SweetAlert probably isn't very suitable for this use case. Think of SweetAlerts as quick dialog modals to convey short information. :)
