### ISSUE TITLE
How to close popup when esc is pressed without executing cancel method.

### ISSUE THREAD

**Issue by Sahil401** [t4t5/sweetalert#694]
Hi i am providing a method to my cancel button in my popup but when user press esc it executes the cancel event but i just want to close the popup on pressing esc.

**Comment by emilv** [comment]
That is very confusing for the user. Cancel and close is generally expected to behave the same way. I vote no to this feature.

**Comment by t4t5** [comment]
Agreed with @emilv. All cancel actions should behave the same way, regardless if they're called through the <kbd>ESC</kbd> key, the cancel button or by clicking outside.

In the upcoming new major release, there will be support for other types of buttons, in addition to "cancel" and "confirm", if that's what you need!
