### ISSUE TITLE
SweetAlert2: Unknown parameter "closeOnConfirm"

### ISSUE THREAD

**Issue by uddinmtm** [t4t5/sweetalert#696]
I'm newly using this alert, but i cant call the function and i get this warn `SweetAlert2: Unknown parameter "closeOnConfirm"` in the console. Why ?

**Comment by limonte** [comment]
Because you are using SweetAlert**2**, which is separated project from this one and have slightly different API. https://github.com/limonte/sweetalert2

**Comment by uddinmtm** [comment]
Oh, I see now. Thank you

**Comment by adrian1299** [comment]
Thank you @limonte I had the same problem, but I resolved the ptoblem.

**Comment by jlwgeneral** [comment]
how to solution

**Comment by BloodSucker123** [comment]
> how to solution

You have to use `preConfirm `

**Comment by carlos0202** [comment]
> > how to solution
> 
> You have to use `preConfirm `

What about implementing closeOnCancel?
