### ISSUE TITLE
quick double click button then sweetalert will close.

### ISSUE THREAD

**Issue by daoerche** [t4t5/sweetalert#697]
when you quick double click button then sweetalert will close for the first time. But quick double click button then not disappear for the second time. However that will close for the third time. And so on.

**Comment by daoerche** [comment]
quick double click will trigger cancel event looks like, when I add "closeOnCancel: false" then this bug disappear

**Comment by bjcangyue** [comment]
I met the same question。
before sweetalert shown, click the page and the sweetalert will hide。

**Comment by t4t5** [comment]
I'm not sure if you stumbled upon some weird inconsistencies, but otherwise this is the expected behaviour. When you double click, the first click will trigger the alert whereas the second one technically clicks outside of it, therefore closing it.

**Comment by daoerche** [comment]
thanks.
