### ISSUE TITLE
change text style (line-height)

### ISSUE THREAD

**Issue by rodrigoorrego** [t4t5/sweetalert#699]
hello, I'm new here! :) and I have a question....

is it possible that I can include/chance line-height (CSS style) on a sweet alert?

              swal({
                      title: 'Bem-vindo!',
                      text: '(..)', <-here I want to change/insert line-height
                      type: 'success'
                    });

thanks in advance! :)

**Comment by ekv88** [comment]
If I undestand correctly you want to change `.sweet-alert p { padding: 0px }` to `padding: 10px 0px;`
But if you want you can even use `{ html: true }` parameter and enable HTML in `{ text: "" }` parameter

**Comment by t4t5** [comment]
Using SweetAlert 2.0, you can easily change the line-height on `.swal-text` using your own CSS to override the default styling. :)
