### ISSUE TITLE
Change Text While Ajax Request Loading

### ISSUE THREAD

**Issue by gotoark** [t4t5/sweetalert#701]
How can i change the text inside the Sweet alert while the Ok Button Shows the loading Animation..?

`swal({   title: "Ajax request example",   text: "Submit to run ajax request",   type: "info",   showCancelButton: true,   closeOnConfirm: false,   showLoaderOnConfirm: true, }, function(){   setTimeout(function(){     swal("Ajax request finished!");   }, 2000); });`

**Comment by t4t5** [comment]
Using SweetAlert 2.0, you could add an event listener on `.swal-button--confirm` and then use `document.querySelector('.swal-text').innerText = "My text"`.
