### ISSUE TITLE
input type="password"

### ISSUE THREAD

**Issue by lislin** [t4t5/sweetalert#702]
how can i change <input type="text" tabIndex="3" /> to <input type="password" tabIndex="3" />

**Comment by ekv88** [comment]
Well there's no option for something like that.
But you can hack it easily:
After executing SWAL, just execute:
`$(".sweet-alert > fieldset").find("input").attr("type", "password");`

**Comment by t4t5** [comment]
There is actually an option like that. Just set `inputType` to `password`. :)

**Comment by alain8915** [comment]
I have a problem in an inputType password, because backspace does not working and i cant erase the input's content with it
