### ISSUE TITLE
Make user can customize id of confirm/cancel button

### ISSUE THREAD

**Issue by AlexVincent525** [t4t5/sweetalert#708]
I have an idea about make user can customize id of confirm/cancel button, which can make custom function easier.

**Comment by t4t5** [comment]
IDs are unnecessary, but you can customize the style of the buttons by using the unique classes `swal-button--confirm` and `swal-button--cancel` in SweetAlert 2.0.

**Comment by pballewsa** [comment]
An ID is really helpful for UI automated testing.  Anyone know how to set the ID of buttons on a sweet alert dialog?

**Comment by zerazeon** [comment]
This is workaround for someone who looking for id
`onOpen: function() { document.getElementsByClassName('swal2-confirm')[0].setAttribute('id','btnConfirm');document.getElementsByClassName('swal2-cancel')[0].setAttribute('id','btnCancel');}`
use method onOpen + javascript to add attribute.

**Comment by JaeDukSeo** [comment]
@zerazeon amazing thank you!
