### ISSUE TITLE
sweetalert input is disabled in AngularJs custom directive

### ISSUE THREAD

**Issue by akacanet87** [t4t5/sweetalert#710]
I want to show list in a modal, so I made modal by using directives.

(Actually, these directives are not my code)

In the list, each item has two buttons, one is to edit name and the other is to delete item.

This delete button shows confirm alert by using sweetalert and works well.

But in the edit button which shows prompt alert, input box doesn't work. It seems like disabled.

It works well when I move swal code to outside of directive, but inside of directive it did not work

any ideas of this?

**Comment by t4t5** [comment]
It's a bit hard to give advice without seeing any code, but my suggestion is to try the new 2.0 release. It render inputs in a smarter way to avoid bugs like these.
