### ISSUE TITLE
problem of using theming

### ISSUE THREAD

**Issue by jellybins** [t4t5/sweetalert#714]
when i creat custom style to load to the swal element ,i found that the sweetalert.js append the sweetalert style in the end of the head tag ,so my custom style code becomes before the sweetalert style.
then my custom style doesn't work.  only add "!important" in every style line.

**Comment by t4t5** [comment]
That's a good point and something I hadn't considered. I'll specify `insertAt: 'top'` for the `style-loader` in `webpack.config.js` for the next release!
