### ISSUE TITLE
Scrolling on chrome mobile 

### ISSUE THREAD

**Issue by cthulu** [t4t5/sweetalert#72]
On mobile chrome (android) it's possible to scroll the background page (not possible in the standard alert () dialog). Is this a feature? 
Reproduce : open the examples on mobile chrome.

**Comment by t4t5** [comment]
Scrolling doesn't bother me too much tbh. The only way to fix this afaik would be to add a class to the body that uses `overflow: hidden`, but I'm not sure I want to pollute the body tag with custom classes.
