### ISSUE TITLE
How to Insert a Line Break in text field?

### ISSUE THREAD

**Issue by tea7day** [t4t5/sweetalert#720]
I am using a sweetalert2.0.

How to Insert a Line Break in text field?

'\n' does not work anymore.

**Comment by t4t5** [comment]
You can inject custom content this way:

```javascript
const textEl = document.createElement("p");
textEl.innerText = "Hello\there";
swal({ content: textEl })
```

...which is a safer way to prevent XSS attacks.

It's a bit long though so I'd happily accept a pull request for accepting raw text nodes in addition to HTML elements. :)
