### ISSUE TITLE
Test sweet alert using Protractor

### ISSUE THREAD

**Issue by makwanaparth94** [t4t5/sweetalert#724]
I am automating the one site where developer set the sweet alerts with different values data like Error!,Success!,No Data Found! etc.
So i used the css selector but it give me an error .

I am attaching the screenshot of that sweet alerts with inspect code

So help me out ,how to handle this issue!

![image](https://user-images.githubusercontent.com/28529639/30521105-6bc66c28-9bd7-11e7-9f82-73540594df81.png)

**Comment by t4t5** [comment]
What's the error exactly?
