### ISSUE TITLE
Edge explor run error:  Object doesn't support property or method 'includes';

### ISSUE THREAD

**Issue by EthanOrange** [t4t5/sweetalert#729]
Object doesn't support property or method 'includes'  ---sweetalert.min.js (1,25427)

**Comment by EthanOrange** [comment]
@t4t5 
~ yes 
The same compliling weird on webpack ~  i trynow i need include the includes polyfill by myself  i works\

**Comment by lionralfs** [comment]
Hey @EthanOrange 

Are you still running into these issues in v2.0.6? `.include` polyfills are included in the library now, so you shouldn't have to do that anymore.

**Comment by EthanOrange** [comment]
@lionralfs  awesome thx!
