### ISSUE TITLE
sweet alert 2 :unknown parameter 

### ISSUE THREAD

**Issue by pasanrox** [t4t5/sweetalert#734]
I used sweet alert 2  for the confirmation of the delete process . but  whenever i click  on the delete  link
it gives unknown parameter in the console. 
![swal](https://user-images.githubusercontent.com/22095403/31003310-a304aeb4-a50c-11e7-9bdd-85148af17aea.png)

somebody help please

**Comment by t4t5** [comment]
Wrong repo: https://github.com/limonte/sweetalert2
