### ISSUE TITLE
npm sweetalert.min.js is not transpiled to es5

### ISSUE THREAD

**Issue by matt-w-cotton** [t4t5/sweetalert#736]
Hello, love the updates in v2!  I noticed that sweetalert.min.js uses es6 "const".  Was this intentionally left in?  Most min.js versions of libs I find are all es5 compatible.
Thank you

**Comment by t4t5** [comment]
This is weird. I thought `"target": "es5"` in the [`tsconfig.json`](https://github.com/t4t5/sweetalert/blob/master/tsconfig.json) would take care of this, but I must obviously be missing something.

**Comment by t4t5** [comment]
Ah, nevermind, it's the single `.js` file in `src` that isn't transpiled which contains a `const`. Will fix in the next update.

**Comment by matt-w-cotton** [comment]
Thank you for the excellent library!

**Comment by t4t5** [comment]
Fixed in v2.0.4
