### ISSUE TITLE
SweetAlert Issue with Visual Studio 2017

### ISSUE THREAD

**Issue by adhip94** [t4t5/sweetalert#737]
Hi,

I am trying to use sweetalert in my MVC application on Visual Studio 2017.

The CSS lint feature in VS 2017 is detecting errors in the css file
![image](https://user-images.githubusercontent.com/20703483/31052350-dff30d90-a69f-11e7-81ba-ccd1cf7e9a0d.png)
![image](https://user-images.githubusercontent.com/20703483/31052364-201c80d6-a6a0-11e7-90c2-6bbf42db0c16.png)

Also the sweetalert  does not appear when I call it.
![image](https://user-images.githubusercontent.com/20703483/31052375-5b71cce0-a6a0-11e7-8f91-56fcb702f3fc.png)

Can you help me resolve this?

**Comment by t4t5** [comment]
The CSS file should not be imported, since it's transpiled with PostCSS and injected automatically when you include `sweetalert.min.js`.

About the modal not showing, have you checked your JavaScript console?

**Comment by adhip94** [comment]
Oh ok. I have noticed that in the sweetalert.js file that there are only 14 lines of code
![image](https://user-images.githubusercontent.com/20703483/31052840-b2647190-a6ac-11e7-943a-27fbf2350aee.png)
But in the sweetalert.min.js there is a lot of code.
![image](https://user-images.githubusercontent.com/20703483/31052842-c6907da8-a6ac-11e7-9d50-146a224418ba.png)
I wanted to know is it necessary to include both the files or is any one of the files enough?

**Comment by t4t5** [comment]
You only need to include `sweetalert.min.js`.
