### ISSUE TITLE
How to add multiple text rows?

### ISSUE THREAD

**Issue by voviks21** [t4t5/sweetalert#740]
Hello
How can i make multiple rows or use html <br>?

**Comment by simon1tan** [comment]
Here's my hack based off https://sweetalert.js.org/docs/#content.
var span = document.createElement("span");
span.innerHTML='abc<br>efg'
swal({
  content: span,
});
I'm sure there is a better way.

**Comment by t4t5** [comment]
For now, @simon1tan's way of doing it is the way to, but I agree that it's a bit tedious for something as simple as adding a line break. I think the right way to do it would be to replace `\n` characters with `<br>` tags in the text option, so that people can write:

```javascript
swal(`Hello\nthere!`)
```

If anyone wants to tackle this (should be very simple), feel free to send a pull request!

**Comment by hectorx2x** [comment]
It has been hard to find a way to use the HTML elements, your hack has helped me, thank you very much friend!

PD: the "\n" it's not working for me, it's not doing a line break

**Comment by rkmax** [comment]
I think automatically things are not sood good, I think is better different options, example

- content: current object
- text: plain text (if you wat can add line break parsing here)
- html: receive html string

**Comment by juanjoseortizalbornoz** [comment]
u can use html to use "<br>" 
   swal({
        title: 'Info',
        html: 'test 1 <br> test 2' ,
        showConfirmButton: true,
		showCloseButton: true,
})
Bye

**Comment by mathurvishal** [comment]
const lines = ['You are very important to us, all information received will always remain confidential.', 'We will contact you as soon as we review your message.', 'We have sent an email to you at '+contact_email+' , Please check it for quick response.'];


swal('Thank you for contacting us!',lines.join('\n\n'),'success');


//worked for me!

**Comment by mathurvishal** [comment]
`const lines = ['You are very important to us, all information received will always remain confidential.', 'We will contact you as soon as we review your message.', 'We have sent an email to you at '+contact_email+' , Please check it for quick response.'];
				swal('Thank you for contacting us!',lines.join('\n\n'),'success');`

**Comment by yerskatmw** [comment]
for my case added <div> to cover the text will work
origina: Line0<br />Line1<br /> [not working]
after: <div>Line0<br />Line1<br /></div> [working fine]

swal({
    title: 'Mt Title',
    html: '<div>Line0<br />Line1<br /></div>',
 });

**Comment by CaptRango** [comment]
` 
  swal({            
            buttons: ["Wait ", "Add Details"],
             html: true,
             text: "Text one .\n  Text 2.\n Text 3."
   })
`
Here is the solution. Enjoy
