### ISSUE TITLE
keyboard shortcut for Yes/No

### ISSUE THREAD

**Issue by simon1tan** [t4t5/sweetalert#741]
Is there a way to trigger the swal buttons such as:
`$('.swal-button--yes').trigger('click') `

I have a sweetalert confirm with a Yes/No button. I would like to be able to press 'y' or 'n' to activate the buttons. I was able to use jwertyJS(https://www.keithcirkel.co.uk/jwerty/) for 'n' and swal.close() but that is not really activiating the button especially with 'Y' having lots more functionality(ajax request)

Doing this with the mouse works perfectly. with keyboard not so much. Any ideas? Perhaps enhancement to accept keyboard shortcuts.

**Comment by simon1tan** [comment]
Ok, found sweetalert2 which seems to have everything I need.

**Comment by t4t5** [comment]
You can use the `swal.close` function to trigger the values you need.

To trigger the `confirm` value for example, you would write:

```javascript
swal.close("confirm")
``
