### ISSUE TITLE
UI imperfection

### ISSUE THREAD

**Issue by Rezendeen** [t4t5/sweetalert#746]
http://prntscr.com/gxbeio

http://prntscr.com/gxbesm

I'm using chrome 61
windows 7

**Comment by lionralfs** [comment]
Hey @Rezendeen 

I just checked the [demo page](https://sweetalert.js.org/) on Chrome 61 / Win7 and it looks fine to me. Your site-specific styles might be interfering with/overwriting sweetalert's own CSS.

**Comment by Rezendeen** [comment]
Fixed, the problems was the CSS box-sizing
