### ISSUE TITLE
Uncaught Error: Bootstrap's JavaScript requires jQuery

### ISSUE THREAD

**Issue by pavanonemg** [t4t5/sweetalert#749]
I am getting jQuery 
![capture](https://user-images.githubusercontent.com/27006885/31600141-f1565e64-b272-11e7-976c-1265566202d8.PNG)
issue

**Comment by dturakhia** [comment]
Check if you are calling jquery before the bootstrap js script. You can get the latest jquery file from here [(https://code.jquery.com/)]

**Comment by t4t5** [comment]
SweetAlert uses neither Bootstrap nor jQuery, so this issue is unrelated to the library.
