### ISSUE TITLE
No way to take data from input

### ISSUE THREAD

**Issue by SanyBoK** [t4t5/sweetalert#750]
Well, tried new version, it's awesome, but how use data from content input?

swal({
        title: "Do you wan't to create mail box?",
        content: {
            element: "input",
            attributes: {
                placeholder: "jack",
                value: "{$user.f_translit}",
                type: "text"
            }
        },
        buttons: {
            mail_create: { text: "Create", value: "mail_create" }
        }
    }).then((value) => {
        if (value == null) return false;
        if (value.length < 3) {
            alert("Too small!");
        } else {
            location.href="..url.." + value;
        }
    });

Everytime I tried to set value - it sets mail_create. Hope you can help, ty

**Comment by t4t5** [comment]
You're using a custom button instead of just using the `confirm` button. If you just want your confirm button to say "Create", try this:

```javascript
swal({
  title: "Do you wan't to create mail box?",
  content: {
    element: "input",
    attributes: {
      placeholder: "jack",
      value: "{$user.f_translit}",
      type: "text",
    }
  },
  button: "Create",
})
.then((value) => {
  ...
```
