### ISSUE TITLE
node_module has no default export.

### ISSUE THREAD

**Issue by aadii104** [t4t5/sweetalert#761]
I am getting an error on doing this ( after running npm install again after some days), please help me here.
import swal from 'sweetalert';
ERROR:
node_modules/sweetalert/typings/sweetalert"' has no default export.

**Comment by aarongoa** [comment]
I faced this problem too. Is anyone working on it? Or should I give it a shot? 
@t4t5

**Comment by aadii104** [comment]
I am able to make my code working by doing so:
import * as swal from 'sweetalert'

but the problem is, it is not accepting the same attributes, nesting buttons with other attribute is giving an error.

**Comment by alenabi** [comment]
I'm facing the same problem too. Please fix that! @t4t5

**Comment by tavuntu** [comment]
same here

**Comment by aarongoa** [comment]
That should fix it.
Please merge @t4t5 :)

**Comment by sumitmatta998** [comment]
@t4t5 I have same issue.. can you tell me the latest version in which it is fixed.
