### ISSUE TITLE
Theming not working

### ISSUE THREAD

**Issue by chapuzzo** [t4t5/sweetalert#762]
I've been using this library for a while but I can't apply any kind of theming. I'm styling the `swal-footer` class in my css but as the original css code is inlined it takes precedence, how can I fix that?

**Comment by t4t5** [comment]
The `swal-footer` isn't styled using inline CSS? Where do you see that?

**Comment by girishpatil** [comment]
https://sweetalert.js.org/docs/#swal-footer Follow this, you can just include plain external css.
and BTW what are you trying to style??
