### ISSUE TITLE
Input returns empty string if defaultValue not changed

### ISSUE THREAD

**Issue by alex-osman** [t4t5/sweetalert#764]
A swal with an input element will return an empty string if the original value is unchanged.  For example:
```
swal({
  text: 'Enter some text',
  content: {
    element: 'input',
    attributes: {
      value: 'hello'
    }
  },
buttons: [true, true]
}).then((retVal) => {
  console.log(retVal)
})
```
The value of `retVal` is 
- `null` if you hit cancel
- `""` if you hit okay
- `"somestring"` if you actually change the input
- `""` if you remove all the text and submit an empty string

It should be "hello" if you hit okay, not an empty string.  There is no way to determine if someone removed all the text and wants to submit an empty string, or if they submitted the defaultValue/value.

I have tried changing `value` to `defaultValue` and that has no effect.

I believe this is because the input element is only calling `setActionValue` on change, and it on init it should be checking if it has a defaultValue, and then calling `setActionValue(this.defaultValue)`

**Comment by t4t5** [comment]
Sounds like a bug, and your analysis seems right. Feel free to send a pull request fixing this if you have time!

**Comment by gitspider** [comment]
The issue is still existed in the latest stable version 2.1.2.

**Comment by jaspreetsinghchhabra** [comment]
The issue still exists on version 2.1.2.

**Comment by DrunkPyromaniac** [comment]
This fix was backed out via #774 for some reason.

**Comment by bk313131** [comment]
The same error

**Comment by joan-teriihoania** [comment]
Same error as well

**Comment by nickdavies791** [comment]
Anyone have a solution to this? I still get the same issue.

**Comment by DGINXREAL** [comment]
The same error is still exists

**Comment by janforth** [comment]
This bug still exists!

**Comment by Dennis4720** [comment]
This issue still exists.

**Comment by SkyNetRu** [comment]
This bug still exists!
got around it like this

```
                swal({
                    title: "Title",
                    text: "Some text",
                    content: {
                        element: "input",
                        attributes: {
                            type: "email",
                            defaultValue: defaultEmail
                        },
                    },
                    button: {
                        text: "Send",
                    }
                }).then(result => {
                    if ( !result ) {
                        result = defaultEmail;
                    }

                    ...
                });
```
