### ISSUE TITLE
Textarea input type Problem!

### ISSUE THREAD

**Issue by PeymanNaeimi** [t4t5/sweetalert#765]
Hi,
When I try to break line in textarea input type, modal confirmed.

I had added these too, but nothing happen:
allowEnterKey: false,
focusConfirm: false,

any one had advise for my problem?

Check the code here:
https://jsfiddle.net/piman/f28tn8hq/24/

**Comment by t4t5** [comment]
You example is using the [SweetAlert 2 fork](https://limonte.github.io/sweetalert2/) which is a separate project.
