### ISSUE TITLE
How to post HTML in SWAL

### ISSUE THREAD

**Issue by jibboo** [t4t5/sweetalert#766]
I want to put HTML into my text parameter, but I get stuff like this:

<b>This is a bold sentence</b>. 

It actually shows the html tags instead of rendering the html.  I have tried putting the html in the 'text' paramater, 'content' parameter and 'html' parameter.   None work.  Help

`var msg = $("<div></div>").html("<p>User is not <b>logged in</b> or user's <b>session has expired</b>.</p><p>Please log in to continue.</p>");
        
swal({  
    icon:"warning",
    title:"Unable to validate user.",
    content: msg, 
    buttons: { 
        login: {
            text:"Login",
            value:"Login"
        }
   }
});`

**Comment by jibboo** [comment]
OK, ... I was able to display HTML by doing it direct through javascript, but it does not work when using jQuery (as above).

`
var msg = document.createElement("div");
msg.innerHTML = "<p>Either user is not logged in or user's session has expired.</p><p>Please log in to continue.<p>";

        swal({  icon:"warning",
                title:"Unable to validate user",
                content: slider,
                buttons:{ 
                    login: {
                        text:"Login",
                        value:"Login"
                    }
                }
            })
`

**Comment by t4t5** [comment]
You'll have to create your DOM nodes using [content](https://sweetalert.js.org/docs/#content). We might make this easier to do in the future using the [React plugin](https://github.com/sweetalert/sweetalert-react) for example.
