### ISSUE TITLE
How to prefill input text

### ISSUE THREAD

**Issue by sarphu** [t4t5/sweetalert#769]
on pop up of swal. is there any method to prefill them, e.g. for editing a text

**Comment by t4t5** [comment]
```javascript
swal({
  content: {
    element: "input",
    attributes: {
      value: "pre-filled text",
    },
  },
});
```

See: https://sweetalert.js.org/docs/#content

**Comment by Fredemb** [comment]
@t4t5 s solution seems to work, except if it is never edited, in which case the swal returns an empty string, regardless of the pre-filled value
