### ISSUE TITLE
IE 11 issue

### ISSUE THREAD

**Issue by adhip94** [t4t5/sweetalert#775]
I keep getting this issue on IE11

![image](https://user-images.githubusercontent.com/20703483/33313659-56c5bb82-d451-11e7-985a-768efd5f172e.png)

Assign function does not work in IE11 I guess, is it possible to use a polyfill function instead?

**Comment by lionralfs** [comment]
Hey @adhip94.
Thanks for reporting this.
Which version of sweetalert are you currently using?

**Comment by adhip94** [comment]
Even I don't remember the exact version since I am using the js file in my application itself, as far as I remember it is v2 which I had downloaded on 3rd October 2017 (from my application svn logs)!

**Comment by lionralfs** [comment]
Could you try using the [latest version](https://github.com/t4t5/sweetalert/releases/latest) to see if the problem persists?

**Comment by adhip94** [comment]
Ok, I used the Polyfill function for assign from the [msdn site](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill) in the sweetalert js and it works fine now , I am not getting any error for assign but now I am getting another error for the promises function "then" since again then is not supported in IE11. Any solution for this?

**Comment by lionralfs** [comment]
You shouldn't have to manually include any polyfills if you use the latest version.

**Comment by adhip94** [comment]
Ok, I have used the minified js file in my application from the link you have sent above 
![image](https://user-images.githubusercontent.com/20703483/33370872-e5f314e4-d51e-11e7-9c65-38137f7572a5.png)

But still in IE I am able to see the same error wherever I use then function for s
![image](https://user-images.githubusercontent.com/20703483/33370946-291b04ca-d51f-11e7-8fac-5074a9bc35d0.png)

A code snippet from my custom javascript of how I am using swal, the above error is coming here when I use .then(value)
![image](https://user-images.githubusercontent.com/20703483/33371485-e8789c32-d520-11e7-8a6a-11b7dd4383da.png)

Do let me know if I have done anything wrong!

**Comment by lionralfs** [comment]
IE11 does not support arrow functions, change
```js
.then((value) => {
 ...
});
```
to
```js
.then(function(value) {
 ...
});
```

Or transpile your code to ES5 using babel, for instance.

**Comment by adhip94** [comment]
Thanks, changing from arrow to function worked. :)
