### ISSUE TITLE
Ipad issues with sweet alert 2

### ISSUE THREAD

**Issue by normbain** [t4t5/sweetalert#780]
when using .then((result) => on an ipad with sweet alert 2 javascript stops working.

clarification: browse to https://limonte.github.io/sweetalert2/
using an ipad.
if the script on the page includes the code ".then((result) =" then 
the buttons will not work (javascript eror)

**Comment by lionralfs** [comment]
You are referring to a different sweetalert, sweetalert2 is located at https://github.com/limonte/sweetalert2

**Comment by limonte** [comment]
> https://limonte.github.io/sweetalert2/

this link is outdated, here's the correct one https://sweetalert2.github.io/

**Comment by legendarylion** [comment]
This probably shouldn't have been closed. It looks like this issue solved the issue: https://github.com/t4t5/sweetalert/issues/818
