### ISSUE TITLE
Getting value from multiple input?

### ISSUE THREAD

**Issue by HadiAkmal** [t4t5/sweetalert#788]
I'm using `content` with multiple `input` element:

`msg.innerHTML = '<input type="text" name="FirstName" value="Abu"> <input type="text" name="LastName" value="Ali"> test <b>123<b>';`

```
      content: msg,
      icon: 'info',
      buttons: ['Cancel', 'Save'],
```

Result:
![image](https://user-images.githubusercontent.com/14165645/34914858-4aa0abf8-f956-11e7-8bf9-2aacdf871995.png)

My question is, how do I retrieve the input value upon save?

Thanks in advance.

**Comment by girishpatil** [comment]
its a promise ... so after doing something like 
`swal("Write something here:", {
  content: 'input',
})
.then((value) => {
  swal(`You typed: ${value}`);
});`

Know more about it here [https://sweetalert.js.org/guides/#advanced-examples](url)

**Comment by HadiAkmal** [comment]
@girishpatil 

I can get the value if it's single input but I have 2 input field. When I tested it, the `value` output is `true` and I'm not getting the data that I keyin the 2 field.

**Comment by g4b0-88** [comment]
I found example at "https://sweetalert2.github.io/"

`const {value: formValues} = await swal({
  title: 'Multiple inputs',
  html:
    '<input id="swal-input1" class="swal2-input">' +
    '<input id="swal-input2" class="swal2-input">',
  focusConfirm: false,
  preConfirm: () => {
    return [
      $('#swal-input1').val(),
      $('#swal-input2').val()
    ]
  }
})

if (formValues) {
  swal(JSON.stringify(formValues))
}`

**Comment by limonte** [comment]
@g4b0-88 SweetAlert2 is a different project, it's repo is https://github.com/sweetalert2/sweetalert2

**Comment by t4t5** [comment]
@HadiAkmal Take a look at https://sweetalert.js.org/guides/#using-dom-nodes-as-content. You'll have to use `swal.setActionValue` if you want the promise to resolve a custom value (in this case, an array of strings seems right).
