### ISSUE TITLE
How can I modify overlay position when the box is displayed?

### ISSUE THREAD

**Issue by magicps5** [t4t5/sweetalert#789]
I'm using another platform S/W with sweetalert.
In my case, extjs's message box of certain conditions is already pop-up, before execute sweetalert.
And the sweetalert box is displayed behind the extjs's message box.
How can I pop-up of sweetalert box in the forefront on extjs's box?

![2018-01-16_18-09-46](https://user-images.githubusercontent.com/28850910/34981272-57de906a-faea-11e7-9fd1-59d0be65adf9.png)

**Comment by girishpatil** [comment]
try setting z-index for className `.swal-overlay` higher than extjs's z-index (maybe you can find its z-index value by inspecting)

**Comment by magicps5** [comment]
@girishpatil Thanks. Solved this issue with .swal_overlay with z-index.
That is very helpful to me.
