### ISSUE TITLE
Missing loading features

### ISSUE THREAD

**Issue by simplenotezy** [t4t5/sweetalert#790]
I previously used version 6.6.0 of the library, but have "upgraded" to version 2.

However, this seems to have removed the "loading" feature, which was quite useful. Now only the buttons have loading states, but this is not useful. E.g. I usually embed sweetalert on existing forms, so when they are submitted, then swal will show a loading icon, followed by a success or error swal.

This is no longer possible as of version 2, because `swal.showLoading();` no longer exists/works.

**Comment by limonte** [comment]
wrong repo, 6.6.0 is the version of SweetAlert2 https://github.com/sweetalert2/sweetalert2
