### ISSUE TITLE
ERROR TypeError: sweetalert_1.default is not a function

### ISSUE THREAD

**Issue by rafamds** [t4t5/sweetalert#796]
Hi, my sweet alert modal is not showing and I'm getting this error on the console:

``` 
ERROR TypeError: sweetalert_1.default is not a function
```
![image](https://user-images.githubusercontent.com/924985/35653762-93177180-06e1-11e8-8edc-48cf3fb2c2cf.png)

I'm using Angular v5 and SweetAlert 2.1.0. 

I'm importing it with the following code:
```js
import swal from 'sweetalert';
``` 
And I'm trying to show a simple alert with the following code:

```js
swal("Hello world!");
```

Any tips?

**Comment by rafamds** [comment]
I found the error:

I was importing it like the above code, as the documentation says but I had to import it with the following code:

```js
import * as swal from 'sweetalert';
```

**Comment by Jossymelgar** [comment]
![image](https://user-images.githubusercontent.com/8672166/36518132-cbb0db3e-174a-11e8-9dbf-ffb0a1df0b7a.png)


 no me sirve

**Comment by Jossymelgar** [comment]
bueno sirve pero me da ese error

**Comment by seanmavley** [comment]
Same error. Nothing changes, even with @rafamds approach. His approach gives:

```Cannot invoke an expression whose type lacks a call signature. Type 'typeof "/home/khophi/Developments/Angular/PackageToMe/node_modules/sweetalert/typings/sweetalert"' has no compatible call signatures```

**Comment by lionralfs** [comment]
@seanmavley take a look at #799, this might be a duplicate of that issue.

**Comment by seanmavley** [comment]
@lionralfs thanks for pointing out. I was just about to reference that issue in this thread. The #799 solution you presented is working fine here too.

Thanks.
