### ISSUE TITLE
Failed to download css

### ISSUE THREAD

**Issue by pintilies** [t4t5/sweetalert#811]
I don't know if it is an issue, but after installing it, adding the 3 files in the main page(SweetAlert.min.js, sweet-alert.js, sweet-alert.css) there are a couple of exception in the browser developer mode, cannot load the css files due tu missing ".css" extention in sweetalert.css:

@import './css/icons';
@import './css/text';
etc..

If I add ".css" extension then there are loaded succesfully? Can this problem be fixed?

Thanks.

**Comment by t4t5** [comment]
I think you might be using an old version if the library.

Since 2.0, you don't need to import the CSS manually. Simply import the JS file and the CSS will automatically be there too. :)

See: https://sweetalert.js.org/guides/
