### ISSUE TITLE
SweetAlert in IE11

### ISSUE THREAD

**Issue by irajchardoli** [t4t5/sweetalert#813]
HI , Im using sweetalert latest version ,
The below code in IE11 not working , and give syntax error:

`swal("Click on either the button or outside the modal.").then((value) => {swal(`The returned value is: ${value}`);});`

please help me how to fix this error ?

**Comment by t4t5** [comment]
Hi @irajchardoli. IE11 does not support some modern ES6 features like [arrow functions](https://caniuse.com/#feat=arrow-functions) and [promises](https://caniuse.com/#feat=promises).

To fix it, you should either compile your code with [Babel](https://babeljs.io), or use a [Promise-polyfill](https://www.npmjs.com/package/promise-polyfill) with some older syntax:

```javascript
swal("Hello")
.then(function(value) {
  swal("The returned value is " + value)
})
```
