### ISSUE TITLE
How to add custom html to swal

### ISSUE THREAD

**Issue by srikanthcx** [t4t5/sweetalert#823]
I was trying to add custom html to swal, but it's not taking the html. What was the solution for the above. Please help me on this.
Thanks

**Comment by lionralfs** [comment]
Hey @srikanthcx 

Does [this](https://github.com/t4t5/sweetalert/pull/421#issuecomment-372073765) solution work for you?

**Comment by lionralfs** [comment]
Would something like this work?

```js
const wrapper = document.createElement('div');
wrapper.innerHTML = YOUR_DYNAMIC_HTML;

swal({
  title: 'Test Title',
  text: 'Test Text',
  content: wrapper
});
```

**Comment by srikanthcx** [comment]
perfect but it will work one time because, if run second time it's saying wrapper is already declared.

**Comment by lionralfs** [comment]
You could wrap everything above in a function that takes the dynamic html as an argument. 
Then, you can just call the function with your html instead of calling swal directly.

**Comment by srikanthcx** [comment]
I was trying something like this

```
var errors = "<ul class='error-list'><% @user.errors.full_messages.each do |message| %><li><%= message %></li><% end %></ul>";
swal({
      title: "Error!",
      content: errors, 
      icon: "error"
});
```

**Comment by lionralfs** [comment]
Can you try this:

```js
(function() {
  const wrapper = document.createElement('div');
  wrapper.innerHTML = "<ul class='error-list'><% @user.errors.full_messages.each do |message| %><li><%= message %></li><% end %></ul>";
  swal({
    title: "Error!",
    content: wrapper, 
    icon: "error"
  });
})();
```

If that doesn't work, I will need some more context. Could you provide me with a clearer example?

**Comment by srikanthcx** [comment]
Thanks @lionralfs , this doesn't work for me  i will use sweetalert2.

**Comment by t4t5** [comment]
@srikanthcx It looks like you’re trying to use ERB templating code in your custom HTML. That’s not going to work in SweetAlert nor any of its forks since SweetAlert is a client-side library. If you want this to work, you’ll have to render your ERB code in some other HTML-element, then clone that into the Swal modal.

**Comment by srikanthcx** [comment]
@t4t5 Same thing i was dooing. In js.erb file i am doing below code. It will give the html output. No issue with swal. But issue is swal is not taking html code.

```
var errors = "<ul class='error-list'><% @user.errors.full_messages.each do |message| %><li><%= message %></li><% end %></ul>";
swal({
      title: "Error!",
      content: errors, 
      icon: "error"
});
```

**Comment by t4t5** [comment]
@srikanthcx I see. In that case, @lionralf’s solution should work fine. Just use `var wrapper = ...` instead of `const wrapper = ...` and I think the error message you encountered should go away.

**Comment by AmjadIqbal** [comment]
Use this package , https://amjadiqbal.github.io/sweetalert/forms.html
videos guide included

**Comment by Sudangadekar** [comment]
how we use anchor tag on sweetalert??

**Comment by AmjadIqbal** [comment]
hey @Sudangadekar  see this forms guide you can include any html inside sweetalert , https://amjadiqbal.github.io/sweetalert/forms.html

**Comment by kiditran** [comment]
> Can you try this:
> 
> ```js
> (function() {
>   const wrapper = document.createElement('div');
>   wrapper.innerHTML = "<ul class='error-list'><% @user.errors.full_messages.each do |message| %><li><%= message %></li><% end %></ul>";
>   swal({
>     title: "Error!",
>     content: wrapper, 
>     icon: "error"
>   });
> })();
> ```
> 
> If that doesn't work, I will need some more context. Could you provide me with a clearer example?

Thank you so much. I just try and done it with https://sweetalert.js.org/

**Comment by arcahyadi** [comment]
> Can you try this:
> 
> ```js
> (function() {
>   const wrapper = document.createElement('div');
>   wrapper.innerHTML = "<ul class='error-list'><% @user.errors.full_messages.each do |message| %><li><%= message %></li><% end %></ul>";
>   swal({
>     title: "Error!",
>     content: wrapper, 
>     icon: "error"
>   });
> })();
> ```
> 
> If that doesn't work, I will need some more context. Could you provide me with a clearer example?

thx for the trick
