### ISSUE TITLE
button center 

### ISSUE THREAD

**Issue by rapeflower** [t4t5/sweetalert#834]
How do I make the button centered

**Comment by davemuir** [comment]
you can ctrl+f for .swal-footer in the dist/sweetalert.min.js and update the style it's dumping for text-align:right to center.  I think this should be committed to the project as the buttons look pretty off to the right.

**Comment by rexx-org** [comment]
Thanks for the tip. Works well! I agree that multiple buttons look better when centered. Hopefully someone could add "align" property for button object?

**Comment by t4t5** [comment]
No need to change the repo's source code. You can simply add the following CSS to your page:

```css
swal-footer {
  text-align: center;
}
```

You can find more styling options [here](https://sweetalert.js.org/docs/#theming).

**Comment by rexx-org** [comment]
Thanks for the link to the themes; should have looked there first! 
Just to clarify, the change should be:
.swal-footer {
  text-align: center;
}
Works perfectly.
