### ISSUE TITLE
Not able to Add a hyperlink in the sweet alert

### ISSUE THREAD

**Issue by adiwithadidas** [t4t5/sweetalert#845]
Hi Guys,
This is is my code which i am using to add a hyperlink in the text .
``swal({
            title: 'This is the ',
            text: '<a href="http://www.externalwebsite.com" target="_blank">externalwebsite.com</a>',
            html: true,
            showCancelButton: true,
            allowOutsideClick: true,
            goToExternal: true,
            externalUrl: 'http://www.externalwebsite.com',
            confirmButtonText: "Continue"
        });``

But it doesn't come out properly. Here is how it comes 

![screenshot_32](https://user-images.githubusercontent.com/3817327/41997254-18a2f4bc-7a75-11e8-8d83-928bdd7f244c.png)

Can you please let me know how can add an anchor tag inside the sweet alert.

Thanks
Adi

**Comment by SergeyW** [comment]
https://sweetalert.js.org/guides/#upgrading-from-1x
html is no longer used. Instead use the content object.

**Comment by adiwithadidas** [comment]
Hi @SergeyW ,
Thanks for your reply. Yeah when i researched a bit about it, I got to know about the same. 

But unfortunately, I am not able to place a hyperlink in the alert box  with content object also. I had searched for some examples and i got many of them but all are about adding HTML form elements, Buttons, etc and none about hyperlinks or anchor tags. 
If you can show me how to add an anchor tags or may be share some examples similar to that, it would be great.


Thanks
Adi

**Comment by t4t5** [comment]
Hey there,

The reason the `html` parameter has been disabled is to discourage use cases where the website could potentially be XSS-attacked.

However, you should still be able to render raw HTML by passing a DOM node to the `content` parameter, like this:

```javascript
const el = document.createElement('div')
el.innerHTML = "Here's a <a href='http://google.com'>link</a>"

swal({
  title: "Hello!",
  content: el,
})
```

**Comment by adiwithadidas** [comment]
Thanks a lot @t4t5

**Comment by PrasaddTelemerge** [comment]
Thank you so much @t4t5
