### ISSUE TITLE
Sweetalert1 & Sweetalert2  coexisting together?

### ISSUE THREAD

**Issue by marchantm** [t4t5/sweetalert#850]
I'm using Crudbooster for my projects and I need to keep Sweetalert1 but also need for some modules the new functionalities. It is very complicated to replace the swal that refer to the old.

There is any way to do this?

Thanks,

**Comment by stack-its** [comment]
I have the same question of using them side-by-side, but just using jQuery.  Quite a lot of code & the change over will take a long time.  What about changing the swal callout to swal2 on the new version?  How difficult would that be to do?

Appreciate a contributor's attention,

Thanks,  bill

**Comment by t4t5** [comment]
The projects have taken different paths to solve problems, and I don't think a merge is realistic in the near future unfortunately.
