### ISSUE TITLE
How to set dynamic value in input field

### ISSUE THREAD

**Issue by rahul7p** [t4t5/sweetalert#867]
@t4t5 
 I want to set dynamic value in input field when sweet alert open.
**inputValue** : text_val

here text_val is dynamic value
And when I set dynamic value then it's showing me undefine.

**Comment by t4t5** [comment]
You can do it like this:

```javascript
swal("Write something here:", {
  content: {
    element: "input",
    attributes: {
      value: "Hello"
    }
  }
})
```
