### ISSUE TITLE
IE11 "Confirm" exclamation mark bug

### ISSUE THREAD

**Issue by Pixel-Solitaire** [t4t5/sweetalert#87]
In the 4th example on «tristanedwards.me/sweetalert» (*the warning message with a function attached to the "Confirm"-button*), with IE11 the bullet of the exclamation mark is so much to the left that its out of the circle (*see image*). 
![sweet-bug](https://cloud.githubusercontent.com/assets/943538/4566079/7824d006-4f25-11e4-9e19-9b0819a891f7.gif)

**Comment by t4t5** [comment]
Fixed.
