### ISSUE TITLE
官网的一处错误

### ISSUE THREAD

**Issue by legolas-zeng** [t4t5/sweetalert#870]
![_20181018094704](https://user-images.githubusercontent.com/27952739/47126380-e2770100-d2ba-11e8-82b3-f6b86f71bc60.png)
我在官网上看到这个，`returnfalse`，其实应该是`return false`，返回false，一处错误，希望官网能改过来。

**Comment by t4t5** [comment]
Sorry, I won't be able to work on this issue unless it's in English.
