### ISSUE TITLE
How to Add Link in this code ?

### ISSUE THREAD

**Issue by IANirab** [t4t5/sweetalert#871]
Hi,
Here is my javascript code ......I can't add link in "ok" button;

`<script type="text/javascript">
$(document).ready(function() {
              $("#confirm-btn-alert<?php echo $result['id']; ?>").click(function(){

                  swal({
                    title: "Are you sure?",
                    text: "Once deleted, you will not be able to recover this file!",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true,
                  })
                  .then((willDelete) => {
                    if (willDelete) {
                      swal("Poof! file has been deleted!", {
                        icon: "success",
                      });
                    } else {
                      swal("Your imaginary file is safe!");
                    }
        });

  });
});

</script>`

**Comment by t4t5** [comment]
You can use JavaScript's `location.href` to redirect the user.

```javascript
swal({
  title: "Go to Google?",
  text: "Clicking the button will redirect you to Google's website",
})
.then((shouldRedirect) => {
  if (shouldRedirect) {
    location.href = "https://www.google.com";
  }
})
```
