### ISSUE TITLE
How to handle confirm button action?

### ISSUE THREAD

**Issue by brkbzdg94** [t4t5/sweetalert#872]
I want OK button click then after, return a value. how can i do this?

function mySwalAlert(atitle, atext, atype) {
		var rtn = null;
		swal({
			title: atitle,
			text: atext,
			type: atype,
			showCancelButton: true,
			confirmButtonColor: "#EF5350",
			confirmButtonText: "Evet!",
			cancelButtonText: "Hayır",
			closeOnConfirm: false,
			closeOnCancel: false
		},
			function (isConfirm) {
				if (isConfirm) {
					rtn = 1;
				}
				else {
					rtn = 0;
				}
			});
		if (rtn == 1)
			return true;
		else
			return false;
	}

But always return false. Because firstly function(isConfirm){ } run

**Comment by brkbzdg94** [comment]
Always return false, because firstly run ;
function mySwalAlert(atitle, atext, atype) {
		var rtn = null;
		swal({
			title: atitle,
			text: atext,
			type: atype,
			showCancelButton: true,
			confirmButtonColor: "#EF5350",
			confirmButtonText: "Evet!",
			cancelButtonText: "Hayır",
			closeOnConfirm: false,
			closeOnCancel: false
		},
			function (isConfirm) {
				if (isConfirm) {
					//alert("true");
					rtn = 1;
				}
				else {
					//alert("false");
					rtn = 0;

				}
			});

		if (rtn == 1)
			return true;
		else
			return false;
	}

**Comment by t4t5** [comment]
It looks like you're using an old version of the library. Take a look at the [upgrade guide](https://sweetalert.js.org/guides/#upgrading-from-1x)
