### ISSUE TITLE
Button too big

### ISSUE THREAD

**Issue by Badetuch** [t4t5/sweetalert#876]
Hey, i made an custom button ( http://prntscr.com/lccisu )
But now the "Ok" Button from sweetalert has the same size ( http://prntscr.com/lccj6r )

Is there anything i can add into my style.css to make a custom Button size for sweetalert?

Hope sb can help me 

Again sorry for my bad English

Badetuch ~Elia

**Comment by t4t5** [comment]
Hey there, sorry it's going to be impossible to solve your issue without the source code.
