### ISSUE TITLE
Use SweetAlert input content

### ISSUE THREAD

**Issue by elig-45** [t4t5/sweetalert#879]
### What is the variable containing the user input ? If I for example want to set up a condition if the users enter a correct password in the SweetAlert box ?

Till then, I use Js `prompt()` to do this ; but I am looking forward to replace the `alert()`, `confirm()` and `let var = prompt()` by better looking SweetAlerts.

Thanks a lot and sorry for my maybe incorrect English ; I come from France 🇫🇷 😄

**Comment by t4t5** [comment]
Check out these 2 examples from the docs:

- [How to get the user's value from an input](https://sweetalert.js.org/guides/#ajax-requests)
- [How to change the input to a password type](https://sweetalert.js.org/docs/#content)

Bonne chance! :)

**Comment by elig-45** [comment]
Thanks

Eli G

Envoyé de mon iPad EA
