### ISSUE TITLE
Sweetalert Confirm Alert with PHP confirmation Event

### ISSUE THREAD

**Issue by KeinWeb** [t4t5/sweetalert#882]
Hello, my questions is simple, its the fact that if it possible with Sweetalerlt that when i create an confirmation Alert that if the user press okay or something like this that an php event were call?Example an mysql update function started to run.Thank you for all answers and im sorry for my bad english.

**Comment by t4t5** [comment]
SweetAlert is a client-side library. If you want it to call a PHP script, you'd have to do an AJAX call to some PHP endpoint.
