### ISSUE TITLE
Keyboard shortcut problem with showCancelButton

### ISSUE THREAD

**Issue by philfreo** [t4t5/sweetalert#89]
If you use sweetalert like a confirm() prompt (Ok/Cancel) via `showCancelButton` then spacebar should be the same as pressing "cancel" (NOT the "ok" button), in order to mirror what happens in OS X during `confirm()`

Or, if you don't like spacebar being the same as "cancel" then you should just have spacebar do nothing if `showCancelButton` is enabled

**Comment by t4t5** [comment]
I have decided to disable the spacebar completely as of version 2.0. Closing.
