### ISSUE TITLE
Conflict with jQuery

### ISSUE THREAD

**Issue by blackfyre** [t4t5/sweetalert#91]
There's a conflict bug with jQuery.
If the swal lib is loaded after jQuery, it throws a <code>Uncaught TypeError: Cannot read property 'querySelector' of null</code> error.

This is due to that jQuery modifies the <code>querySelector</code>, after it's loaded.

#56 Fixes this issue, as does the description in #53.

**Comment by t4t5** [comment]
This is now fixed.
