### ISSUE TITLE
Feature Suggestion: Don't show again

### ISSUE THREAD

**Issue by jimbrew** [t4t5/sweetalert#931]
it would be good to have a checkbox option on the popout alerts to not show again.

Similar to this:
![image](https://user-images.githubusercontent.com/35928790/77909106-a522eb00-7284-11ea-8dcb-8a057226f141.png)

**Comment by t4t5** [comment]
You can create more advanced modals where you set the DOM content: https://sweetalert.js.org/guides/#using-dom-nodes-as-content
