### ISSUE TITLE
Can not Change Color of Pop-Up button 

### ISSUE THREAD

**Issue by devishraq** [t4t5/sweetalert#989]
After adding sweetalert in my JS but can not change the 
<img width="960" alt="Screenshot_19" src="https://user-images.githubusercontent.com/101325013/165504798-2fd5662c-5862-4eda-ab7d-ed82a3b4419c.png">
color of the Button.

**Comment by dnizfor** [comment]
swal({
  confirmButtonColor: '#8CD4F5',
});

**Comment by sailonthrough** [comment]
Your email is received and will be handled  as soon as possible,and this is an automatic reply,I will respond to your message  immediately when I see it.Thank you.
